feat(slack): Set level to color on slack attachment
getsentry/sentry pull request #10016
Opened 2018-10-04 03:51 UTC by iiogmgo

hello, 
I want to see again the color of level on slack notification like before sentry integration(web hook).

Like this
![webhook-screenshot](https://imgur.com/1m7D69E.jpg)

2018-10-10 20:11 UTC, EvanPurkhiser commented
@saragilford have any product thoughts on if we would want to merge this?

2018-10-15 18:50 UTC, saragilford commented
From a product perspective, this works for me.

2018-10-15 20:03 UTC, evanpurkhiser requested changes
Just one minor comment @iiogmgo and then this is good to go :)

2018-10-15 20:03 UTC, EvanPurkhiser commented on src/sentry/integrations/slack/utils.py
> -NEW_ISSUE_COLOR = '#E03E2F'
Could you get rid of `NEW_ISSUE_COLOR` and then down where we set the color just default to `LEVE_TO_COLOR['error']` if there is no level.

2018-10-19 18:54 UTC, evanpurkhiser approved these changes

2018-10-19 18:55 UTC, merged

2018-10-19 18:55 UTC, EvanPurkhiser commented
Thanks so much @iiogmgo :D