feat: DIF UI Update + Delete
getsentry/sentry pull request #10038
Opened 2018-10-08 13:57 UTC by HazAT

This PR changes the UI for Debug Files in the project settings.

- You can search for symbols now + paging
- You can delete symbols

The separation between Versioned dSYMs and unreferenced dSYMs does not work for all DIFs Sentry supports.

More PRs will follow in regards to DIF handling but this is the first really helpful change.

![screenshot 2018-10-08 15 53 19](https://user-images.githubusercontent.com/363802/46613136-be752c00-cb12-11e8-943b-43d6c411399d.png)

2018-10-10 13:57 UTC, markstory commented on src/sentry/api/endpoints/debug_files.py
> +        Retrieve a list of debug information files for a given project.
Should this be 'delete'?

2018-10-10 13:57 UTC, markstory commented on src/sentry/api/endpoints/debug_files.py
> +                                     DIFs of.
This endpoint doesn't list anything; should this be updated?

2018-10-10 13:57 UTC, markstory commented on src/sentry/api/endpoints/debug_files.py
> +                    debug_file.delete()
Should the get() be inside the transaction scope?

2018-10-10 13:57 UTC, markstory commented on src/sentry/static/sentry/app/views/projectDebugFiles.jsx
> +  mixins: [ApiMixin, OrganizationState],
I thought we were preferring es6 classes and higher order components for setting organization state? cc @billyvg

2018-10-10 13:57 UTC, markstory commented on src/sentry/static/sentry/app/views/projectDebugFiles.jsx
> +              <div className="btn-group" style={{float: 'right'}}>
You can use the `pull-right` classname instead of an inline style.

2018-10-11 18:27 UTC, billyvg commented on src/sentry/static/sentry/app/views/projectDebugFiles.jsx
> +        <div className="ref-project-releases">
These class names should be updated (and are they even in use?) -- actually we don't even need all of these `div`s

2018-10-11 18:28 UTC, billyvg commented on src/sentry/static/sentry/app/views/projectDebugFiles.jsx
> +            {access.has('project:write') ? (
Let's always show the button but disable if no write access

2018-10-15 08:01 UTC, HazAT commented
@billyvg All updated + Updated Screenshot

2018-10-15 08:26 UTC, jan-auer requested changes

2018-10-15 08:27 UTC, jan-auer requested changes

2018-10-15 08:28 UTC, jan-auer commented
FTR, I'm adding associated symcache deletion in https://github.com/getsentry/sentry/pull/10052, so we don't have to cover this here.

2018-10-15 09:16 UTC, jan-auer approved these changes

2018-10-16 08:02 UTC, mitsuhiko approved these changes
Merge!

2018-10-16 09:17 UTC, merged