feat: Pull latest SDK information from the registry
getsentry/sentry pull request #10231
Opened 2018-10-23 13:23 UTC by kamilogorek

Instead of getsentry/getsentry#2304

2018-10-23 14:21 UTC, kamilogorek reviewed
Looks good. Need a double-check from @mitsuhiko though.

2018-10-23 14:43 UTC, mitsuhiko approved these changes

2018-10-24 12:37 UTC, HazAT commented
@tonyo Can you please double check with Team Ops if the location where we store the file is good?
Maybe we want to have something that is generally applicable, right now, the json file is stored in the same folder as the python file.

2018-10-24 14:24 UTC, tonyo requested changes

2018-10-25 09:41 UTC, kamilogorek commented
@tonyo ignored + forced build

2018-10-25 12:42 UTC, tonyo approved these changes
No idea yet why that travis job fails.

2018-10-29 11:38 UTC, tonyo commented
I'll take a look at the travis issue now.

2018-10-29 12:19 UTC, tonyo commented on src/sentry/utils/distutils/commands/build_js_sdk_registry.py
> +    def run(self):
I don't see any harm in overriding the entire `run()` method here.

2018-10-29 12:50 UTC, tonyo commented
@kamilogorek @HazAT lgtm now

2018-10-29 14:03 UTC, HazAT commented
@tonyo Thanks for your help, I will merge this now to have the latest version of the browser SDK available in the loader.

2018-10-29 14:14 UTC, merged