feat: Include triggering rules in webhook payload
getsentry/sentry pull request #10506
Opened 2018-11-09 00:34 UTC by legalosLOTR

### Context
At Flexport, we are heavy users of Sentry webhooks. We use these to assign, prioritize and route alerts through various systems. We have a bunch of different "alert rules" in the sentry UI which all fire the same webhook. But in the webhook, we cannot distinguish which particular rule fired. We need this information because it's an important input for prioritization.

### Solution
The solution is pretty simple. I just added code to wire the triggering rule names to the webhook payload.

### Test plan
- Run sentry locally and verify that the payload includes this field
- Update tests

2018-11-09 17:17 UTC, markstory commented on src/sentry/plugins/bases/notify.py
> +        return self.notify_users(event.group, event, map(lambda r: r.label, notification.rules))
Could use a list comprehension here

```suggestion
        return self.notify_users(event.group, event, [r.label for r in notification.rules])
```

2018-11-09 18:33 UTC, dcramer approved these changes

2018-11-09 18:34 UTC, dcramer commented
Thanks!

2018-11-13 18:38 UTC, legalosLOTR commented
Thanks for approving guys! When can we expect this to get deployed?

2018-11-13 18:51 UTC, dcramer requested changes
Would you mind making a few quick changes and I'll take some time to confirm this won't break any other existing integrations (or ill fix them ahead of landing this)?

2018-11-13 18:51 UTC, dcramer commented on src/sentry/plugins/bases/notify.py
> +        return self.notify_users(event.group, event, [r.label for r in notification.rules])
Could we change this to kwargs?

```suggestion
        return self.notify_users(event.group, event, triggering_rules=[r.label for r in notification.rules])
```

2018-11-13 18:51 UTC, dcramer commented on src/sentry/plugins/sentry_webhooks/plugin.py
> +    def notify_users(self, group, event, triggering_rules, fail_silently=False):
Just to future proof (and what I'm going to check in other plugins) could we add kwargs support?

```suggestion
    def notify_users(self, group, event, triggering_rules, fail_silently=False, **kwargs):
```

2018-11-13 18:56 UTC, dcramer commented
I think there's a low impact chance on this since:

1. Old Slack is fine
2. New Slack is fine
3. There's not many plugins which would even use the notify_users hook

So as long as we do the kwargs changes I think we're safe to merge, since I commonly used the kwargs pattern in a lot of endpoints to future proof them.

2018-11-13 20:16 UTC, legalosLOTR commented
Made the requested changes. I also grepped for `notify_users` and these are the only files that mention it.

2018-11-13 20:36 UTC, dcramer approved these changes

2018-11-13 20:36 UTC, merged

2018-11-13 20:36 UTC, dcramer commented
Thanks!