feat(chunk_upload): Indicate maximum file sizes
getsentry/sentry pull request #10762
Opened 2018-11-26 14:54 UTC by jan-auer

2018-11-26 15:00 UTC, HazAT approved these changes
LGTM, just one question.
Why is this an option now and the other "settings" are not? (like blob_size, max_chunks ...)

2018-11-26 15:00 UTC, mitsuhiko requested changes
This still needs to hard reject large uploads.

2018-11-26 15:30 UTC, mitsuhiko approved these changes

2018-11-26 16:15 UTC, jan-auer commented
HOLD until https://github.com/getsentry/getsentry/pull/2397 is finalized.

2018-11-27 13:54 UTC, jan-auer commented
@mitsuhiko Updated to feature flag.

2018-11-27 14:25 UTC, mitsuhiko approved these changes
lgtm. Can we make sure we deploy this only after we validated everybody who should be opted into it and loop sales in.

2018-11-27 15:30 UTC, merged