fix(api): Add pagination for channel.list in Slack integration
getsentry/sentry pull request #11064
Opened 2018-12-17 19:50 UTC by cjmaio

In the global Slack integration, channel.list is used to grab the channel ID. However, in Slack instances with > 1000 channels, this is insufficient. This change will fire off subsequent requests if needed to fetch the entire list of channels.

Fixes GH-10056

This was recreated from https://github.com/getsentry/sentry/pull/10057 after a bad Git merge

2019-01-25 21:24 UTC, evanpurkhiser requested changes

2019-03-06 13:48 UTC, viteksafronov requested changes

2019-04-29 14:11 UTC, Skyross commented
Anyone is involved for the resolution to this issue? Need any help?

2019-08-16 13:53 UTC, swankjesse commented
This issue is impacting my team!

2019-08-29 09:45 UTC, Skyross commented
I've done the same fix in private branch. Should I create another MR instead of current?

2019-09-27 21:17 UTC, PaarthB commented
@EvanPurkhiser @viteksafronov When do you plan to fix this issue?

2019-09-27 22:12 UTC, viteksafronov commented
> @EvanPurkhiser @viteksafronov When do you plan to fix this issue?

Well, I'm not a person who tried to fix an issue, but If nobody can deal with this, I may create a new MR because it works for me in our installation with my patch.

2019-09-29 00:13 UTC, PaarthB commented
> I may create a new MR because it works for me in our installation with my patch.

If you could do that, that'll be great.

2019-09-29 00:19 UTC, PaarthB commented
@viteksafronov If the MR is going to take long, could you share with me what changes you made, in an email? I could try to do the same.

2019-10-01 04:54 UTC, PaarthB commented
@viteksafronov Just confirming are you intending to raise a MR for this soon?

2019-12-30 13:08 UTC, artful88533 commented
we also have > 1000 channels (

2019-12-30 16:02 UTC, viteksafronov commented
> we also have > 1000 channels (

this PR should be closed, because the issue already fixed https://github.com/getsentry/sentry/pull/14887

2019-12-31 07:16 UTC, artful88533 commented
> this PR should be closed, because the issue already fixed #14887

Good news! Anybody knows when will the release be created with this fix?

2020-01-18 02:39 UTC, closed without merging