feat(app-platform): Add uninstall webhook
getsentry/sentry pull request #11451
Opened 2019-01-10 00:16 UTC by MeredithAnya

Adds the webhook sent when a sentry app is uninstalled. 

 **Header Resource**: 
```
'Sentry-Hook-Resource': 'installation'
```

**Payload:**
```javascript
{  
  "action": "deleted",
  "installation": {
    "uuid": "<uuid>"
  },
  "data": { },
  // user who uninstalled the app
  "actor": {
    "type": "user",
    "id": "<user_id>",
    "name": "<user_name", 
  }, 
}
```

Relies on some changes made in https://github.com/getsentry/sentry/pull/11426

2019-01-10 00:19 UTC, MeredithAnya commented on tests/sentry/mediators/sentry_app_installations/test_installation_notifier.py
> +            'action': 'deleted',
I'm keeping this whole payload in the test for the 'deleted' case incase down the road we change it to be different from install, and so we (aka me) don't forget to test the whole payload and not just the action

2019-01-22 22:12 UTC, mnoble requested changes

2019-01-22 22:12 UTC, mnoble commented on src/sentry/api/endpoints/sentry_app_installation_details.py
> +            action='deleted',
Doesn't look like the Mediator takes an `action` param. I feel like this should be failing something...

2019-01-23 18:39 UTC, mnoble approved these changes

2019-01-24 22:57 UTC, merged