fix(project-selector): Remove add project button for folks who cannot add a project
getsentry/sentry pull request #12521
Opened 2019-03-25 20:03 UTC by Chrissy

plus a couple follow-up fixed from review

2019-03-25 20:22 UTC, billyvg requested changes
Can we disable instead of hide?

2019-04-03 22:22 UTC, Chrissy commented
This has been updated to be disabled instead of hidden.

2019-04-03 22:27 UTC, billyvg approved these changes

2019-04-03 22:27 UTC, billyvg commented on src/sentry/static/sentry/app/components/projectSelector.jsx
> +            title={hasProjectWrite ? null : 'You need project write access to use this'}
`t()` - maybe "You don't have permission to add a project"?

2019-04-03 22:27 UTC, billyvg commented on src/sentry/static/sentry/app/components/projectSelector.jsx
> +            to={`/organizations/${org.slug}/projects/new`}
This should have a trailing slash I think?

2019-04-04 19:10 UTC, merged