ref(native): Remove symcaches and cficaches completely
getsentry/sentry pull request #13264
Opened 2019-05-17 07:54 UTC by jan-auer

Removes all remnants of symcaches and cficaches and drops them from the database.

**Context:**
- In #13197 we stopped to generate cache files during upload. 
- In #13224 we removed all code paths using symcaches and cfi caches during native event processing.
- In #13248 we removed all references to symcaches and cfi caches.

2019-05-17 08:01 UTC, mitsuhiko approved these changes

2019-05-17 08:11 UTC, mitsuhiko requested changes
Taking back my approval. The migration has unrelated stuff in it that is wrong.

2019-05-20 14:21 UTC, jan-auer commented
Updated.

2019-05-20 14:51 UTC, mitsuhiko approved these changes

2019-05-20 15:36 UTC, tonyo approved these changes
Marked the migration as dangerous, will run it offline.

2019-05-20 16:15 UTC, merged