feat: Support issue IDs as canonical parameters
getsentry/sentry pull request #13757
Opened 2019-06-20 17:57 UTC by dcramer

2019-06-20 17:57 UTC, dcramer commented
This would need tests + migrations, but putting this up to see what others think.

It'd allow us to use FOO-1ZA as a canonical resource in API endpoints and URLs.

For example, https://sentry.io/sentry/issues/FOO-1ZA

2019-06-20 20:47 UTC, wedamija commented
This seems ok to me. You'll need to change a bunch of url regexes for this to work though, we just search for `\d+` at the moment.

2019-06-21 13:10 UTC, markstory reviewed
I like the idea. It improves the ergonomics of our URLs. Would we also want to update the permalink in emails and API responses?

2019-06-21 16:42 UTC, dcramer commented on src/sentry/models/group.py
> +        params = {'project__slug': short_id.project_slug, 'short_id': short_id.id}
Maybe if we used it anywhere else, but given it still has to query multiple ways it seems unneeded at this point

2019-06-21 16:48 UTC, dcramer commented
Going to finish this off in some free cycles. I'm going to expose it in frontend routes too if its not too hard (but not use it as canonical yet).

2019-06-21 18:34 UTC, dcramer commented
Its a chunk of work to make the URLs accept it in the UI right now as they rely on GroupStore which would need to be id + short id aware first. Gonna not do that yet, and we can worry about that in a follow up.

2019-07-16 16:00 UTC, dcramer commented
Rebasing and going to merge this when I get time this week.

2019-07-17 20:57 UTC, dcramer commented
@markstory @wedamija actually yall didnt sign off on this. Mind reviewing formally?

2019-07-17 23:48 UTC, wedamija requested changes

2019-07-17 23:48 UTC, wedamija commented on src/sentry/south_migrations/0489_auto__add_field_groupredirect_previous_short_id__add_field_groupredire.py
> +            "CREATE INDEX CONCURRENTLY {} ON sentry_groupredirect (previous_short_id, previous_project_slug)".
This needs to be a unique index

2019-07-17 23:50 UTC, dcramer commented on src/sentry/api/urls.py
> +        r'^events/(?P<event_id>[^\/]+)/$',
I can revert - noticed it along the way and brings it in line with most other endpoints.

Right now it'd be a bit awkward if you queried /events/foo/ and got a generic 404 vs an "event not found".

2019-07-17 23:51 UTC, dcramer commented on src/sentry/models/groupredirect.py
> +    previous_short_id = BoundedBigIntegerField(null=True)
I dont think we can, but I dont quite recall the internals

2019-07-17 23:57 UTC, wedamija commented on src/sentry/api/urls.py
> +        r'^events/(?P<event_id>[^\/]+)/$',
Not blocking on this at all, mostly just curious about the change.

2019-07-18 15:49 UTC, dcramer commented
Resolved the index concern - anyone see anything else blocking?

2019-07-18 18:50 UTC, wedamija approved these changes
Looks good. Migrations are up to 0490, so you just need to rebuild the state before merging.

2019-07-18 20:35 UTC, merged