Feat/3rd party initiated installation
getsentry/sentry pull request #14459
Opened 2019-08-20 23:18 UTC by scefali

2019-08-26 18:31 UTC, MeredithAnya requested changes
So when testing this out, it seems like when you change the dropdown to an organization that already has the app installed, it first shows 'Accept & Install' and then updates to show the error/gray out the button. However there was enough time for someone to actually click the button and in doing so I was able to install the same integration twice on an org.

I think we need to handle this in the mediator OR add the unique constraint on the organization_id and the sentry_app_id for the SentryAppInstallation model

2019-08-27 19:25 UTC, scefali commented on src/sentry/static/sentry/app/components/modals/sentryAppDetailsModal.jsx
> +    closeOnInstall: PropTypes.bool.isRequired,
@MeredithAnya We don't need it if `onInstall` is redirecting us to another page. Is the issue that the prop type is required?

2019-08-27 19:26 UTC, scefali commented on src/sentry/static/sentry/app/views/sentryAppExternalInstallation.jsx
> +    const newUrl = document.referrer || '/';
@MeredithAnya Good suggestion. Let me make that change.

2019-08-27 19:59 UTC, scefali commented on src/sentry/static/sentry/app/components/modals/sentryAppDetailsModal.jsx
> +    closeOnInstall: PropTypes.bool.isRequired,
@MeredithAnya My bad, I think I gave you an incorrect explanation. The issue without the change is that even if the redirectUrl is given, `onClose` is still called. Meaning you don't actually redirect to the right place during installation. Adding the field `closeOnInstall` and not calling `closeModal` lets `onInstall` handle the redirect after installation. This wasn't an issue before the integrations page just has a popup and it didn't matter that the popup was closed after uninstalling but it does matter if the close behavior changes the current page.

2019-08-27 20:28 UTC, MeredithAnya approved these changes

2019-08-27 21:06 UTC, merged