feat(discover-2): Add querybuilder on discover-v2 data table
getsentry/sentry pull request #14675
Opened 2019-09-12 00:28 UTC by leedongwei

Making an early PR to get early feedback on the UI implementation. It's still very much a WIP.

Even though the `gridResizable` component is new and separated into the `app/component` folder, it is based on @dashed implementation using CSS Grids. The eventual implementation is to use his `table.tsx` to fetch the data and pass it to `gridResizable` for display.

There are 3 stages of functionality to this component:
1. Allow add/edit/remove columns (Flagged on Organizations)
2. Allow resizing of column width (Flagged locally)
3. Allow drag-to-rearrange columns (Flagged locally)

Global feature-flag boundary is set on `app/views/eventsV2/table.tsx`. 

Local flags are on `app/components/gridResizable/flags.tsx`. They are unused at the moment as there is no JS logic to the component but it will come in eventually to hide the function 2+3.

Refs SEN-956
Refs SEN-995 
Refs SEN-1028 
Refs SEN-1029

2019-09-13 18:03 UTC, lynnagara commented
Would be great to see this in Storybook

2019-09-17 00:55 UTC, dashed requested changes
Addressed some react warnings

2019-09-17 00:55 UTC, dashed commented on src/sentry/static/sentry/app/components/gridResizable/styles.tsx
> +export const GridEditGroup = styled.tr`
```suggestion
export const GridEditGroup = styled.th`
```

2019-09-17 01:00 UTC, dashed requested changes

2019-09-17 01:00 UTC, dashed commented on src/sentry/static/sentry/app/components/gridResizable/styles.tsx
> +  cursor: grab;
```suggestion
  cursor: grab;
  user-select: none;
```

when the user drags on these draggable handles, we prefer nothing is selected (e.g. no text selection)

2019-09-19 18:21 UTC, markstory commented on src/sentry/static/sentry/app/views/eventsV2/table.tsx
> +    eventView: EventView.fromLocation(this.props.location),
Could the eventView be passed as props from the containing component in index.tsx?

2019-09-19 18:21 UTC, markstory commented on src/sentry/static/sentry/app/views/eventsV2/table.tsx
>      if (this.props.location !== prevProps.location) {
This could be an eventView method that compares with the last view. That would let us only refetch when columns or condition related values change.

2019-09-20 07:51 UTC, leedongwei commented
Closing to move review into #14790 and #14791

2019-09-20 07:51 UTC, closed without merging