ref(ts): Convert AssigneeSelector
getsentry/sentry pull request #14919
Opened 2019-10-02 23:32 UTC by leedongwei

2019-10-02 23:37 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/components/assigneeSelector.tsx
> +  memberList: SentryTypes.Member[];
Is this right? don't we import our types from `app/types`?

2019-10-03 03:28 UTC, dashed requested changes

2019-10-03 03:28 UTC, dashed commented on src/sentry/static/sentry/app/components/assigneeSelector.tsx
> +  px?: number;
@leedongwei this `px` prop seems like it's used at all; and we can safely remove it .

2019-10-06 17:17 UTC, dashed approved these changes
Looks like TypeScript to me 👍

2019-10-06 20:25 UTC, merged