feat: Add a bind_cached_fk to the BaseModel
getsentry/sentry pull request #14937
Opened 2019-10-03 20:11 UTC by mattrobenolt

Model.bind_cached_fk provides a way that we can freely assure that
traversing a foreign key relationship is done in the most efficient way
possible.

* If the relationship has already been bound, it does nothing.
* If not bound, it checks if the model can be fetched using
get_from_cache.
* Falls back to a normal get and query from the database.

This pattern allows things such as:

group.bind_cached_fk('project').project

And make sure this is done the best we can.

2019-10-03 23:57 UTC, tkaemming requested changes
Seems like it shouldn't be hard to wire up at least a trivial test to this to ensure there's _some_ coverage.

2019-10-03 23:57 UTC, tkaemming commented on src/sentry/db/models/base.py
> +    def bind_cached_fk(self, *rels):
Why isn't `rels` just a list? Passing it as a variadic makes easier to accidentally turn it into a noop by not passing any arguments, and limits the potential for adding more arguments in the future that don't have to be plucked out of `**kwargs`.

2020-10-28 20:41 UTC, BYK commented
Closing due to staleness.

2020-10-28 20:41 UTC, closed without merging

2020-10-28 21:36 UTC, mattrobenolt commented
RIP, this was a nice idea.