WIP
getsentry/sentry pull request #14960
Opened 2019-10-07 17:34 UTC by billyvg

2019-10-08 02:59 UTC, eurica commented
Cool! So nice to see this.  Are those lines in profiler.jsx something every developer would have to write or just because of something specific we're doing?

2019-10-08 13:21 UTC, kamilogorek requested changes

2019-10-08 13:21 UTC, kamilogorek commented on src/sentry/static/sentry/app/api.tsx
> +          (requestSpan as any).finish();
For now we can use:
```js
(requestSpan as Sentry.Span).finish();
```

2019-10-08 13:21 UTC, kamilogorek commented on src/sentry/static/sentry/app/utils/apm.jsx
> +export function finishTransaction(delay) {
This method should probably also reset `interruptFlush` value

2019-10-08 18:44 UTC, billyvg commented on src/sentry/static/sentry/app/utils/apm.jsx
> +  if (flushTransactionTimeout) {
Refactored these a bit

2019-10-08 18:45 UTC, billyvg commented on src/sentry/static/sentry/app/api.tsx
> +          (requestSpan as any).finish();
Moved to where we start the span

2019-10-08 18:53 UTC, billyvg commented
> Cool! So nice to see this. Are those lines in profiler.jsx something every developer would have to write or just because of something specific we're doing?

This is not necessarily a representation of what our SDK will be like for our clients.

2019-10-10 13:44 UTC, kamilogorek approved these changes

2019-10-11 00:19 UTC, merged