py3(pytest): bump pytest and friends to last 2.7 supported versions
getsentry/sentry pull request #14997
Opened 2019-10-08 21:05 UTC by joshuarli

This bumps the following in preparation for python3:

- pytest to 4.6.5 (2.7 LTS and last compatible version)
- pytest-html to 1.22.0 (last 2.7 compatible version)
- pytest-django to 3.5.1 (latest version, still compat with pytest 4.x)

I also moved "tests requirements" to dev, since they're pretty much redundant.

TODO: rebase this on 3.4.x.
TODO: this has to be mirrored over to getsentry + sentry-plugins.

2019-10-08 23:05 UTC, wedamija approved these changes

2019-10-08 23:06 UTC, wedamija requested changes
Actually, are you sure those `make_stacktrace_snapshot` calls are doing anything now? I think they're just going to return the inner function

2019-10-08 23:16 UTC, joshuarli commented
> Actually, are you sure those `make_stacktrace_snapshot` calls are doing anything now? I think they're just going to return the inner function

_facepalm_ you're right, lol

2019-10-08 23:24 UTC, joshuarli commented
> Actually, are you sure those `make_stacktrace_snapshot` calls are doing anything now? I think they're just going to return the inner function

Good catch, gimme a sec to understand what's really going on here. Now that I remember, the branch it was cherry picked from, I didn't know what I was doing, haha.

2019-10-09 17:58 UTC, joshuarli commented
Hmm, I can't remember why I changed all of it back then. If I revert it, pytest only complains about `test_get_stacktrace_with_only_filename`:

```
Fixture "make_stacktrace_snapshot" called directly.
```

2019-10-09 18:06 UTC, joshuarli commented
Right, so I don't really know why `make_stacktrace_snapshot` was previously not being passed to that one test. Fixing that results in

```
AssertionError: assert '' == 'errors: null\nget_stacktrac..."foo\\"\\n  File \\"bar\\""'
  + errors: null
  + get_stacktrace: "Stacktrace (most recent call last):\
  + \
  +   File \\"foo\\"\
  +   File \\"\\
  +   bar\\""
  + to_json:
  +   frames:
  +   - abs_path: foo
  +     filename: foo
  +   - abs_path: bar
  +     filename: bar
  + to_string: "Stacktrace (most recent call last):\
  + \
  +   File \\"foo\\"\
  +   File \\"bar\\""
```

And after following some indirection, I realize there isn't a `tests/sentry/event_manager/interfaces/snapshots/test_stacktrace/test_get_stacktrace_with_only_filename.pysnap` file.

2019-10-09 18:11 UTC, joshuarli commented
@untitaker how does c2f346fe4442ea782b8b4cf2e8c9fb719d233131 look to you?

2019-10-09 18:15 UTC, untitaker approved these changes
damn, we didn't have that safeguard of pytest?

2019-10-09 18:18 UTC, wedamija approved these changes

2019-10-09 18:21 UTC, joshuarli commented
> damn, we didn't have that safeguard of pytest?

Not in 3.x it seems.

2019-10-09 18:35 UTC, merged