ref(eventstore): Allow passing a dataset to Eventstore functions
getsentry/sentry pull request #15118
Opened 2019-10-16 20:35 UTC by lynnagara

Adds a `dataset` parameter to all eventstore functions, that supports
passing a dataset to be searched.

In many cases we already know which dataset we want to search (apart
from Discover v2 this is always Events). This avoids unnecessarily
running the detect_dataset function and possibly making an incorrect
decision in these scenarios.

2019-10-17 16:13 UTC, markstory commented on src/sentry/api/endpoints/organization_event_details.py
> +            event, filter=self._get_filter(snuba_args), dataset=dataset
Should the `dataset` be part of the `filter` object? That could help consolidate some parameters and co-locate the dataset choice with the conditions.

2019-10-17 21:47 UTC, fpacifici commented
Could you please provide some additional context about cases where detect_dataset would yield the wrong result ?
One of the goals of eventstore is to have a unified abstraction around the way we fetch events. Originally this was to hide differences between Snuba/Postgres/Nodestore. Now we have different sources within snuba events/transaction. 
Leaking the decision around the snuba dataset seems going against the goal of introducing the eventstore abstraction, since we would be spreading the dataset decision logic around the code base instead of keeping it hidden within the data fetching api.
This would increase the complexity of the product when fetching events and make eventstore less useful. Plus it would make it harder to move this logic entirely into Snuba.

2019-10-17 21:47 UTC, fpacifici requested changes
See the comment above regarding leaking the dataset outside eventstore.

2019-10-17 23:57 UTC, lynnagara commented
The wrong / ambiguous case I was thinking of where a user might have a custom tag "duration" on an error and we would interpret it as a transaction even if they were looking for an error.
Honestly, this might be unlikely though. The main motivation for this is to limit the search space of certain queries.

For `get_event_by_id`, in the majority of cases (anything outside Discover 2 right now) we know that we are only searching for a matching non transaction event. However since get_event_by_id doesn't know this, we will end up searching both tables unnecessarily for a match (in the future where we do not dual write transactions).

For `get_events`, since we accept a list of conditions via filter, we could probably force a correct decision by adding a condition "type != transaction" everywhere where this gets called outside Discover and have Snuba / eventstore / whatever later analyse those conditions to make the right decision (this seems not dissimilar to being aware of datasets though).

The decision about a dataset isn't currently unique to eventstore. Since dataset_query / raw_query are being passed the dataset, we already have code unrelated to eventstore (doing aggregations) that is dataset aware.

Although the user facing data model of events for Discover is a gigantic joined table of events and transactions, I'm not sure that's the model we want to expose to Sentry generally.

2019-10-18 02:29 UTC, lynnagara commented
Thinking about this some more, I do think it's worthwhile giving Sentry control of the dataset.

We can have 3 datasets available to Sentry:
- Events
- Transactions
- JoinedEventsAndTransactions

Events is what's used pretty much everywhere right now. Transactions is only used by Discover2, which currently switches between Events and Transactions (depending on we get from detect_dataset). The 3rd one is not available yet, but all Discover2 queries will use this in future.

Once the 3rd dataset becomes available we can delete all the dataset detection logic that flips between events/transactions and start querying the joined dataset instead.

2019-10-18 18:56 UTC, fpacifici commented
I don't think I agree with this still. Let me break the reasoning down.
These are the downsides of exposing the dataset concept outside of eventstore
1) Spread around the product codebase a decision that we are trying to make transparent. This will make it much harder to move it back into eventstore/snuba because the logic will be scattered around the code base and we will have to honor that parameter when the product won't really care in order to function properly. Since moving responsibilities towards eventstore and then snuba is something we are already actively doing, letting the product take this decision would push us in the opposite direction.
2) There is already a way, in the product scope, to drive our decision for the dataset in an optimized way. This is, as you mentioned, passing a `type=XXX` filter. This condition will always be conceptually valid no matter how we reorganize datasets, while an explicit dataset parameter would require us to make changes to the product at every change we do in the dataset structure and logic. 
3) API Inconsistency. If we transparently make eventstore read from other sources other than snuba (like cache or nodestore) we would be passing in a parameter that should drive an internal implementation choice that will be ignored. This is a confusing behavior for an api since it behaves differently from what the user would expect
4) API complexity. This doubles the degrees of freedom the api has to take into account, since the callsites now are not only able to filter the event but, for each filter they provide us they can tell us where to go to pick data. This adds another dimension to the behaviors we have to specify.
5) Introducing this now for the sake of a data model where we will not have transactions in the event table is premature optimization. We do not know yet exactly how the data model will look like then, we may have a matview that keeps the minimum set of common columns, thus that dataset decision will be useless. If it turns out we will need the user to specify where to take data from we will be able to introduce this parameter then, without tying our hands now, since this is not a problem right now.

So in practice, why not just use the `type` parameter to decide and add this parameter where you do not need transactions (which basically means the same place where you would have passed the dataset)? This is more future proof specifically now that we are going to make a lot of changes to which datasets are available.

More remarks:
_The decision about a dataset isn't currently unique to eventstore. Since dataset_query / raw_query are being passed the dataset, we already have code unrelated to eventstore (doing aggregations) that is dataset aware._
That is true, but the reason is that there is no eventstore like abstraction there. The Snuba api should be revisited. And that dataset choice logic is temporary. The Snuba raw_query is a lower level api than eventstore, like sending SQL statements to a DB (raw_query) vs using the Django ORM (eventstore). So it is meaningful that dataset is exposed there and it is not  in eventstore

_Although the user facing data model of events for Discover is a gigantic joined table of events and transactions, I'm not sure that's the model we want to expose to Sentry generally._
We aren't in general (think about outcomes, they are unrelated). But since we are moving on a direciton where a lot of the product works on this generic concept of event independently whether this is a transaction or an error, spreading the responsibility of picking a the right storage for different event types seems against the goal.

2019-10-18 18:56 UTC, markstory commented on src/sentry/api/endpoints/organization_event_details.py
> +        dataset = snuba.detect_dataset(snuba_args, aliased_conditions=True)
I'm planning on moving/removing the need to pass `aliased_conditions` in an effort to reduce the number of places/layers we convert from a 'public' field name to the internal ones. Right now that happens in `api.event_search` for conditions and in `snuba.transform_aliases_and_query()`, `snuba.dataset_query()` and `eventstore` methods for selected fields, order and group by.

2019-10-24 18:00 UTC, lynnagara commented
So as discussed offline, we will pass the decision via conditions on the type rather than add new syntax. If we need some optimization around get_events_by_id we will handle it later.

2019-10-24 18:00 UTC, closed without merging