meta(typo): Fix multiple typos
getsentry/sentry pull request #15197
Opened 2019-10-21 19:05 UTC by billyvg

This is a continuation of @minho42 work on https://github.com/getsentry/sentry/pull/14615, rebased on top of our latest master and resolved the merge conflicts.

2019-10-21 19:06 UTC, billyvg commented
IDK if there's an easier way for me to help resolve the conflicts in https://github.com/getsentry/sentry/pull/14615

2019-10-21 19:11 UTC, dashed requested changes

2019-10-21 19:11 UTC, dashed commented on src/sentry/db/models/query.py
> +    """Operator to test if any of the given values are (case-insensitively)
```suggestion
    """Operator to test if any of the given values are (case-insensitive)
```

2019-10-21 19:11 UTC, dashed commented on src/sentry/db/models/query.py
> +    """Operator to test if any of the given values are (case-insensitively)
```suggestion
    """Operator to test if any of the given values are (case-insensitive)
```

2019-10-21 19:16 UTC, EvanPurkhiser commented on src/sentry/db/models/query.py
> +    """Operator to test if any of the given values are (case-insensitively)
I think this is fine as it is.

2019-10-21 19:16 UTC, EvanPurkhiser commented on src/sentry/db/models/query.py
> +    """Operator to test if any of the given values are (case-insensitively)
🤷‍♂

2019-10-21 19:17 UTC, dashed commented on src/sentry/db/models/query.py
> +    """Operator to test if any of the given values are (case-insensitively)
🤔

2019-10-21 21:21 UTC, dashed approved these changes
Looks good to me 👍 

Took me a while to look thru them all 😄

2019-10-21 21:27 UTC, tkaemming approved these changes
🙃

2019-10-21 21:32 UTC, merged

2019-10-21 21:38 UTC, joshuarli commented
Thanks so much @minho42! Also billy.

2019-10-22 06:27 UTC, minho42 commented
@billyvg Thank you!