feat(discoverv2): removing issue from tab and updating order of issue in sidebar
getsentry/sentry pull request #15834
Opened 2019-11-26 19:17 UTC by doralchan

![Screen Shot 2019-11-26 at 11 17 02 AM](https://user-images.githubusercontent.com/4830259/69664993-4af7ec00-103e-11ea-9e49-53e6dad90e53.png)

2019-11-26 21:57 UTC, markstory approved these changes

2019-11-26 22:46 UTC, dashed requested changes

2019-11-26 22:46 UTC, dashed commented on src/sentry/static/sentry/app/views/eventsV2/eventDetails/content.tsx
> +      <StyledTitle>{title}:</StyledTitle>
@doralchan `<StyledTitle />` should also be `gray2` as per Cramer's feedback.

2019-11-26 23:08 UTC, doralchan commented
I did change that! 

<img width="756" alt="Screen Shot 2019-11-26 at 3 07 45 PM" src="https://user-images.githubusercontent.com/4830259/69680019-899d9e80-105e-11ea-8ddc-19c496996e9c.png">

2019-11-27 00:17 UTC, dashed approved these changes
Looks good to me 👍

2019-11-27 00:18 UTC, dashed commented on src/sentry/static/sentry/app/views/eventsV2/eventDetails/content.tsx
> +      <StyledTitle>{title}:</StyledTitle>
Oh oops. looks like it was addressed in this PR now.

2019-11-27 00:58 UTC, merged