Update broken loader link
getsentry/sentry pull request #15987
Opened 2019-12-06 19:40 UTC by ceorourke

Currently in the product it goes here: https://docs.sentry.io/platforms/javascript/browser/ which 404s

I _think_ it's supposed to go here https://docs.sentry.io/platforms/javascript/#what-does-the-loader-provide but correct me if I'm wrong

2019-12-06 19:58 UTC, dashed requested changes
nit.

2019-12-06 19:58 UTC, dashed commented on src/sentry/static/sentry/app/views/settings/project/projectKeys/details/keySettings.tsx
>                        'Copy this script into your website to setup our JavaScript SDK without any additional configuration. [link]',
```suggestion
                      'Copy this script into your website to setup your JavaScript SDK without any additional configuration. [link]',
```

2019-12-06 21:21 UTC, markstory approved these changes

2019-12-07 09:23 UTC, dashed approved these changes

2019-12-09 20:16 UTC, merged