feat(eventstream): Register option to allow eventstream to send event to different topics
getsentry/sentry pull request #16072
Opened 2019-12-12 00:07 UTC by fpacifici

We are going to split transactions from other types of events in eventstore. They will go into two separate topics. This is to reduce the pressure on the event topic itself that kept backlogging on some partitions lately.

2019-12-12 00:12 UTC, mattrobenolt requested changes

2019-12-12 00:12 UTC, mattrobenolt commented on src/sentry/options/defaults.py
> +register("store.eventstream-per-type-topic", default=False)
Add `flags=FLAG_PRIORITIZE_DISK`.

(We frankly should have this on most if not all of these, I'm not sure why people stopped.)

2019-12-17 19:33 UTC, tkaemming approved these changes
Seems fine to me, you still need that ✅ from @mattrobenolt though.

2019-12-17 19:35 UTC, mattrobenolt approved these changes

2020-01-02 23:12 UTC, merged