fix(workflow): Fix permissions for editing Metric Alert Rules
getsentry/sentry pull request #16460
Opened 2020-01-15 02:41 UTC by billyvg

The UI was never updated to use the "project" scoped endpoint for metric alert rules. The UI also locked the form to require `org:write` access, instead of `project:write`.

Needs https://github.com/getsentry/sentry/pull/16408 and https://github.com/getsentry/sentry/pull/16151

2020-01-15 02:46 UTC, iProgramStuff reviewed
This needs to come with backend changes I think. The project scoped API probably isn't using the new combined rule serializer.

Did you see that when you were developing this?

2020-01-15 16:45 UTC, billyvg commented
@iProgramStuff yeah I was gonna wait for your PR to be merged first

2020-01-23 17:28 UTC, iProgramStuff requested changes

2020-01-23 17:28 UTC, iProgramStuff commented on src/sentry/incidents/endpoints/project_alert_rule_index.py
> +from sentry.incidents.endpoints.serializers import UnifiedAlertRuleSerializer
This refactor (https://github.com/getsentry/sentry/pull/16546) removes the UnifiedAlertRuleSerializer

2020-01-23 17:28 UTC, iProgramStuff commented on src/sentry/incidents/endpoints/project_alert_rule_index.py
> +from sentry.incidents.endpoints.serializers import UnifiedAlertRuleSerializer
once it's merged, we can leave this as-is (using AlertRuleSerializer)

2020-01-23 21:31 UTC, iProgramStuff approved these changes

2020-01-23 21:38 UTC, merged