feat(lint): Update prettier
getsentry/sentry pull request #16505
Opened 2020-01-16 23:04 UTC by jeffkwoh

Required to properly support nullish coalescence operator and optional chaining

2020-01-16 23:06 UTC, billyvg requested changes
Did you run prettier across our codebase?

2020-01-16 23:46 UTC, jeffkwoh commented
@billyvg Thanks for the reminder, done.

2020-01-17 03:43 UTC, billyvg reviewed
Did a quick glance, and it seems like this formatting is a nice improvement.  Anyone in @getsentry/app-frontend have any thoughts?

2020-01-17 03:43 UTC, billyvg commented on src/sentry/static/sentry/app/views/organizationGroupDetails/groupTagValues.jsx
> -            href={`/${orgId}/${group.project.slug}/issues/${group.id}/tags/${
v nice

2020-01-17 15:17 UTC, markstory reviewed
@billyvg Generally looks good to me. The template string changes are 😍 . I was not a fan of all the line breaks that prettier added before.

2020-01-17 18:22 UTC, billyvg approved these changes

2020-01-17 19:14 UTC, merged