feat(workflow): Fix "View in Discover" query
getsentry/sentry pull request #16867
Opened 2020-02-07 00:52 UTC by billyvg

Changes columns to be issue.id, count(id), count_unique(user.id) and fixes sorting

2020-02-07 00:56 UTC, dashed approved these changes
Looks good to me 👍

2020-02-07 01:50 UTC, adhiraj commented
👍

2020-02-07 02:19 UTC, adhiraj requested changes
Actually can you change the time period to match the period in the alert details graph?

2020-02-07 14:31 UTC, markstory commented on src/sentry/static/sentry/app/views/alerts/details/body.tsx
> +      fields: ['issue.id', 'count(id)', 'count_unique(user.id)'],
You can use the `issue` field now to get a shortid link instead of the autoincement.

2020-02-07 19:16 UTC, markstory approved these changes

2020-02-10 20:27 UTC, adhiraj approved these changes

2020-02-11 00:23 UTC, merged