fix(issues): Improve UX when highlighting Group title
getsentry/sentry pull request #17042
Opened 2020-02-14 01:11 UTC by leedongwei

Took the fastest way out to fix this UX issue.

![textselection](https://user-images.githubusercontent.com/1748388/74492026-56f78b00-4e82-11ea-992b-b19cbca41bfe.gif)

2020-02-14 03:44 UTC, dashed requested changes

2020-02-14 03:44 UTC, dashed commented on src/sentry/static/sentry/app/components/eventOrGroupTitle.tsx
> +        <em title={subtitle}>{'asdfasdfa/asdfasdf.asdfadsf' || subtitle}</em>
```suggestion
        <em title={subtitle}>{subtitle}</em>
```

2020-02-14 14:42 UTC, markstory commented on src/sentry/static/sentry/app/components/eventOrGroupTitle.tsx
> +      | 'transaction';
Should this union be in app/types? It feels like something that will be used in more than one place and could be part of the event type too.

2020-02-14 18:13 UTC, leedongwei commented on src/sentry/static/sentry/app/components/eventOrGroupTitle.tsx
> +        <em title={subtitle}>{'asdfasdfa/asdfasdf.asdfadsf' || subtitle}</em>
Lol omg.

2020-02-14 18:48 UTC, leedongwei commented
Latest commit is dependent on the correct types from #17058

2020-02-14 21:38 UTC, markstory approved these changes

2020-02-14 22:38 UTC, dashed approved these changes
Looks good to me 👍

2020-02-18 22:46 UTC, leedongwei commented
Had a long weekend. Rebased on `master` and running tests again.

2020-02-18 23:14 UTC, leedongwei commented
1c63f7a updates acceptance test snapshops.

2020-02-18 23:47 UTC, leedongwei commented
@markstory @dashed @doralchan @billyvg

FYI: This commit has a layout change on mobile width: the subtitle will be moved into a new-line, underneath title. Titles/subtitles that are longer than the page width will be truncated with ellipsis. Please take a look at Percy's diffs.

Not sure who owns the Event/Group page, so I want to make sure y'all are aware and get your buy-in before I merge this.

2020-02-19 01:11 UTC, billyvg commented
I would say @matejminar and @priscilawebdev probably owns these views now? It lgtm, seems more readable this way on mobile.

2020-02-19 07:36 UTC, priscilawebdev approved these changes
It looks good to me 👍

2020-02-19 07:41 UTC, priscilawebdev commented
Talking about Percy's snapshots, I would say that the changes made seem to me much better now than before 😉

2020-02-19 09:03 UTC, matejminar approved these changes
Looks good to me, thanks.

2020-02-19 18:35 UTC, merged