chore(snuba) - Matching snuba's internal query limit
getsentry/sentry pull request #17146
Opened 2020-02-19 21:58 UTC by wmak

- This matches our limits with what snuba has internally
- Also moving this to a constant so if snuba changes the limit, we can
  match it easily

2020-02-19 22:09 UTC, dashed commented
We should let the SNS team sign off on this.

2020-02-19 22:19 UTC, lynnagara commented
This is a product change on the stats and discover endpoints. Do we know who is relying on the larger limits here.

2020-02-19 22:21 UTC, lynnagara commented
The PR description is also misleading since the snuba limit is 10,000 not 1000

2020-02-19 22:24 UTC, wmak commented
@lynnagara Hrm maybe I misunderstood something then. @fpacifici had mentioned to me here: https://www.notion.so/sentry/Q1-Backend-Plan-be735036516542b7a8f271f5073fc973?d=09eed214-e94d-4478-be9e-be3ee79bd20a#258a001a779548e4846097d63e8b3309

That the limit was 1,000.

@bowencai8 If this is done correctly (ie. matching the limit properly which I might not be right now :( ) there shouldn't be any impact to the user.

2020-02-19 22:25 UTC, lynnagara commented
I don't have access to view that doc. Default is 1000, max is 10000 https://github.com/getsentry/snuba/blob/5e5de9e85b68fb931c7e9711db5c873774363dcf/snuba/query/schema.py#L104

2020-02-20 15:49 UTC, dashed commented
What @lynnagara has said seems correct to me.  @fpacifici can you comment?

2020-02-20 19:10 UTC, fpacifici commented
@lynnagara  is right on the number, I was wrong sorry.

Though I don't think it is a good idea to hardcode the maximum snuba limit and use it everywhere, expecially where you do not need it. If youdon't have a specific max size you need, please let Snuba pick the default (which is 1000), for the cases where you specifically need more (like stats) then feel free to use it.
But please avoid defaulting on the maximum when you do not need it, that would jsut be wasting resources.

2020-02-20 19:11 UTC, fpacifici requested changes

2020-02-20 19:11 UTC, fpacifici commented on src/sentry/tagstore/snuba/backend.py
> -            limit=1000,
If this query worked with 1000, please leave it to 1000. if it worked, it means there is no reason for potentially load 10x more data.

2020-02-20 19:12 UTC, wmak commented
Perfect @fpacifici going to close this PR then! Thanks for the info :+1: I wanted to hardcode it for the queries where we were trying to get the maximum (eg. with timeseries)

2020-02-20 19:12 UTC, closed without merging

2020-02-20 19:14 UTC, fpacifici commented
The max you want for a time series depends on the query, not on the fact it is a time series.

2020-02-20 19:19 UTC, dashed commented
@fpacifici would this be easy to determine?

2020-02-20 19:25 UTC, fpacifici commented
Generally it should. That's the number of points you expect to render if it is a time series (you can calculate that from the bucket and start-end timestamp), but that depends on your use case. 
Still I would not overly complicate the solution, it is better using the default if that works for you even if it may load slightly more data than you need, then calculating it wrong. 

My concern was about taking the max and basically making it the new default.

2020-02-20 19:27 UTC, dashed commented
Gotcha. 👍  Thanks for explaining.