fix(workflow): Fixing graph falloff
getsentry/sentry pull request #17436
Opened 2020-03-03 17:25 UTC by iProgramStuff

The alert details page and the rule builder page usually show a massive dropoff on the last point of the graph. This is because that is the current time bucket, and events are still coming in.

This is misleading, and can cause confusion. We no longer render the final data point as a solution to this.

2020-03-03 18:45 UTC, billyvg commented on src/sentry/static/sentry/app/views/alerts/details/chart.tsx
> +            dataArray: chartData.splice(-1, 1),
You probably want slice, which returns a new array where as splice alters the array in place and returns an array of the deleted items

```suggestion
            dataArray: chartData.slice(0, -1),
```

2020-03-04 17:27 UTC, markstory approved these changes

2020-03-04 17:41 UTC, billyvg commented on src/sentry/static/sentry/app/views/alerts/details/chart.tsx
> +            dataArray: chartData?.slice(-1, 1),
I think you want `slice(0, -1)`

2020-03-04 17:41 UTC, billyvg requested changes
I don't think the args to `slice()` are correct

2020-03-04 17:53 UTC, billyvg approved these changes

2020-03-04 18:20 UTC, merged