perf(subscriptions): Add script for load testing snuba subscriptions
getsentry/sentry pull request #17451
Opened 2020-03-04 00:16 UTC by wedamija

This script allows us to bulk create subscriptions in snuba. It creates them with random
permutations of various parameters.  We could potentially add some more items to `queries` to get
some queries with more terms going.

We create all the subscriptions with a fake type. This means that the `QuerySubscriptionConsumer`
will receive the updates, load the `QuerySubscription`, find no handler and just exit. So we're only
testing load on the Snuba/Clickhouse side for now.

Right now this is just on Sentry, but we can adapt it to add subscriptions to other random projects
too. These will have no effect on anything, so it's safe to do so.

When we're finished with the load test, or if we just need to stop it, we can run
`delete_fake_subscriptions` and it'll remove all the subscriptions that were created with this
script.

Probably no need to commit this to master.

2020-03-05 20:02 UTC, tkaemming requested changes

2020-03-05 20:02 UTC, tkaemming commented on src/sentry/subscription_test.py
> +            time_window=random.choice(time_windows),
Ideally this number generator would have the option to be easily seeded so that the test is repeatable.

2020-03-05 20:44 UTC, tkaemming approved these changes

2020-03-05 20:44 UTC, tkaemming commented on src/sentry/subscription_test.py
> +    project = Project.objects.get(organization_id=organization_id, slug=project_slug)
I think using the organization slug here would probably be a bit more ergonomic.

2020-03-07 01:09 UTC, wedamija commented
Closing and moving to https://github.com/getsentry/getsentry/pull/3643

2020-03-07 01:09 UTC, closed without merging