feat(plugin): Make Mail Plugin non-configurable
getsentry/sentry pull request #17842
Opened 2020-03-24 00:07 UTC by jeffkwoh

2020-03-25 01:24 UTC, wedamija reviewed
LGTM pending the flag changes

2020-03-25 21:15 UTC, scefali requested changes

2020-03-25 21:15 UTC, scefali commented on src/sentry/plugins/base/manager.py
>              if not safe_execute(plugin.can_configure_for_project, project, _with_transaction=False):
@jeffkwoh The right way to do this is by adding a `can_configure_for_project` method to `MailPlugin` which will handle the logic you want to add.

2020-03-30 20:46 UTC, wedamija approved these changes

2020-03-31 16:50 UTC, scefali approved these changes

2020-03-31 17:00 UTC, merged