feat(async-csv): Add beta-tag to export all button
getsentry/sentry pull request #18089
Opened 2020-04-03 20:37 UTC by leeandher

Before we enable the feature for GA or anything like that, we want to add a beta tag to let people know unexpected errors will be looked at. 👌

Image:

![image](https://user-images.githubusercontent.com/35509934/78402919-73ce5600-75c9-11ea-9e25-9e7c924d3567.png)

2020-04-03 20:39 UTC, leeandher commented on tests/js/spec/components/dataExport.spec.jsx
> +    expect(wrapper.text()).toContain('Export All to CSV');
Changing these from `toBe` to `toContain` seemed to make more sense than verifying `Export All to CSVbeta` was the return value.

2020-04-03 20:39 UTC, dashed requested changes
I dont think the beta tag label should be placed like that.

2020-04-03 20:39 UTC, leeandher commented on src/sentry/static/sentry/app/components/dataExport.tsx
> +    </span>
I'm not the sure this is the most 'proper' way to position the beta tag with CSS but let me know if I should change it.

2020-04-03 20:44 UTC, leeandher commented
@dashed @doralchan By default I could just drop it inside the button like this: 
![image](https://user-images.githubusercontent.com/35509934/78403392-48983680-75ca-11ea-989a-cf134cf2c944.png)

I'll have to play with the sizing or the other button to get them to match, but what about this look?

2020-04-03 22:58 UTC, doralchan commented
This is the first time I'm seeing this badge used this way. Was there a designer that worked on this?

2020-04-03 22:59 UTC, doralchan submitted a review, later dismissed
I would avoid putting a badge on a button. It's overkill.

2020-04-03 23:02 UTC, leeandher commented
@doralchan no designer or anything, I was just advised to throw it on there while it could still be buggy for GA

2020-04-06 22:06 UTC, dashed approved these changes
Looks good to me 👍

2020-04-07 18:51 UTC, merged