ref(ui): Social distance saved query search / new query button
getsentry/sentry pull request #18566
Opened 2020-05-01 19:50 UTC by EvanPurkhiser

This should make it much clearer that the button is not just a submit
button for the field

2020-05-01 19:50 UTC, scefali commented
@EvanPurkhiser A screenshot would be nice :)

2020-05-01 19:51 UTC, EvanPurkhiser commented
To be honest I think it doesn't look QUITE as nice since now there's a bit of a gap, but I do think usability wise it is a lot better

2020-05-01 19:59 UTC, doralchan requested changes
Going to design something else - I'd rather not have a primary CTA under a header like this

2020-05-01 22:39 UTC, dashed commented
What does this look like with the banner?

2020-05-15 21:34 UTC, EvanPurkhiser commented
Going to let discover team handle this one

2020-05-15 21:34 UTC, closed without merging