fix(ui): Add new alert status icons
getsentry/sentry pull request #19076
Opened 2020-05-28 23:40 UTC by scttcper

These icons appear in both the new alert header inside a button, and in the alerts list.

before:
![image](https://user-images.githubusercontent.com/1400464/83204150-fc67ff00-a0ff-11ea-8c2f-c204d05450fa.png)

new icons:
![image](https://user-images.githubusercontent.com/1400464/83203968-7b106c80-a0ff-11ea-9675-1ccd1cf4812d.png)

new alerts header:
![image](https://user-images.githubusercontent.com/1400464/83204904-e22f2080-a101-11ea-800f-fe8fcba48265.png)

2020-05-29 19:36 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/views/alerts/status.tsx
> +    <IconCheckmark color="green400" />
😍

2020-05-29 19:37 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/views/alerts/status.tsx
> +  display: grid;
Thanks for using grid. Can you use grid gap to get rid of the margins on the icon?

2020-05-29 19:37 UTC, evanpurkhiser requested changes
Just my comment about grid gap

2020-06-01 22:05 UTC, scttcper commented
Updated the dropdown after the design discussions cc @evanh 

![image](https://user-images.githubusercontent.com/1400464/83459378-19ab0f00-a419-11ea-83de-48333974e59e.png)
Note: this is without the new checkmark icon.

2020-06-09 18:43 UTC, evanpurkhiser approved these changes

2020-06-09 18:55 UTC, merged