ref(config): Rename config to SENTRY_TRUSTED_RELAY_PKS
getsentry/sentry pull request #19240
Opened 2020-06-09 11:14 UTC by jan-auer

2020-06-09 11:28 UTC, jan-auer commented
Ok, `onpremise` needs updating, too.

2020-06-09 14:10 UTC, mitsuhiko approved these changes

2020-06-09 14:17 UTC, BYK requested changes
Let's do something like https://github.com/getsentry/sentry/commit/a48d4c111060071f6a6ff3160695885f7cf922da where we both deprecate this old setting and also move it into `config.yml`.

2020-06-09 14:20 UTC, jan-auer commented
Is there any benefit we get from moving it? There are plenty of other related settings in the python file, such as `SENTRY_RELAY_OPEN_REGISTRATION` which we'd all have to move.

2020-06-09 14:23 UTC, BYK commented
>Is there any benefit we get from moving it?

 - You get automatic backwards compatibility (and the GCB build here would be fixed)
 - Most of the customizable config is already moved to `config.yml` file and although there isn't a concerted effort behind this, we state that `sentry.conf.py` file is mostly deprecated

>There are plenty of other related settings in the python file, such as SENTRY_RELAY_OPEN_REGISTRATION which we'd all have to move.

We can do them one by one (or in this PR, doesn't matter much) under a `relay.*` namespace.

2020-06-09 14:28 UTC, jan-auer commented
> Most of the customizable config is already moved to `config.yml`

I see. In that case, I'll give this a spin later.

> we state that sentry.conf.py file is mostly deprecated

I think we should start adding large comments in `server.py` so that folks don't add more settings to that file. I still see new settings being added every now and then, although it has reduced over the last years.

2020-06-14 20:57 UTC, mitsuhiko commented
This setting was never supposed to be set by non sentry.io installations. We expose this setting on a per-org basis in the org settings to enable external relays.

If we think there is a value to have this config be set by other parties than us I think we can move it, but that was not the original motivation at least.

2020-06-15 07:52 UTC, jan-auer commented
Discussed offline a bit more, and we'll move to `config.yml` since this is required in the onpremise setup flow to get internal Relays working.

2020-10-29 20:12 UTC, BYK commented
Closing due to staleness and conflicts.

2020-10-29 20:12 UTC, closed without merging