feat(ui): Indicate invites sent for approval in invite modal
getsentry/sentry pull request #19370
Opened 2020-06-15 18:29 UTC by slohmes

Updates the invite modal to make it clear to members that their invite has been sent to owners / managers for approval:
* reword subheading text
* add alert box, linking to requests tab
* add extra text to status (bottom left)
* remove the little question mark next to the header
* update "send more..." button text

These changes only show up for members who don’t have invite access. Managers and owners still view the old (current) invite module display.

Part of ENT-216.

2020-06-15 18:39 UTC, slohmes commented
<img width="1792" alt="Screen Shot 2020-06-15 at 11 38 27 AM" src="https://user-images.githubusercontent.com/11082872/84693713-c6e35400-aefc-11ea-98ce-4281f02c10d0.png">

2020-06-15 18:48 UTC, leedongwei approved these changes

2020-06-15 21:32 UTC, EvanPurkhiser commented
IMO this alert box is aggressively big. We need to do spelling about these alert sizes soon

2020-06-15 21:37 UTC, evanpurkhiser requested changes

2020-06-15 21:37 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/components/modals/inviteMembersModal/index.tsx
> +            {tct('Check the status of your pending invite requests in the [link].', {
You can write this as ‘in the [link:Requests tab]’ and then make the link element self closing.

This gives translators better context

2020-06-15 21:37 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/components/modals/inviteMembersModal/index.tsx
> +                '%s invite request to owners and managers for approval',
Is this wording right? Should it be “one invite request sent” ?

2020-10-29 20:17 UTC, BYK commented
We would like to adjust this in single tenant installs.

2020-10-29 20:17 UTC, closed without merging