(fix: API-1175) Reference before assignment
getsentry/sentry pull request #20058
Opened 2020-07-28 01:08 UTC by mgaeta

https://sentry.io/organizations/sentry/issues/1809864258
In the last line of the loop we assign `prev = term` so I'm using that instead.
There may be another bug that's causing `terms` to be empty.

2020-07-28 01:22 UTC, dashed commented
@mgaeta thanks for looking into this! 👍

2020-07-28 14:59 UTC, evanh requested changes
This is a good change. I think there's a deeper issue here as well. This code only gets run if the parser detects some sort of boolean expression, and that should never happen with issues.

2020-07-28 14:59 UTC, evanh commented on src/sentry/api/event_search.py
> +            u"Condition is missing on the right side of '{}' operator".format(prev)
This message won't make sense if `prev` is None. I'm not sure what the error should be in that case.

2020-07-28 15:38 UTC, evanh commented
Also we should add a test for this case.

2020-07-29 01:32 UTC, mgaeta commented
@evanh I can't reproduce this issue because it was fixed by https://github.com/getsentry/sentry/pull/20048. Should I close the PR?

2020-07-29 16:07 UTC, dashed commented
Shouldn't it still be possible to hit this code path?

2020-07-29 17:12 UTC, evanh commented
I think we can close this. Thanks!

2020-07-29 17:26 UTC, closed without merging