ref(py3): Remove invalid http interface query_string_as_bytes tests
getsentry/sentry pull request #20386
Opened 2020-08-25 09:38 UTC by EvanPurkhiser

the python relay library will not handle json encoding byte values. This will just blow up. Remove the test as we should not be passing bytes as the query string.

2020-08-25 09:41 UTC, untitaker approved these changes

2020-08-25 09:42 UTC, untitaker requested changes
Please search for a `.pysnap` file with that test name and remove it as well.

2020-08-25 09:49 UTC, EvanPurkhiser commented
Ah yeah sorry, I shouldn't work so late 🙃

2020-08-26 08:53 UTC, untitaker approved these changes

2020-08-26 23:42 UTC, merged