test(pytest): Refactor test grouping and allow selecting only snuba tests
getsentry/sentry pull request #20915
Opened 2020-09-22 15:50 UTC by billyvg

This refactors test grouping so that we deselect inside of conftest in the
`pytest_collection_modifyitems` hook. Also adds option to only select Snuba
tests.

2020-09-22 17:14 UTC, billyvg commented
Comparing travis builds for this PR: https://travis-ci.org/github/getsentry/sentry/builds/729354847 and a PR on master: https://travis-ci.org/github/getsentry/sentry/builds/729313484 - the tests are grouped correctly.

2020-09-23 23:52 UTC, wedamija approved these changes
Good refactor here, improves the makefile a bunch. Not sure why the mark gets lost with the acceptance tests, although I wonder if it's because the acceptance tests use `.mark` as well.

2020-09-23 23:52 UTC, wedamija commented on src/sentry/utils/pytest/sentry.py
> +        if group_num == current_group:
Nit: Could combine these.

2020-09-24 00:06 UTC, joshuarli commented on src/sentry/utils/pytest/sentry.py
> +        # TODO(joshuarli): six 1.12.0 adds ensure_binary: six.ensure_binary(item.location[0])
```suggestion
```

Feel free to remove this, it's outdated.

2020-09-24 17:46 UTC, joshuarli requested changes
This doesn't work, sorry, should have looked sooner.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/14209781/94180680-e5f36980-fe8d-11ea-88dd-a08472be950f.png">

2020-09-24 17:50 UTC, joshuarli approved these changes

2020-09-24 20:57 UTC, merged