feat(py3): Add python 3 acceptance tests
getsentry/sentry pull request #20950
Opened 2020-09-23 23:42 UTC by wedamija

These should all be passing pretty soon, just adding optional acceptance tests so that we can
require these soon.

2020-09-23 23:42 UTC, wedamija commented on .github/workflows/acceptance.yml
> +
I purposely left off the `Save snapshots` step here, I think that's correct @billyvg?

2020-09-23 23:46 UTC, EvanPurkhiser approved these changes
I looked over it, looks fine to me. If people have more strong feelings feel free to wait for them.

Approving based on the fact that I assume this works.

2020-09-23 23:58 UTC, joshuarli requested changes, later dismissed

2020-09-23 23:58 UTC, joshuarli commented on .github/workflows/acceptance.yml
> +            yarn webpack --display errors-only
This could be omitted if `SENTRY_LIGHT_BUILD` is unset, and any webpacking errors would fail earlier, before devservices.

2020-09-23 23:58 UTC, joshuarli commented on conftest.py
> +    # Modification so that GHA tests run
Reminder to revert after it's working.

2020-09-24 00:02 UTC, joshuarli commented on .github/workflows/acceptance.yml
> +            yarn webpack --display errors-only
Oh, should do that for 2.7 acceptance too. I might have missed that in earlier review, I don't recall.

2020-09-24 00:04 UTC, joshuarli commented on .github/workflows/acceptance.yml
> +            yarn webpack --display errors-only
Original PR https://github.com/getsentry/sentry/pull/18576, looks like I didn't complain about this before.

2020-09-24 00:25 UTC, joshuarli commented on .github/workflows/acceptance.yml
> +            yarn webpack --display errors-only
After some offline discussion, ignore what I said above. It's useful to have yarn webpack explicitly so time can be measured. And also I want to remove SENTRY_LIGHT_BUILD and make it the default in the future.

2020-09-24 01:27 UTC, merged