fix(perf): Change query result function names
getsentry/sentry pull request #20991
Opened 2020-09-25 17:50 UTC by k-fish

### Summary
It came up recently that these function names are unclear. This renames some of the functions in QueryResult to be more accurate and changes their params as well.

2020-09-25 18:49 UTC, Zylphrex requested changes
There's one more in `src/sentry/static/sentry/app/views/performance/transactionSummary/transactionList.tsx`.

2020-10-02 16:16 UTC, Zylphrex reviewed
It seems there's more in `src/sentry/static/sentry/app/views/performance/trends/content.tsx` now.

2020-10-02 19:39 UTC, Zylphrex approved these changes
LGTM

2020-10-05 15:13 UTC, dashed approved these changes

2020-10-05 16:07 UTC, merged