ref(apidocs-testing): Releases Endpoint Testing
getsentry/sentry pull request #21035
Opened 2020-09-29 00:10 UTC by MeredithAnya

**Context:**
Now that the schema for the documented API endpoints is in Sentry, we have been writing tests to make sure that if an endpoint is changed, we can catch if the change would violate the schema we have in place. This makes sure that there are not accidental breaking changes to these document endpoints that would affect the developers who build on top of them. 

**Release Endpoints**
The latest and greatest in the batches of tests, this PR covers the tests for the endpoints in the "Releases" section of the API docs. 

Some things to take note of:
* The tests found that some status codes were wrong (`201` instead of `200`).
* Reference objects (`$ref`) do not seem to work with `"nullable": true`, there is a [whole discussion](https://github.com/OAI/OpenAPI-Specification/issues/1368) about it but even with some of the suggestions I couldn't get the openapi-core validator to work correctly. Further research required, but for now I've added the whole `Deploy` object instead of referencing it.
* Not adding `delete` paths since we don't get a response payload back.

2020-09-29 17:27 UTC, ceorourke requested changes
Overall looks good, the fixtures are optional but I think the 2 `pass` statements left in need to be changed.

2020-09-29 17:27 UTC, ceorourke commented on tests/apidocs/endpoints/releases/test_organization_release_details.py
> +        org.flags.allow_joinleave = False
what is this part for?

2020-09-29 17:27 UTC, ceorourke commented on tests/apidocs/endpoints/releases/test_organization_release_details.py
> +        pass
why is there a `pass` here?

2020-09-29 17:27 UTC, ceorourke commented on tests/apidocs/endpoints/releases/test_organization_release_file_details.py
> +        releasefile = ReleaseFile.objects.create(
you can use the `create_release_file` fixture here too

2020-09-29 17:27 UTC, ceorourke commented on tests/apidocs/endpoints/releases/test_organization_releases.py
> +        pass
there's a `pass` here too

2020-09-29 17:27 UTC, ceorourke commented on tests/apidocs/endpoints/releases/test_project_issues_solved_in_release.py
> +        repo = Repository.objects.create(organization_id=self.org.id, name=self.project.name)
can use `create_repo` here

2020-09-29 17:50 UTC, MeredithAnya commented on tests/apidocs/endpoints/releases/test_organization_release_details.py
> +        pass
leftover oopsie :)

2020-09-29 17:51 UTC, MeredithAnya commented
> Overall looks good, the fixtures are optional but I think the 2 `pass` statements left in need to be removed.

The fixtures is a good call cause if tables change I'm going assume the fixtures will be updated.

2020-09-29 17:51 UTC, ceorourke approved these changes
👍

2020-09-30 21:37 UTC, MeredithAnya commented
@ceorourke I'm adding this comment more as taking note, but I didn't use the `create_commit` factory because I ran into some problems with it auto creating the commit release files. Probs doing something wrong but might follow up later with those changes

2020-10-01 16:33 UTC, merged