feat/allow-measurements-in-pxx-functions
getsentry/sentry pull request #21230
Opened 2020-10-08 18:01 UTC by Zylphrex

The predefined Pxx functions is currently hard coded for transaction.duration
but there is no reason why it can't work for any numeric column. This change
adds support for any numeric column in these predefined Pxx functions while
leaving the default as transaction.duration for backwards compatibility.

2020-10-08 18:37 UTC, dashed approved these changes

2020-10-08 22:50 UTC, wmak requested changes
I think this breaks when you try `p75(measurements.lcp)` cause of `validate_argument_count` not taking the default into the total number of arguments

Can you add some tests for this too?

2020-10-09 00:08 UTC, Zylphrex commented
> I think this breaks when you try `p75(measurements.lcp)` cause of `validate_argument_count` not taking the default into the total number of arguments
> 
> Can you add some tests for this too?

No sure what you mean by `p75(measurements.lcp)` breaking as `validate_argument_count` does check against the total number of arguments, but I added some tests for it.

2020-10-09 00:17 UTC, wmak approved these changes
🤔 not... sure why this was failing when I tested it, nevermind looks good now

2020-10-09 01:26 UTC, markstory commented on src/sentry/api/event_search.py
> +            optional_args=[with_default("transaction.duration")(NumericColumnNoLookup("column"))],
I like the with_default() function but think the currying is a bit elaborate. Wouldn't `with_default('transaction.duration', NumericColumnNoLookup('column'))` work just as well?

2020-10-09 14:48 UTC, markstory approved these changes

2020-10-09 15:14 UTC, merged