ref(stats): Link to project issues, not settings
getsentry/sentry pull request #21703
Opened 2020-10-30 22:41 UTC by EvanPurkhiser

Fixes https://github.com/getsentry/sentry/issues/15431

2020-10-30 22:43 UTC, billyvg approved these changes

2020-10-30 22:44 UTC, billyvg requested changes, later dismissed

2020-10-30 22:44 UTC, billyvg commented on src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx
> +      const projectLink = `/organizations/${organization.slug}/issues/?project_id=${project.id}`;
Wait this should be 
```suggestion
      const projectLink = `/organizations/${organization.slug}/issues/?project=${project.id}`;
```

2020-11-17 08:38 UTC, matejminar approved these changes

2020-11-17 10:22 UTC, EvanPurkhiser commented on src/sentry/static/sentry/app/views/organizationStats/projectTable.tsx
> +      const projectLink = `/organizations/${organization.slug}/issues/?project_id=${project.id}`;
oh wait maybe I didn't commit this hmm

2020-11-17 22:06 UTC, merged