ref(Datetime): Update clock24Hours format
getsentry/sentry pull request #21717
Opened 2020-11-01 15:35 UTC by priscilawebdev

2020-11-02 10:45 UTC, matejminar approved these changes

2020-11-02 17:48 UTC, billyvg approved these changes

2020-11-03 08:50 UTC, matejminar requested changes
I just realized, that this still won't be consistent with the default `lll` format.
There will be a difference in `Nov 03` vs `Nov 3`

2020-11-03 09:02 UTC, priscilawebdev commented
Good catch @matejminar ... I've updated the code 😉

2020-11-03 09:08 UTC, matejminar approved these changes

2020-11-03 10:01 UTC, merged