build(gha): Add plugins test suite
getsentry/sentry pull request #21825
Opened 2020-11-05 18:48 UTC by billyvg

This was a test suite I missed when moving things over.

2020-11-05 22:39 UTC, joshuarli requested changes
You missed `if: steps.changes.outputs.backend == 'true'` for setup-python.

But, there are also acceptance tests with snapshots for plugins. Could we move that to the acceptance job? Then we can remove the JS steps too. Is that viable?

2020-11-05 23:19 UTC, joshuarli commented on Makefile
> -	@echo "--> Building static assets"
Good job on being thorough here, I would have missed this.

2020-11-05 23:21 UTC, joshuarli approved these changes

2020-11-06 00:27 UTC, scefali approved these changes
LGTM

2020-11-06 00:32 UTC, merged