test(symbolicator): Update snapshots
getsentry/sentry pull request #22395
Opened 2020-12-02 14:35 UTC by flub

Symbolicator snapshots need updating for the new download info
available from https://github.com/getsentry/symbolicator/pull/309.

2020-12-14 08:47 UTC, jan-auer approved these changes

2020-12-14 08:47 UTC, jan-auer commented on tests/symbolicator/snapshots/SymbolicatorMinidumpIntegrationTest/test_reprocessing_reprocessed.pysnap
> +      location: '4'
Are these db ids stable? If not, please remove or mask them before passing them into the snapshot.

2020-12-14 09:06 UTC, jan-auer requested changes
Retracting my approval. 

- Snapshots are not being tested by CI currently due to a wrong condition.
- Symbolicator has candidates disabled in its config, so this would not pass.

2020-12-15 13:21 UTC, flub commented
With most recent changes to getsentry/symbolicator#309 this isn't needed anymore.

2020-12-17 08:07 UTC, closed without merging