ref(modals): Use openModal for SentryAppExternalIssueActions
getsentry/sentry pull request #22593
Opened 2020-12-10 11:22 UTC by EvanPurkhiser

2020-12-10 17:00 UTC, scefali requested changes
Tested this out and it looks like there's a bug the doesn't open up the modal the first time you click it

2020-12-10 19:44 UTC, EvanPurkhiser commented
Sounds right, looks like tests are failing too, so I'll take a closer look.

Just blasted a lot of these out so doesn't surprise me it's not quite right.

2020-12-11 08:28 UTC, EvanPurkhiser commented
Verified this works.

2020-12-14 20:45 UTC, scefali approved these changes

2020-12-14 20:45 UTC, merged