fix(discover): Handle has filters on array fields
getsentry/sentry pull request #22813
Opened 2020-12-18 23:49 UTC by wmak

- Array fields were being treated as strings, which meant that the
  conditions we were building were incorrect, this uses the notEmpty
  function to check if the array instead.

2021-01-04 15:08 UTC, markstory commented on src/sentry/api/event_search.py
> +    "stack.stack_level",
Should `error.type`, `error.value`, `error.mechanism` also be in this list?

2021-01-04 20:21 UTC, markstory approved these changes

2021-01-04 20:29 UTC, dashed requested changes

2021-01-04 20:29 UTC, dashed commented on tests/sentry/api/test_event_search.py
> +        _filter.conditions == [
@wmak you're missing `assert` here

2021-01-06 15:28 UTC, wmak commented on tests/sentry/api/test_event_search.py
> +        _filter.conditions == [
Dang great catch, ty

2021-01-07 17:11 UTC, dashed approved these changes

2021-01-08 21:46 UTC, merged