feat(workflow): Add index to GroupInbox date added
getsentry/sentry pull request #22931
Opened 2021-01-05 22:27 UTC by scttcper

Related to #22908

2021-01-05 22:39 UTC, mattrobenolt requested changes
This index needs to be made concurrently otherwise it'll take us down.

And since it's so large, let's also flag this as `is_dangerous = True` and `atomic = False`.

2021-01-05 22:40 UTC, mattrobenolt commented
Also, why does your SQL seem to be suggesting a dangerous change to the default value?

cc @wedamija

2021-01-05 22:41 UTC, mattrobenolt commented
lol I think it's materializing a new `timezone.now()` and wanting to update that.

2021-01-05 22:47 UTC, wedamija commented
> Also, why does your SQL seem to be suggesting a dangerous change to the default value?
> 
> cc @wedamija

Lol damn, since we'll need to do manual SQL to create the index concurrently we can just remove those lines.

2021-01-05 22:47 UTC, wedamija reviewed
Since this table is huge and busy, someone will need to run this manually. We should also create the index concurrently. Take a look at https://github.com/getsentry/sentry/blob/0580ecd42a13a1232200ba61611508f75610537f/src/sentry/migrations/0061_alertrule_partial_index.py#L41 for an example

2021-01-05 23:59 UTC, wedamija commented on src/sentry/migrations/0147_add_groupinbox_date_added_index.py
> +                    CREATE INDEX CONCURRENTLY IF NOT EXISTS sentry_groupinbox_date_added
I'm not sure how much it matters, but let's use the name that Django generated previously: `sentry_groupinbox_date_added_f113c11b`

2021-01-06 01:12 UTC, wedamija approved these changes

2021-01-08 19:48 UTC, mattrobenolt approved these changes

2021-01-08 19:49 UTC, merged