fix(dashboards) Autoselect text in content editable
getsentry/sentry pull request #23121
Opened 2021-01-15 19:29 UTC by markstory

Dashboards and discover saved queries should autoselect their text making renaming eaiser. The additional padding helps ensure that the cursor is contained in the div boundaries.

### Cursor not overflowing

![Screen Shot 2021-01-15 at 2 20 54 PM](https://user-images.githubusercontent.com/24086/104769928-0ba6c600-573e-11eb-889d-a1abcd4bdc56.png)

2021-01-15 19:38 UTC, k-fish approved these changes

2021-01-15 20:19 UTC, dashed requested changes
Seems to exhibit undesirable behaviour in Chrome. Clicking on the inline input selects the entire document: 

https://user-images.githubusercontent.com/139499/104774595-f7b29280-5744-11eb-9f90-d55e0255089d.mp4



https://user-images.githubusercontent.com/139499/104774594-f5e8cf00-5744-11eb-904b-9c9a00f8663b.mp4

2021-01-15 22:15 UTC, markstory commented
@dashed Thanks for catching that. Looks like chrome doesn't focus the div until the focus event is complete.

2021-01-19 21:11 UTC, dashed approved these changes
works for me

2021-01-20 19:15 UTC, merged