fix(ui): added temporary feedback button for Issues
getsentry/sentry pull request #23419
Opened 2021-01-28 18:08 UTC by robinrendle

<img width="401" alt="Screen Shot 2021-01-28 at 10 08 41 AM" src="https://user-images.githubusercontent.com/1900676/106180179-d001f800-6150-11eb-8dc0-4e4b3e505b8f.png">

2021-01-29 17:17 UTC, scttcper approved these changes

2021-01-29 17:27 UTC, iProgramStuff approved these changes

2021-02-01 20:48 UTC, scttcper requested changes

2021-02-01 20:48 UTC, scttcper commented on src/sentry/static/sentry/app/views/issueList/header.tsx
> +            <Tooltip title="You’re seeing the new issues experience because you’ve opted to be an early adopter of new features. Send us feedback via email">
needs translation, move title to button as title prop

2021-02-01 21:28 UTC, scttcper approved these changes

2021-02-01 22:58 UTC, merged