ref: Update caveats in reprocessing dialogue
getsentry/sentry pull request #23413
Opened 2021-01-28 15:42 UTC by untitaker

Based on https://github.com/getsentry/sentry-docs/pull/2907

2021-01-28 17:09 UTC, jan-auer approved these changes

2021-01-29 08:22 UTC, priscilawebdev requested changes, later dismissed

2021-01-29 08:22 UTC, priscilawebdev commented on src/sentry/static/sentry/app/views/organizationGroupDetails/reprocessingDialogForm.tsx
> +            For more information please refer to{' '}
we should use the translation function here too

2021-01-29 08:22 UTC, priscilawebdev commented on src/sentry/static/sentry/app/views/organizationGroupDetails/reprocessingDialogForm.tsx
> +              the documentation on reprocessing.
and here too

2021-01-29 11:01 UTC, merged