feat(release-health): Add session adoption to release-health
getsentry/sentry pull request #24091
Opened 2021-02-25 12:20 UTC by ahmedetefy

This PR fixes the problem that in some server-side sdks no user data is attached to session data and so no Users adoption metric information
- It solves this by calculating adoption based on sessions in addition to users adoption calculations

2021-02-26 12:54 UTC, mitsuhiko requested changes

2021-02-26 12:54 UTC, mitsuhiko commented on src/sentry/snuba/sessions.py
> +        total_users_count = total_adoption.get(x["project_id"])[0]
This will error if the .get returns None. Should make a none check and handle that case.

2021-02-26 16:18 UTC, matejminar reviewed
We need to add session adoption to the serializer too:
https://github.com/getsentry/sentry/blob/master/src/sentry/api/serializers/models/release.py#L430

2021-03-02 10:07 UTC, mitsuhiko approved these changes

2021-03-02 10:22 UTC, merged