Migration to remove db_index from sentry_file_timestamp and sentry_file_checksum
getsentry/sentry pull request #24101
Opened 2021-02-25 16:19 UTC by iProgramStuff

These are no longer indices in the database, so following up with a migration.

2021-02-25 18:10 UTC, mattrobenolt requested changes
As I mentioned in the other PR, let's make these a `DROP INDEX CONCURRENTLY IF EXISTS`. And set `atomic = False`.

2021-02-25 18:29 UTC, wedamija commented
> As I mentioned in the other PR, let's make these a `DROP INDEX CONCURRENTLY IF EXISTS`. And set `atomic = False`.

This has already been run on Saas by @JTCunning, do we need to do this here for other installations?

2021-02-25 18:29 UTC, wedamija commented on src/sentry/migrations/0166_drop_file_indices.py
> +    is_dangerous = False
Mark this as `is_dangerous` so that it doesn't run on saas, since it has already been done.

2021-02-25 18:38 UTC, mattrobenolt commented
> This has already been run on Saas by @JTCunning, do we need to do this here for other installations?

Yes please. There's 0 downside to doing this just to be safe. We should just always do this.

2021-02-25 19:11 UTC, wedamija commented
> > This has already been run on Saas by @JTCunning, do we need to do this here for other installations?
> 
> Yes please. There's 0 downside to doing this just to be safe. We should just always do this.

Ok. My concern here is that if the indexes were created in south then the name can be different. Hardcoding the names isn't really safe to do anymore. Just looking into how to do this safely with the schema editor.


```

2021-02-25 19:22 UTC, wedamija reviewed
@iProgramStuff This should do what you need. It's probably worth generalising this so that we could pass the model name and a list of columns to remove indexes from. Then we can use this for other column index drops.
```
def drop_index(apps, schema_editor):
    File = apps.get_model("sentry", "File")
    for column_name in ["timestamp", "checksum"]:
        index_names = schema_editor._constraint_names(
            File, [column_name], index=True, type_=models.indexes.Index.suffix
        )
        for index_name in index_names:
            schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS "{index_name}"')
```

2021-03-22 22:40 UTC, wedamija reviewed
Looks good to me. I wonder if we should generalize this further and allow pairs of indexes to be passed as well. IE We could pass `[('col_a', 'col_b'), ('col_a', )]` to remove any indexes that are compound on `col_a` and `col_b`, and also any that just use `col_a`. Maybe something we can do as it comes up.

2021-03-22 22:40 UTC, wedamija commented on src/sentry/utils/query.py
> +def drop_column_indexes(schema_editor, model, indexes):
Maybe `column_names` instead of indexes? Or `indexed_columns`?

2021-03-22 22:40 UTC, wedamija commented on src/sentry/utils/query.py
> +def drop_column_indexes(schema_editor, model, indexes):
Also worth having a comment that explains what this does. Something along the lines of:
"Accepts a list of columns and removes any indexes that are only relevant for those columns.". Wording is a bit hard...

2023-10-27 07:00 UTC, closed without merging