fix(bitbucket) Fix a bug when username is missing
getsentry/sentry pull request #25486
Opened 2021-04-21 15:55 UTC by immohsin

This PR fixes issue: #24333

The username in bitbucket API response was removed since April 2019 and hence the org name and URL was not showing up correctly.

More details: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

2021-04-21 22:13 UTC, manuzope commented
Thanks for the PR, @immohsin! I'll get it triaged for review!

2021-04-27 00:05 UTC, immohsin commented
@manuzope can you please triage this pr for review

2021-04-30 17:43 UTC, manuzope commented
Hi @immohsin, yes this is in our queue. We're going to try to the review in the next few days.

2021-11-11 23:38 UTC, AniketDas-Tekky requested changes

2021-11-11 23:38 UTC, AniketDas-Tekky commented on src/sentry/integrations/bitbucket/integration.py
> +            if "nickname" in principal_data:
Can you add a comment saying why we need to modify the domain and link the bitbucket documentation?

2022-02-08 20:56 UTC, ceorourke commented
Hello, this was fixed in https://github.com/getsentry/sentry/pull/31536 - apologies this PR got missed.

2022-02-08 20:56 UTC, closed without merging