Adding Authorization-header for installations-request
getsentry/sentry pull request #26281
Opened 2021-05-28 14:34 UTC by itssimple

GitHub Enterprise has deprecated using `access_token` only in querystring.

Response from newer versions:
```json
{
    "message": "Must specify access token via Authorization header",
    "documentation_url": "https://docs.github.com/enterprise/3.0/v3/#oauth2-token-sent-in-a-header"
}
```

2021-05-30 11:31 UTC, BYK commented
/gcbrun

2021-05-30 11:32 UTC, BYK commented
Thanks a lot @itssimple! I think this was overlooked when fixing the main GitHub auth a while ago.

Pinging the @getsentry/ecosystem team for a review and merge.

2021-06-01 19:53 UTC, MeredithAnya requested changes
@itssimple Thank you putting up this PR ! 

Just a couple of things: 

I would recommend adding `match_querystring=True` to the responses made to the `/user` endpoints in the GHE tests to just verify that we are making requests without the access token in the query param. (even though we are mocking out the response)

Here is one of the requests, the other is some lines above:
https://github.com/getsentry/sentry/blob/1bd0ad94c943e2fc1da129e39cd8b2606431b511/tests/sentry/integrations/github_enterprise/test_integration.py#L97-L101

Additionally, can you tell me which version of GHE you tested this out on?

2021-06-01 19:53 UTC, MeredithAnya commented on src/sentry/integrations/github_enterprise/integration.py
>              params={"access_token": access_token},
Let's remove the `params` here since you are adding the `access_token` to the headers now

2021-06-01 21:08 UTC, itssimple commented
@MeredithAnya Thanks for checking the PR!

I have committed the changes requested by adding the `match_querystring=True` to the test, and removing the params from the actual request.

I'm testing this against a 3.0.7 version of GHE.

2021-06-01 21:26 UTC, BYK commented
/gcbrun

2021-06-01 21:37 UTC, MeredithAnya commented
> @MeredithAnya Thanks for checking the PR!
> 
> I have committed the changes requested by adding the `match_querystring=True` to the test, and removing the params from the actual request.
> 
> I'm testing this against a 3.0.7 version of GHE.

Thanks for removing the params ! The `match_querystring=True` is a new arg, not part of the json so i think needs to be like the following

```python
responses.add(
    responses.GET,
    self.base_url + "/user/installations",
    json={"installations": [{"id": installation_id}]},
    match_querystring=True,
) 
```

after that I think things should be good

2021-06-01 21:41 UTC, itssimple commented
Ah, sorry. It's my first time modifying Python. :)

2021-06-01 21:43 UTC, BYK commented
/gcbrun

2021-06-01 21:53 UTC, BYK commented
/gcbrun

2021-06-01 21:55 UTC, BYK commented on src/sentry/integrations/github_enterprise/integration.py
> +                "Authorization": "token {}".format(access_token),
Pretty sure this is what the linter wants.

```suggestion
                f"Authorization": "token {access_token}",
```

2021-06-01 21:56 UTC, BYK commented
/gcbrun

2021-06-01 21:58 UTC, BYK commented on src/sentry/integrations/github_enterprise/integration.py
> +                f"Authorization": "token {access_token}",
Well, I was hasty
```suggestion
                "Authorization": f"token {access_token}",
```

2021-06-01 22:00 UTC, BYK commented
/gcbrun

2021-06-01 22:00 UTC, MeredithAnya commented
we got this team !

> fix lint once and for all

2021-06-01 22:01 UTC, MeredithAnya approved these changes

2021-06-01 22:44 UTC, merged