chore: Squash migration history and remove south compat
getsentry/sentry pull request #26567
Opened 2021-06-11 18:02 UTC by markstory

This is a potentially breaking change for self-hosted instances as they will need to update to 2021-06 before moving forward.

Squashing migrations helps speed up new environment setup and CI when migrations are changed.

2021-06-11 18:58 UTC, chadwhitacre commented
So squashing adds a migration file but doesn't remove any? Then what's the point? 🤔

2021-06-11 19:02 UTC, wedamija commented
I tried running `makemigrations` with this in place and it created migration `0207` with no relation to the squash. Is there more we need to do here to make this squashed migration the 'primary' path or w/e?

2021-06-11 20:44 UTC, markstory commented
> So squashing adds a migration file but doesn't remove any? Then what's the point? 🤔

You can remove the migrations, but Django's docs say you should have the old migrations and the squash present in the tree until all environments are synced up.

Once that is done you can update the squash, remove the `replaces` attributes and delete all the old migrations.  My thinking was that we would have the replaced migrations until the July release for self-hosted is cut afterwhich I would remove the old migration files.

2021-06-15 15:16 UTC, markstory commented
@chadwhitacre @wedamija I think this is ready now. The migration SQL generation builds are failing but I think that is due to bugs in django migrations. 

I've been testing this locally using `make reset-db` and also running tests with `MIGRATIONS_TEST_MIGRATE=1 pytest tests/sentry/api/endpoints/test_organization*`

2021-06-15 19:27 UTC, BYK requested changes
@markstory, can you add a changelog entry for this, telling people that they need to stop at this revision? @wedamija was able to cook in a warning telling people to upgrade to `9.1.2` first somehow, maybe we can also get that?

2021-06-15 19:46 UTC, markstory commented
> can you add a changelog entry for this, telling people that they need to stop at this revision?

I've updated the changelog with a note.

2021-06-16 00:43 UTC, wedamija approved these changes
@BYK was asking whether we could bake in a warning to help prevent users shooting themselves in the foot here. One option could be to repurpose the south compatibility later to make sure that people either have 0 migrations run, or up to migration 200 run and error otherwise.

Maybe we could do that when we delete the unsquashed migrations from the codebase.

2021-06-17 19:28 UTC, BYK requested changes
Requesting changes for the readme stuff. I'd also love to find a way to implement what @wedamija mentioned regarding in-code "into your face" error/warnings but I won't block on that.

2021-06-17 19:28 UTC, BYK commented on CHANGES
> +  migrations was removed.
This part needs to be moved to top, before `21.6.1` heading. I'd also add a `### Breaking Change` sub-heading like the one in `21.6.0` and put a link to https://develop.sentry.dev/self-hosted/#hard-stops

2021-06-17 22:14 UTC, BYK approved these changes
Unblocking

2021-06-18 14:01 UTC, merged