feat(symbolicator): Add an internal global option to ignore all built-in sources
getsentry/sentry pull request #27265
Opened 2021-07-09 03:39 UTC by relaxolotl

This registers a new config option that should allow sentry to omit all built-in sources during symbolication, which should enable one way to mitigate the impact of a cache refresh.

This only includes registration based on the assumption that manual action is still required in between registration and the first read of the option. (see: https://github.com/getsentry/sentry/pull/25807#issuecomment-831297640)

2021-07-09 13:43 UTC, untitaker approved these changes
I lack context on what you're doing but assuming my comment https://github.com/getsentry/sentry/pull/27264#issuecomment-877198607 doesn't apply this is the correct way to add the option. After deploying this PR, somebody needs to ssh into production and initialize it manually *before* deploying the second PR. You can ping me or ops to do that.

2021-07-09 14:12 UTC, flub requested changes
I also commented this on the other PR.  But this needs to be a sequence of source IDs to disable IIUC and not a boolean option that disables everything (and i believe this is the source of @untitaker 's confusion about why this is useful)

2021-07-09 14:14 UTC, untitaker commented
Honestly I believe this should be an option that is somehow toggleable per-symbolicator but I don't think that's possible unless Sentry does the load-balancing in-app (which would be doable but a little bit of extra work)

2021-07-09 14:16 UTC, untitaker commented
the more I think about it I wonder if this option is really needed. Wouldn't it suffice to prune the cache for one instance, and if that instance doesn't recover, remove it from HAProxy for a while? Then repeat for all instances.

2021-07-09 14:20 UTC, flub commented
> the more I think about it I wonder if this option is really needed. Wouldn't it suffice to prune the cache for one instance, and if that instance doesn't recover, remove it from HAProxy for a while? Then repeat for all instances.

This isn't a mitigation for caching though, it came in response to download trouble.  i hope this postmortem describes why we chose this: https://www.notion.so/sentry/Symbolication-backlog-due-to-intentional-cache-refresh-e451b87086c5442a956d6016345a8c75
if not we should write this up better :) it's a long read though...

2021-07-09 22:28 UTC, relaxolotl commented
Updated the flag so it accepts a sequence. @flub could I bother you to take a second look at this?

2021-07-12 08:23 UTC, flub approved these changes

2021-07-12 15:25 UTC, merged