[Removed] Theme Array and its only dependency.
getsentry/sentry pull request #27577
Opened 2021-07-20 13:22 UTC by Jesse-Box

Problem
`theme.tsx` includes a space array which was only used by one component.

Solution
Migrated the only component depending on the `theme.tsx` array to more commonly used `SPACING` object found in `space.tsx` and removed the `theme.space` array.

2021-07-20 13:28 UTC, matejminar approved these changes
Looks good to me!

2021-07-20 13:51 UTC, markstory approved these changes
:clap:

2021-07-20 13:57 UTC, priscilawebdev approved these changes, later dismissed
🚢 🇮🇹

2021-07-20 14:26 UTC, billyvg requested changes

2021-07-20 14:26 UTC, billyvg commented on static/app/components/events/rrwebReplayer/index.tsx
> +    padding: ${space(2)};
The padding values are not equivalent here (`0` missing in the shorthand), is that intentional?

2021-07-21 15:28 UTC, billyvg approved these changes

2021-07-21 20:53 UTC, dashed approved these changes

2021-07-22 06:28 UTC, priscilawebdev approved these changes

2021-07-22 07:41 UTC, merged