build(ci): Separate webpack from acceptance test runner
getsentry/sentry pull request #27656
Opened 2021-07-21 21:18 UTC by billyvg

This creates a new webpack job that prepares our frontend assets for
acceptance tests. The acceptance test runners will wait until this is
completed before running.

2021-07-23 22:17 UTC, billyvg commented on .github/workflows/acceptance.yml
> +          retention-days: 14
Default is 90 days -- there's no need to keep visual snapshots for that long.

2021-07-23 22:17 UTC, billyvg commented on .github/workflows/acceptance.yml
> +        id: wait-for-frontend
This polls for the webpack job to complete so that we can run acceptance + webpack jobs in parallel.

2021-07-26 16:55 UTC, armenzg requested changes
Only the Ubuntu change.

Good idea to tackle this!

2021-07-26 16:55 UTC, armenzg commented on .github/workflows/acceptance.yml
> +    runs-on: ubuntu-16.04
<img width="593" alt="image" src="https://user-images.githubusercontent.com/44410/127027958-882dd1f6-98ad-4151-8b50-40e2c696c7cb.png">

2021-07-26 16:55 UTC, armenzg commented on .github/workflows/acceptance.yml
> +    timeout-minutes: 20
👏🏻

2021-07-26 17:00 UTC, billyvg commented on .github/workflows/acceptance.yml
> +    runs-on: ubuntu-16.04
Oops, good catch

```suggestion
    runs-on: ubuntu-20.04
```

2021-07-26 18:02 UTC, armenzg approved these changes

2021-07-26 23:47 UTC, merged