feat(integrations): add Notion integration
getsentry/sentry pull request #28063
Opened 2021-08-13 20:52 UTC by vladanpaunovic

Create pages in **[Notion](https://www.notion.so/)** directly from **[Sentry](https://sentry.io)**. This integration also allows you to link Sentry issues to existing databases or pages in Notion.

This integration enables you to:
- Create and link Sentry issue groups directly to a Notion database in any of your workspaces, providing a quick way to jump from a Sentry bug to tracked ticket!
- Link Sentry issues to existing Notion database

## Prerequisites
Make sure to add `notion-app.client-id` & `notion-app.client-secret` in your `config.yml`.
_Feel free to request these values from me_

## What is missing?
- Autocomplete `externalIssue` when linking issues
- Notion icon (it is included in this PR, yet it magically stopped appearing for me)
- Tests (inspiration could be taken from [plugin integration](https://github.com/vladanpaunovic/sentry/blob/001299412f71f9d36d86dd5a3c425d9098cb080a/tests/sentry_plugins/notion/test_plugin.py))

## Preview
### Notion integration
![localhost_8000_settings_sentry_integrations_](https://user-images.githubusercontent.com/29886766/129001297-f75be48e-d352-4ec3-b927-fea2150d45ae.png)

### Creating a new page in Notion
![localhost_8000_organizations_sentry_issues_2__project=1 referrer=notion_integration (1)](https://user-images.githubusercontent.com/29886766/129000930-ce3e380f-a240-40b3-a10b-d2f4662d8557.png)

### Linking a page in Notion
![localhost_8000_organizations_sentry_issues_2__project=1 referrer=notion_integration (2)](https://user-images.githubusercontent.com/29886766/129001126-8c93d288-569b-4079-98fd-cfc243cc9942.png)

2021-08-13 21:06 UTC, manuzope commented
Thanks for putting up the placeholder PR, @vladanpaunovic. As discussed, this is probably unactionable until Notion's APIs are out of beta but once that is done, we can evaluate moving forward with this (heads up @jonesphillip).

2021-08-18 09:57 UTC, ahmedetefy requested changes

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/client.py
> +        return [(db["id"], db["title"][0]["plain_text"]) for db in databases["results"]]
Feel like this should be wrapped in try/catch, if `db["title"]` has no elements -> It will error

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/client.py
> +        return self.request(path=DATABASES, method="POST", data=data)
Nit: 
```
return self.request(path=DATABASES, method="POST", data={"filter": {"value": "database", "property": "object"}})
```

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/client.py
> +        data = {
I feel like this is quite verbose to be added here, I would probably move it outside to a variable especially that it is being reused here -> https://github.com/getsentry/sentry/pull/28063/files#diff-6f44ca78c71193f4cf9dd520fb3de2887f20886fa4f408a1b52a2361e5668131R130

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/integration.py
> +        notion_client = self.get_client()
Also feel like this should be wrapped in a try/catch -> What happens if line 64 fails?

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/integration.py
> +        output = [(page["id"], generate_page_title(page)) for page in notion_pages["results"]]
try/catch -> might raise an error if any of these elements are not there especially in `generate_page_title`

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/integration.py
> +                        "object": "block",
This block should be refactored like the ones above and reused

2021-08-18 09:57 UTC, ahmedetefy commented on src/sentry/integrations/notion/integration.py
> +            "external_id": authentication["workspace_name"],
`authentication.get("workspace_name")` instead so if "workspace_name" does not exist, you get a `None` rather than a `KeyError`

2021-08-18 09:57 UTC, ahmedetefy commented on static/app/plugins/components/pluginIcon.tsx
> +  notion,
Move `notion` import to below `netlify` because the list is alphabetically ordered

2021-09-22 12:13 UTC, closed without merging