feat(plugins): Add deprecation warning in UI
getsentry/sentry pull request #28143
Opened 2021-08-24 00:42 UTC by ceorourke

Have mercy on my backend soul

<img width="982" alt="Screen Shot 2021-08-23 at 5 37 35 PM" src="https://user-images.githubusercontent.com/29959063/130537470-0bb1cedb-0bc9-4f1f-a2ea-592ad720e535.png">
<img width="961" alt="Screen Shot 2021-08-23 at 5 37 46 PM" src="https://user-images.githubusercontent.com/29959063/130537475-a4a073b1-02e5-464f-ab8a-303f74a38d6d.png">

2021-08-24 17:38 UTC, robinrendle commented
@ceorourke can we left align the alert in the first screenshot 😬

2021-08-25 00:52 UTC, mgaeta requested changes
```javascript
import React, {Component} from 'react';
import styled from '@emotion/styled';

import Alert from 'app/components/alert';
import Button from 'app/components/button';
import {IconWarning} from 'app/icons';
import {t} from 'app/locale';
import space from 'app/styles/space';
import {Organization, PluginWithProjectList} from 'app/types';
import {trackIntegrationEvent} from 'app/utils/integrationUtil';

type Props = {
  organization: Organization;
  plugin: PluginWithProjectList;
};

type State = {};

class PluginDeprecationAlert extends Component<Props, State> {
  render() {
    const {organization, plugin} = this.props;

    // Short-circuit if not deprecated.
    if (!plugin.deprecationDate) {
      return <React.Fragment />;
    }
    let upgradeUrl = '';
    if (plugin.firstPartyAlternative !== null) {
      upgradeUrl =
        plugin.altIsSentryApp === false
          ? `/settings/${organization.slug}/integrations/${plugin.firstPartyAlternative}/`
          : `/settings/${organization.slug}/sentry-apps/${plugin.firstPartyAlternative}/`;
    }

    return (
      <AlertContainer>
        <Alert type="warning" icon={<IconWarning size="sm" />}>
          <span>{`This integration is being deprecated on ${plugin.deprecationDate}. Please upgrade to avoid any disruption.`}</span>
          <ResolveNowButton
            href={`${upgradeUrl}?tab=configurations&referrer=directory_upgrade_now`}
            size="xsmall"
            onClick={() =>
              trackIntegrationEvent('integrations.resolve_now_clicked', {
                integration_type: 'plugin',
                integration: plugin.slug,
                organization,
              })
            }
          >
            {t('Upgrade Now')}
          </ResolveNowButton>
        </Alert>
      </AlertContainer>
    );
  }
}

const ResolveNowButton = styled(Button)`
  color: ${p => p.theme.subText};
  float: right;
`;

const AlertContainer = styled('div')`
  padding: 0px ${space(3)} 0px 68px;
`;

export default PluginDeprecationAlert;
```

2021-08-25 00:52 UTC, mgaeta commented on static/app/types/index.tsx
> +  altIsSentryApp: boolean;
Each of these are optional so I'd make them 
```javascript
altIsSentryApp?: boolean;
deprecationDate?: string;
firstPartyAlternative?: string;
```

2021-08-25 00:52 UTC, mgaeta commented on static/app/views/organizationIntegrations/integrationListDirectory.tsx
> +      upgradeUrl =
I don't know if this is actually clearer but it's less code.
```javascript
const resource = plugin.altIsSentryApp ? 'sentry-apps' : 'integrations';
upgradeUrl = `/settings/${organization.slug}/${resource}/${plugin.firstPartyAlternative}/`;
```

2021-08-25 18:12 UTC, mgaeta approved these changes

2021-08-25 18:35 UTC, merged