fix(jira): More explicitly excise `itemKey` in `removeRow`
getsentry/sentry pull request #28664
Opened 2021-09-17 23:40 UTC by mgaeta

2021-09-18 21:55 UTC, mrbaguvix requested changes

2021-09-18 21:55 UTC, mrbaguvix commented on static/app/views/settings/components/forms/choiceMapperField.tsx
> +      );
I think we should put the _saveChanges_ param to a clearer identifier or write a comment explaining what is happening here for readability purpose.

2021-09-20 19:15 UTC, NisanthanNanthakumar approved these changes

2021-09-20 21:14 UTC, merged

2021-09-20 21:21 UTC, EvanPurkhiser commented on static/app/views/settings/components/forms/choiceMapperField.tsx
> +        Object.fromEntries(Object.entries(value).filter(([key, _]) => key !== itemKey))
`Object.fromEntries(Object.entries(value).filter(([key]) => key !== itemKey))`

You don't need the underscore, you would only need that if you didn't care about earlier indexes in the array.