WIP: ref: Move all symbolicator-related code in store.py to a separate file
getsentry/sentry pull request #28973
Opened 2021-09-29 23:57 UTC by relaxolotl

aka reduce the number of angry markus "why am i a reviewer on this" comments on native PRs.

Ingest can stop being pulled in for reviews on PRs that do not
require their feedback or should not require their feedback.

**Currently a WIP, need to sort out some details but the general idea's already there.**

2021-09-30 08:07 UTC, untitaker reviewed
thank you!

2021-09-30 08:07 UTC, untitaker commented on src/sentry/tasks/store.py
>  import logging
From this file you will have to temporarily re-export all symbolication tasks as there can be in-flight queue items for which the worker will attempt to import from this module.

```suggestion
import logging
from sentry.tasks.symbolication import symbolicate_event, ...
```

2021-09-30 10:51 UTC, flub commented
generally LGTM.  I put this in NATIVE-259 if you want to link the ticket btw

2021-09-30 15:44 UTC, loewenheim approved these changes

2021-10-02 03:15 UTC, relaxolotl commented on src/sentry/tasks/symbolication.py
> +        # TODO: this uses a private "store" function. is there a way to not do this?
nts: figure out an answer to this, namely "is this ok?" and how to make it ok if it isn't

also probably good to think about the the line that has been drawn by splitting all of the symbolicator stuff out into its own file: are there other places where it's using internal `store.py` stuff? is there symbolication logic in `store.py` that could and should be moved out into a method in this file? what are the low hanging fruit for those?

2021-10-04 16:48 UTC, untitaker commented on src/sentry/tasks/store.py
>  import logging
actually add yourself to https://github.com/getsentry/sentry/blob/a2212cd3f2cae4411c7c06bcbcecf03ba7bac2d7/src/sentry/conf/server.py#L543 instead

2021-10-15 09:10 UTC, flub reviewed
LGTM, did we test locally if events still get processed and symbolicated etc?

2021-10-19 05:48 UTC, relaxolotl commented
@untitaker can you take a second look at this when you have time?

2021-10-19 11:36 UTC, untitaker requested changes
there is one change to the task `name` attribute that really needs to be reverted and tested (probably manually), otherwise I believe this is good to go

2021-10-19 12:14 UTC, flub requested changes
https://github.com/getsentry/sentry/blob/b576d6fcd52fb8395e329a3f27b16a60ff4bddac/src/sentry/api/serializers/models/project.py#L44 also needs to be updated with this move

2021-10-19 20:11 UTC, untitaker approved these changes

2021-10-20 17:08 UTC, flub approved these changes

2021-10-20 17:58 UTC, merged