feat: Move events in the wrong queue to the right one [NATIVE-203]
getsentry/sentry pull request #29207
Opened 2021-10-08 13:57 UTC by loewenheim

2021-10-11 10:12 UTC, flub approved these changes

2021-10-11 15:04 UTC, jjbayer approved these changes

2021-10-11 15:16 UTC, flub requested changes

2021-10-13 11:14 UTC, flub approved these changes
approving to unblock.  we can always fix up the metrics.  no one in ops seems to be getting back to me.

Tests look good 😄

2021-10-13 11:23 UTC, merged