feat(symbolication): Selection logic for low priority queue [NATIVE-211]
getsentry/sentry pull request #29258
Opened 2021-10-12 13:13 UTC by flub

A bunch of refactoring still, but I think this is more or less my first proposal at the logic.

2021-10-16 02:01 UTC, relaxolotl requested changes

2021-10-18 17:59 UTC, relaxolotl approved these changes
thanks for making these changes and going through all of the suggestions 🎉

2021-10-19 08:30 UTC, flub commented
> thanks for making these changes and going through all of the suggestions 🎉

Thanks for the thorough review!

2021-10-19 09:06 UTC, Swatinem approved these changes

2021-10-20 08:00 UTC, merged