ref(celery): Make renaming tasks more painless
getsentry/sentry pull request #29421
Opened 2021-10-19 23:09 UTC by relaxolotl

There's currently a significant cost (well, greater than what it should be) associated with renaming celery tasks. As mentioned in https://github.com/getsentry/sentry/pull/28973#discussion_r719160387 which can be verified via the instructions found in https://github.com/getsentry/sentry/pull/28973#discussion_r731769288, renaming tasks will cause all in-flight tasks associated with the previous name to fail and be dropped. One must be willing to eat the cost of these dropped in-flight tasks which could end up being a fairly costly decision, meaning that there's a fairly high impact associated with something which doesn't make any meaningful change to any of the logic in the code.

This attempts to make such changes more painless by adding an additional parameter `legacy_names` to the `instrumented_task` decorator: if a task is renamed, previous names can be added to the `legacy_names` list which will take care of making sure that any tasks associated with the previous name(s) will complete. Metrics associated with instrumented tasks has also been updated appropriately so it's possible to determine when a certain legacy name is no longer in use, and can be removed from the task.

---

The nitty gritty implementation overview: This registers additional tasks with the [celery registry](http://docs.celeryq.org/en/latest/userguide/tasks.html#how-it-works), one per legacy name supplied in `legacy_names`. None of these are associated with the actual task that is exposed and exported to other modules; Only the task associated with the current name as specified by `name` will be the one that is available and invokable by other modules.

2021-10-19 23:14 UTC, relaxolotl commented
@tonyo @oioki: This PR also updates the metrics associated with symbolication tasks to reflect the namespace change that was made in #28973. This will most likely cause a minor blip in our current metrics dashboards, which I plan to update if/after this gets merged. I'd like to get your thoughts on this in case this should be reverted, or if there needs to be additional prep work done in anticipation of this change.

cc @flub @loewenheim @Swatinem

2021-10-20 09:06 UTC, Swatinem approved these changes

2021-10-20 13:33 UTC, flub requested changes
I don't really like this, it's too much complexity and moving for very little gain.  Why can't we keep those things being named by their original task names forever?

2021-10-21 08:58 UTC, flub commented
> > The Celery documentation describes in details how it can auto-name tasks based on the modules. I wouldn't claim (or at least I didn't see) that it encourages that.
> 
> I'm making a nitpicky point here, but it states this underneath the linked section:
> 
> > A best practice is to use the module name as a name-space, this way names won’t collide if there’s already a task with that name defined in another module.
> 
> Which reads pretty heavily to me as encouragement, or a recommendation. The documentation does explain how its auto-naming behaviour behaviour works as you've mentioned, but this is a recommendation outside of that explanation to use the module name.

Ok, fine.  I'll go a step further and say I disagree with celery's assertion in that case 😄 

> > I think the sentry code base chose a very good pattern of making the task names explicit and to not let them depend on the modules where the code happens to live. This exactly decouples the task naming from the module naming which is great for refactoring.
> 
> I'm confused about this assertion, particularly the bit about decoupling: As far as I can tell, a large number of task names are scoped by the modules they live in: [...]

What I mean is that every invocation of `@instrumeted_task` carries a `name='...'` argument (as far as I could tell).  That is why I say it is decoupled because the name is not automatically inferred from the module the function names the code happens to live in.  And #28973 shows that this allows us to move code around without having to deal with renamed tasks.

> Hair splitting about names aside, my main concern here is how to make it easier to rename tasks.

My main assertion is that is it not desirable to ever rename a task.  My secondary assertion is that task names do not need to match module and function names and that these will diverge over time due to refactoring, and that this is fine.

> I would be open to other ideas on how one could restructure existing modules that contain tasks while avoiding the issues outlined in the PR description (ie event dropping).  In other words, I'm curious as to what you mean by the below statement:
> 
> > it is fairly easy to make sure the tasks are available in the workers after moving things around I think if further restructuring of code is desired for something it is not something that will be that difficult.

By doing what was done in #28973: you can move the implementation of tasks without renaming the tasks.


----

I've tried to explain to explain why I think it is a bad idea to rename tasks.  If none of the reasoning is convincing and you really believe this PR is important than go ahead, I'm now assuming it is because you disagree with me rather than that I failed to explain myself.

2021-10-21 15:48 UTC, closed without merging