feat(ui): Icon Search in Storybook
getsentry/sentry pull request #30392
Opened 2021-12-03 00:38 UTC by vuluongj20

**1. New page for icon search, with:**
- Fuzzy, keyword-based search
    <img width="791" alt="Screen Shot 2021-12-02 at 4 30 20 PM" src="https://user-images.githubusercontent.com/44172267/144524305-cdfa0561-08ea-4b70-a071-b24bcae0157c.png">
- Popover panels with prop selectors and copiable code snippets
    <img width="357" alt="Screen Shot 2021-12-02 at 4 31 10 PM" src="https://user-images.githubusercontent.com/44172267/144524376-db2d1b94-dad5-4b0e-9a15-54d9b69a7f23.png">

**2. Missing icons** 
Adding icons that are in the design system on Figma but not yet in `static/app/icons`, e.g. `IconText`.

**3. File Icon story**
Moving it into the Components section, as FileIcon seems like more of a component than an asset (SVG, PNG).

2021-12-03 15:14 UTC, Jesse-Box requested changes, later dismissed
If you wanna add these new icons to the library we first need to tweak them on the design side first.

2021-12-03 15:14 UTC, Jesse-Box commented on static/app/icons/iconUnlock.tsx
> +      <g clipPath="url(#a)">
@vuluongj20 I double-checked this icon and the paths are bigger than the dimensions of the SVG itself, probably why you have this `clipPath` prop.

Check it out.

<img width="1152" alt="Screen Shot 2021-12-03 at 16 10 38" src="https://user-images.githubusercontent.com/6508377/144625596-3a14f79b-f05d-48b7-b9d6-26adc34c73bf.png">

2021-12-03 15:14 UTC, Jesse-Box commented on static/app/icons/iconSpaceship.tsx
> +        <clipPath id="a">
@vuluongj20 Same goes here

2021-12-03 15:14 UTC, Jesse-Box commented on static/app/icons/iconSend.tsx
> +        <clipPath id="a">
@vuluongj20 you get the point lol

2021-12-03 19:40 UTC, vuluongj20 commented
> If you wanna add these new icons to the library we first need to tweak them on the design side first.

@Jesse-Box Good catches! Added a couple of commits to address the issues you raised: removing the unnecessary clipPaths (https://github.com/getsentry/sentry/pull/30392/commits/46420803bc748d5006b12895eca5b4741b89da3e), and resizing IconLock/IconUnlock (https://github.com/getsentry/sentry/pull/30392/commits/1baf41caface59893e473ac76b3d6b52015b5b62).

2021-12-03 20:23 UTC, evanpurkhiser commented
Can we do this PR without adding new icons for now?

2021-12-06 19:29 UTC, vuluongj20 commented
> Can we do this PR without adding new icons for now?

Yeah makes sense - just removed them!

2021-12-14 21:21 UTC, billyvg commented
The popover is pretty cool - I got a bit confused though as I expected the icon that I clicked to change when for example, toggled isCircled:

![image](https://user-images.githubusercontent.com/79684/146081143-15dcc563-4899-446c-afb2-b84c6c9d3db4.png)

2021-12-22 21:01 UTC, billyvg approved these changes

2022-01-13 04:16 UTC, merged