feat(ci): Balance test distribution for pytest [WIP]
getsentry/sentry pull request #31049
Opened 2022-01-11 17:11 UTC by billyvg

wip...

2022-01-17 15:49 UTC, billyvg commented on .github/workflows/backend-test.yml
> +          branch: 'feat/ci/balance-pytest-test-durations'
This will be removed as it should fetch from main branch.

2022-01-17 16:21 UTC, billyvg commented
Some runs work better than others:

https://github.com/getsentry/sentry/runs/4822012995?check_suite_focus=true (here they're all around 9 minutes).

2022-01-19 21:25 UTC, joshuarli commented on .github/actions/pytest-report/action.yml
> +        echo $(pwd)
nit: You can actually just access it with `$PWD`. You don't need to subshell.

2022-01-19 21:29 UTC, joshuarli approved these changes

2022-01-20 06:46 UTC, joshuarli requested changes
@billyvg Actually, a concern: it would be annoying if tests shifted around from one job to the next. Like if you fail various tests, and then are looking for the next commit's result for a specific test, it would take more time to find if it got rebalanced to a new job. I think this is definitely going to happen for the tests with retries.

You probably want to hash the branch name and use that to freeze the distribution per PR.

2022-01-20 15:41 UTC, billyvg commented
@joshuarli That's a good point, I wonder if that's how users would approach it though? If you're fixing tests it seems likely that you'll look for failed jobs rather than a specific check?

Another thing that's potentially annoying is that this distributes individual tests vs files, so a file can be run on all instances and makes it more difficult to track down.

2022-01-20 20:46 UTC, joshuarli commented
> @joshuarli That's a good point, I wonder if that's how users would approach it though? If you're fixing tests it seems likely that you'll look for failed jobs rather than a specific check?

Well - one check is one matrix job right? If you're looking to see if you fixed a specific test and you failed a few, it'll be hard to find that specific test if it's rebalanced. If it's only one test fail then it's easy to click on whatever job fail. Actually, if there's a test that flakes in another job then it's still the same situation. Does this make sense?

2022-01-20 20:51 UTC, billyvg commented
Yeah, I'm just assuming you would click all of the failed jobs - but in the case of a flake that would definitely be annoying. We never have flakes though so it's fine _/s_

2022-01-26 20:56 UTC, billyvg commented
Can't fully implement this yet because of this bug https://github.com/actions/runner/issues/1578

2022-12-16 19:09 UTC, closed without merging