ref(ui): alert badge
getsentry/sentry pull request #31877
Opened 2022-02-16 23:18 UTC by robinrendle

- Added new icons for alert status
- Removed css from AlertBadge so that it only uses these new icons
- Removed duplicate AlertBadge on the Project Details page

![CleanShot 2022-02-16 at 15 13 56](https://user-images.githubusercontent.com/1900676/154373636-5ccc2a6d-e3ab-4b9b-bce1-4a0d333aecaf.png)
![CleanShot 2022-02-16 at 15 13 50](https://user-images.githubusercontent.com/1900676/154373647-fe1ee892-5ee4-4fe3-a68a-cd6109a155c1.png)

2022-02-17 02:41 UTC, doralchan commented
Wait wat? Why aren't you using IconDiamond

2022-02-17 02:43 UTC, doralchan requested changes, later dismissed
I'm confused about why you're not using IconDiamond instead of creating iconAlertCritical, iconAlertIssues, iconAlertResolved and iconAlertWarning

2022-02-17 19:11 UTC, robinrendle commented
@doralchan Yeah, you’re right. I’ve removed those icons and switched the background of AlertBadge to use IconDiamond.

2022-02-17 19:18 UTC, scttcper commented on static/app/components/alertBadge.tsx
> +import {IncidentStatus} from '../views/alerts/types';
```suggestion
import {IncidentStatus} from 'sentry/views/alerts/types';
```

2022-02-17 19:19 UTC, scttcper approved these changes

2022-02-18 18:23 UTC, scttcper approved these changes

2022-02-18 18:52 UTC, merged