ref(access): Convert set attributes to derived properties of Access
getsentry/sentry pull request #31880
Opened 2022-02-17 00:26 UTC by RyanSkonnord

Convert Access to an abstract class, changing teams and projects to
    dervied properties, and the "has access" methods to abstract.

    Introduce OrganizationMemberAccess to represent the former base case
    where a user has access only to a subset of their organization's teams
    and projects. Push has_global_access down to here.

    Use OrganizationGlobalAccess in more places, to represent where
    superusers and Sentry apps have access to all an organization's teams
    and projects. Enumerate those sets of teams and projects as properties.

    Tweak the class structure as needed.

Lest this look like a lot of refactoring for refactoring's sake, the actual motivation is from https://github.com/getsentry/sentry/pull/31816#discussion_r808316557 -- it would simplify the representation of team-based roles if we didn't have to build sets of `Team` objects to represent having access to all teams in the `_from_sentry_app` case. The rest of the changes snowballed from there. But, I do think it leaves the base `Access` class a bit cleaner overall.

2022-02-17 00:27 UTC, RyanSkonnord commented
See also https://github.com/getsentry/sentry/pull/31876, which added some test coverage that these changes needed.

2022-02-17 17:00 UTC, JoshFerge requested changes
I like the direction of these changes, but overall I feel there is too much here in 1 PR to be able to review and follow confidently, and given the importance of the correctness of Access I think we should be careful that we aren't introducing altered behavior.

If we want to make these changes, we should attempt to do it in smaller chunks so each change can be examined thoroughly IMO. We could do this in a few different ways -- stacked PRs, having the ABC along with the current class and slowly replacing the concretes, etc. Let me know what you think.

2022-02-18 00:31 UTC, RyanSkonnord commented
Thanks @JoshFerge for the feedback.

I'd contend that this PR does represent one logical change -- that is, converting `Access` to an abstract class that disclaims responsibility over teams and projects -- and that the rest of the changes are just OOP bookkeeping. I'm generally more open to such a large change being pushed atomically when it's a behaviorally-equivalent refactoring; we have pretty thorough test coverage on this code.

But, I think I could probably rework it into smaller PRs. Step 1 would probably be to construct `OrganizationGlobalAccess` instead of `Access` in `_from_sentry_app` (the original goal) and other places as in this PR. Step 2 would be to introduce `OrganizationMemberAccess`. Then step 3 would be to convert `Access` to ABC. Part of the reason I originally loaded more changes onto step 1 had to do with small differences in behavior from `OrganizationGlobalAccess`, but that's probably solvable in fewer SLOC changes.

2022-02-18 18:30 UTC, JoshFerge commented
> Thanks @JoshFerge for the feedback.
> 
> I'd contend that this PR does represent one logical change -- that is, converting `Access` to an abstract class that disclaims responsibility over teams and projects -- and that the rest of the changes are just OOP bookkeeping. I'm generally more open to such a large change being pushed atomically when it's a behaviorally-equivalent refactoring; we have pretty thorough test coverage on this code.
> 
> But, I think I could probably rework it into smaller PRs. Step 1 would probably be to construct `OrganizationGlobalAccess` instead of `Access` in `_from_sentry_app` (the original goal) and other places as in this PR. Step 2 would be to introduce `OrganizationMemberAccess`. Then step 3 would be to convert `Access` to ABC. Part of the reason I originally loaded more changes onto step 1 had to do with small differences in behavior from `OrganizationGlobalAccess`, but that's probably solvable in fewer SLOC changes.

There are behavior changes in this PR -- see this test case below involving ApiKey access: passes on master, fails on this branch. The change may be innocuous, but to me is a signal we should be more careful and add coverage as we go.

```
class FromAuthTest(TestCase):
    def test_from_token(self):
        project = self.create_project(organization=self.organization)
        project.status = ProjectStatus.PENDING_DELETION
        project.save()

        api_key = ApiKey.objects.create(
            organization=self.organization, scope_list=["project:write"]
        )
        result = access.from_auth(api_key, self.organization)
        assert result.has_project_access(project) is True
```

2022-02-18 21:12 UTC, RyanSkonnord commented
> There are behavior changes in this PR -- see this test case below involving ApiKey access: passes on master, fails on this branch. The change may be innocuous, but to me is a signal we should be more careful and add coverage as we go.

I actually almost wrote a third paragraph about that exact thing yesterday but was trying not to overload on details. 😅

I did knowingly introduce a few behavioral changes in the course of unifying the "from Sentry app" case with the "organization global access" case, including this difference with access to non-visible projects. As I did this, my thought was that at least one of the following applied:

1. The change doesn't matter, as indicated by the lack of a unit test that cares.
2. It's actually more correct, or at least more intuitive, to consistently filter non-visible projects from all kinds of access objects. It's just an oversight that, currently, some do and others don't.

It would take some investigation to say exactly which is the case, but without investing that effort, I'd opine that simplifying the code justifies a bit of "move fast and break things" approach.

However, I am duly chastened for letting the change slip in invisibly, as though it were an unnoticed side effect of the larger refactoring. As I break up this PR, I'll make a point of calling it out in the commit logs and maybe add to the unit tests too, so as to leave some breadcrumbs in case it does cause a regression. (I'm also open to discussion if you disagree with me about the change being safe.)

2022-02-24 00:56 UTC, RyanSkonnord commented
Broke out a smaller change set into https://github.com/getsentry/sentry/pull/32020.

2022-02-24 00:56 UTC, closed without merging