fix(alert-rule): Fix attribute error
getsentry/sentry pull request #32142
Opened 2022-03-01 00:10 UTC by NisanthanNanthakumar

Fixes [SENTRY-TFB](https://sentry.io/organizations/sentry/issues/3056121071/events/3974d9080f3547f99660b08f20a6850f/?project=1&statsPeriod=14d)

2022-03-01 00:12 UTC, ceorourke approved these changes

2022-03-01 00:14 UTC, mgaeta commented
Needs tests. Also `_fetch_sentry_app_uri()` gets settings the same way. Will it be broken?

2022-03-01 00:32 UTC, dashed requested changes
a test to trigger this would be nice to have.

2022-03-01 02:47 UTC, mgaeta commented on src/sentry/incidents/endpoints/organization_alert_rule_details.py
> +        serialized_rule["errors"] = errors
I would just not attach `errors` if it's an empty list.

2022-03-01 02:47 UTC, mgaeta commented on src/sentry/api/endpoints/project_rule_details.py
> +                # print(action)
oops

2022-03-01 02:48 UTC, mgaeta commented
I'd still like to see a test.

2022-03-01 18:28 UTC, mgaeta approved these changes

2022-03-01 23:52 UTC, NisanthanNanthakumar commented on tests/sentry/api/endpoints/test_project_rule_details.py
> +        response = self.client.get(url, format="json")
@dashed nah its still 200. We still want to return the alert rule even if the SentryApp action is disabled. I can make it more explicit and check the status code here

2022-03-02 00:24 UTC, dashed approved these changes

2022-03-02 22:57 UTC, merged