feat(appconnect): Introduce an endpoint to trigger refresh of builds
getsentry/sentry pull request #33457
Opened 2022-04-08 15:20 UTC by flub

Normally the builds are refreshed once an hour, however we're adding a
way to trigger this manually.  This endpoint is still severely
ratelimited.

NATIVE-139

2022-04-08 16:10 UTC, loewenheim approved these changes

2022-04-08 17:31 UTC, AniketDas-Tekky requested changes
There should be unit tests to ensure correct API responses.

2022-04-08 18:48 UTC, wedamija reviewed
Probably also worth adding this endpoint to codeowners

2022-04-12 21:44 UTC, AniketDas-Tekky reviewed
Who's going to call this API? What is their authentication going to be? Could we restrict which authentication class is used?

2022-04-13 07:25 UTC, flub commented
> Who's going to call this API? What is their authentication going to be? Could we restrict which authentication class is used?

I guess one could wonder why this is `StrictProjectPermission` vs `ProjectSettingPermission`, this what you're alluding to?  I don't know the answer to this though as I was not involved with this initial choice.  The entire `projects/{org_slug}/{proj_slug}/appstoreconnect/` hierarchy uses the same permissions set, as it should.  For this PR changing that permission is huge scope creep as it involves changing permissions of existing APIs etc.  If you really believe this should be re-evaluated I think that's a separate issue to resolve.

2022-04-13 08:35 UTC, priscilawebdev commented on src/sentry/api/endpoints/project_app_store_connect_credentials.py
> +    ``GET projects/{org_slug}/{proj_slug}/appstoreconnect/status/``
good catch!

2022-04-13 08:36 UTC, priscilawebdev approved these changes
tested locally and everything seems to work fine

2022-04-13 14:54 UTC, flub commented
(FWIW #33576 did get merged into this PR by accident, please ignore the changes to the frontend.  This was supposed to be merged into master once this PR landed there.)

2022-04-14 17:18 UTC, AniketDas-Tekky approved these changes

2022-04-14 17:21 UTC, AniketDas-Tekky commented
> > Who's going to call this API? What is their authentication going to be? Could we restrict which authentication class is used?
> 
> I guess one could wonder why this is `StrictProjectPermission` vs `ProjectSettingPermission`, this what you're alluding to? I don't know the answer to this though as I was not involved with this initial choice. The entire `projects/{org_slug}/{proj_slug}/appstoreconnect/` hierarchy uses the same permissions set, as it should. For this PR changing that permission is huge scope creep as it involves changing permissions of existing APIs etc. If you really believe this should be re-evaluated I think that's a separate issue to resolve.

What I meant was the `authentication_classes` not `permissions`. By default we allow Session, Basic, and Token authentication. Meaning anyone with a token could hit this endpoint if they wanted. We could restrict it to Session only. while it won't stop crafty users for hitting the endpoint, it should reduce it/make it harder.

I'm just trying to see if there's a way to avoid being forced to support a private API

2022-04-19 08:54 UTC, flub commented
> What I meant was the `authentication_classes` not `permissions`. By default we allow Session, Basic, and Token authentication. Meaning anyone with a token could hit this endpoint if they wanted. We could restrict it to Session only. while it won't stop crafty users for hitting the endpoint, it should reduce it/make it harder.

Ah, I see.  To be honest having "Token" made testing this locally a lot easier :)

> I'm just trying to see if there's a way to avoid being forced to support a private API

More seriously, I actually think all the `.../appstoreconnect/*` APIs should be made public.  There really is nothing that should stop a customer from building some automation for this, maybe they want to regularly expire and refresh these credentials.  It is only private right now out of, err, no one gave us time to build it publicly and this wasn't a thing yet when it was first created.

2022-04-19 09:47 UTC, merged