dlee(1): Add more whitespace to options in roleSelectControl
getsentry/sentry pull request #33551
Opened 2022-04-12 19:30 UTC by leedongwei

### Before

<img width="394" alt="pr1-2" src="https://user-images.githubusercontent.com/1748388/163039161-d7cfc417-4043-4f3e-9d12-58c55219cbe2.png">

### After 

<img width="449" alt="pr1-1" src="https://user-images.githubusercontent.com/1748388/163039149-beaa0bc7-b5e6-4dc3-b5d8-c554d4663584.png">

2022-04-12 19:33 UTC, nhsiehgit approved these changes

2022-04-15 09:15 UTC, evanpurkhiser commented
What's going on here? This appears to be broken from what it looked like before. cc @vuluongj20.

There definitely should be more padding on the inside of this select.

2022-04-15 09:16 UTC, evanpurkhiser requested changes
Going to let vu chime in here

2022-05-09 22:22 UTC, evanpurkhiser approved these changes

2022-05-09 23:05 UTC, dashed approved these changes

2022-05-10 19:40 UTC, merged