fix(relay): Do not rate-limit auth endpoints
getsentry/sentry pull request #35050
Opened 2022-05-26 16:48 UTC by untitaker

Our internal relays are hitting those endpoints as the autoscaler kicks in. We need to make sure those endpoints are always available.

External relays will also hammer those endpoints. If we rate-limit in those cases, we risk losing events as well. So internal vs external requests doesn't matter too much.

2022-05-26 16:50 UTC, AniketDas-Tekky approved these changes

2022-05-27 07:56 UTC, jan-auer requested changes
We want those auth endpoints rate limited, since they are also being used by external Relays. In a proper fix, we would need to ensure that those rate limits are bypassed by trusted relays, but enforced on external ones. 

See [INGEST-1310](https://getsentry.atlassian.net/browse/INGEST-1310)

2022-05-30 08:04 UTC, untitaker commented
I raised the rate limit to 200 rps / IP. I suspect our internal relays's requests (all pods) are coming all from the same IP, so this would be effectively a global limit.

I believe the original limit was 70/IP in code, but our internal stats don't show this kind of traffic.

2022-05-30 08:20 UTC, jan-auer approved these changes

2022-05-30 08:20 UTC, jan-auer commented on src/sentry/api/endpoints/relay/register_challenge.py
> +            RateLimitCategory.IP: RateLimit(200, 1),
_nit_: Add a constant somewhere in `endpoints/relay/` to indicate which limits belong together.

2022-05-30 08:25 UTC, jjbayer approved these changes
Might want to update the PR title / description to something like "Raise rate limits.."

2022-05-31 07:29 UTC, merged