ref(projectconfig): Count project config computations
getsentry/sentry pull request #35133
Opened 2022-05-31 08:24 UTC by flub

This allows to keep track of the rate of project config computations,
which are a relatively expensive operation.

Alternative to the rather more scary experiment at #35107

2022-05-31 08:28 UTC, jjbayer commented on src/sentry/relay/config/__init__.py
> +    metrics.incr("sentry.relay.config.get_project_config")
Do we care about absolute numbers here?
```suggestion
    metrics.incr("sentry.relay.config.get_project_config", sample_rate=1.0)
```

2022-05-31 08:29 UTC, jan-auer requested changes, later dismissed

2022-05-31 08:32 UTC, untitaker reviewed
this metric already exists as `sentry.relay_project_configs.get_config.duration.count`, though we may want to bump the sample rate of the timer.

2022-06-01 12:33 UTC, untitaker approved these changes

2022-06-01 12:36 UTC, flub commented
Changed this to a timer, which also gives us a count.

I though about removing https://github.com/getsentry/sentry/blob/57fa2fca83f2f8ea3b15ca6606cc8474e0aa7da4/src/sentry/api/endpoints/relay/project_configs.py#L127 which covers the same but only partially.  Though it may break dashboards so I left it alone.

Regarding the `sample_rate=1`: this metric happens often enough that I don't think we need to revert to that.  I think this is mostly needed when you have metrics that are rarely emitted which skews the results, for something emitted a lot the default sampling should be fine.  (not that i endorse sampling of metrics, my personal opinion is that it is heresy caused by a poor metrics transport (statsd) - the metric type already defines the aggregation)

2022-06-02 08:49 UTC, jan-auer commented on src/sentry/relay/config/__init__.py
> +            return _get_project_config(project, full_config=True, project_keys=None)
Could you use `@metrics.wraps("relay.config.get_project_config.duration")` on the `get_project_config function instead?

2022-06-09 12:59 UTC, merged