feat(ci): Label PRs backend / frontend
getsentry/sentry pull request #35420
Opened 2022-06-07 00:59 UTC by evanpurkhiser

2022-06-07 10:58 UTC, armenzg requested changes
I love the Ukranian flag colours :)
<img width="136" alt="image" src="https://user-images.githubusercontent.com/44410/172362988-965cec34-9365-4fcd-bff1-e5d089dde82f.png">

This will be really useful when looking at the Pull Requests tab.

2022-06-07 10:58 UTC, armenzg commented on .github/workflows/label-pullrequest.yml
> +          list-files: shell
I don't think you need to list the files.

2022-06-07 10:58 UTC, armenzg commented on .github/workflows/label-pullrequest.yml
> +        if: needs.files-changed.outputs.frontend == 'true'
You need to do `steps.changes` instead since you're not trying to access the output of a job you depend on named `files-changed`.

2022-06-07 21:31 UTC, davidenwang commented
taking this over from Evan since he is on vacation, lmk if those changes are correct.

2022-06-08 12:51 UTC, armenzg approved these changes
Thank you for taking over and addressing my comments!

2022-06-08 13:43 UTC, armenzg requested changes
What Billy said

2022-06-08 19:57 UTC, davidenwang commented on .github/workflows/label-pullrequest.yml
> +        uses: actions-ecosystem/action-add-labels@v1
good call

2022-06-08 20:26 UTC, armenzg approved these changes

2022-06-09 14:58 UTC, merged