feat(sampling): Add E2E tests - [TET-101]
getsentry/sentry pull request #35780
Opened 2022-06-17 14:59 UTC by priscilawebdev

**What this PR does:**

- Add End 2 End tests for the Sampling configuration in settings
    -  Drag and Drop
    -  Rule order
    - Add a rule with all possible conditions
    - Validate the payload

2022-06-20 13:13 UTC, matejminar commented
@priscilawebdev I feel like most of these could be just tested with RTL.

The initial intent of this JIRA story was to test the contract between frontend, backend, and relay.
1. Build a huge rule in UI that contains all conditions
2. Assert the payload (documented here: https://www.notion.so/sentry/Dynamic-Sampling-Rules-Payload-339ddc44f13944de9ed414ec821a3271)
3. Make sure that relay is also ok with that payload (https://github.com/getsentry/sentry/blob/ac7f56ae3fd2357f6eef1f54e46258bc27d5e157/src/sentry/api/endpoints/project_details.py#L95-L113)

2022-06-20 13:25 UTC, priscilawebdev commented
I see.. yes, apart from the drag and drop test, I totally agree with you. I confess that when I started working on this PR, the goal was not so clear to me, so thank you for clarifying this 🙏

2022-06-22 09:29 UTC, andriisoldatenko requested changes

2022-06-22 09:35 UTC, andriisoldatenko approved these changes

2022-06-22 09:58 UTC, merged