fix(api): allow OrganizationReleaseDetailsEndpoint to accept empty version
getsentry/sentry pull request #36452
Opened 2022-07-07 22:29 UTC by barkbarkimashark

Customer reported trying to archive a release with a empty `version` field. Looking at the DB, there are 152 rows of releases where this is the case - possibly due to an old code? 

To allow customers to archive these presumably faulty releases, this change is needed to accept PUT requests with empty `version` in the URL path.

2022-07-07 22:38 UTC, barkbarkimashark commented
Release with empty version doesn't look like legacy code. Recent rows are still being created:
<img width="1279" alt="Screen Shot 2022-07-07 at 3 35 08 PM" src="https://user-images.githubusercontent.com/101606877/177882727-f3cd0b7b-0c86-479d-b638-1de8469a8791.png">

Somehow a codepath is bypassing the `ReleaseWithVersion` serializer and creating Release rows with empty version (and a lot of other missing column values). 

For now, allowing users to archive these bad releases is easier than tracking down where in the codebase releases with empty versions are being created.

2022-07-08 00:41 UTC, AniketDas-Tekky requested changes

2022-07-08 00:41 UTC, AniketDas-Tekky commented on src/sentry/api/urls.py
> +                    r"^(?P<organization_slug>[^\/]+)/releases/(?P<version>[^/]*)/$",
Accepting no version is gonna cause this route to collide with the OrganizationReleasesEndpoint 

https://github.com/getsentry/sentry/pull/36452/files#diff-0568d2568ed366405103d213b7ba1291a283f1e517375416fb758ffd41f308f0R1404

2022-07-08 13:46 UTC, markstory commented
> Somehow a codepath is bypassing the ReleaseWithVersion serializer and creating Release rows with empty version (and a lot of other missing column values).

My bet is that customers are sending `''` as the release tag in events. During ingestion if an error/transaction uses a release that doesn't exist yet, we create a release. We have the same behavior for environments too.

2022-07-08 16:33 UTC, barkbarkimashark commented
Would it make more sense to clear up the 152 rows in the DB with invalid release version, update the ingestion codepath to not create a release if version is empty string.

This way we won't need to mess around with the OrganizationReleaseDetailsEndpoint URL.

2022-07-11 13:45 UTC, markstory commented
> Would it make more sense to clear up the 152 rows in the DB with invalid release version, update the ingestion codepath to not create a release if version is empty string.

I think not making `''` slug releases makes sense, they aren't something we can easily support and are already disallowed by the release creation APIs.

2022-07-13 03:34 UTC, barkbarkimashark commented
Note to self, this looks like where we create releases from events - need to make sure `version` is not empty string or null before creating a release:
https://github.com/getsentry/sentry/blob/2ff4da3321129cd72ccabcd54d5bca78a12a4ea5/src/sentry/event_manager.py#L682-L686

2022-07-13 03:37 UTC, barkbarkimashark commented
Will have to rethink this PR. Instead of allowing users to archive releases with empty `version`, I think it makes more sense to:
1. dis-allow creating Releases with empty version in event ingestion. 
2. Write a backfill to scan through `Releases` and remove any rows with empty string in the `version` column.

2022-07-13 03:37 UTC, closed without merging