feat(build): Make freezing requirements idempotent
getsentry/sentry pull request #38175
Opened 2022-08-26 14:06 UTC by armenzg

Running `make freeze-requirements` without changes to the base requirements file should not update to newer packages.

This makes it harder to make unintended changes

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> -beautifulsoup4>=4.7.1
Most changes in this file are just `s/>=/==`.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +mistune==2.0.4
Using the same version as the one in the frozen file.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +google-auth==1.35.0
Using the same version as the one in the frozen file.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +urllib3[brotli]==1.26.11
Using the same version as the one in the frozen file.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +cryptography==37.0.2
Using the same version as the one in the frozen file.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +cffi==1.15.1
Using the same version as the one in the frozen file.

2022-08-26 14:09 UTC, armenzg commented on requirements-base.txt
> +sqlparse==0.3.0
Using the same version as the one in the frozen file.

2022-08-26 20:47 UTC, armenzg commented
Using a split view makes reviewing this easier:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/44410/186988357-5414ea90-3a40-4e88-a591-8987e73a7b8e.png">

2022-08-29 12:35 UTC, asottile-sentry requested changes

2022-08-29 12:39 UTC, armenzg commented on requirements-base.txt
> +beautifulsoup4==4.7.1
Let's say you want to update package A and run `make freeze-requirements`, would it not update everything required for package A (expected) while also updating some other packages (I would say unexpected or a side-effect).

2022-08-29 12:52 UTC, armenzg commented on requirements-base.txt
> +beautifulsoup4==4.7.1
Ah okay. I may have experienced that. Thanks @asottile-sentry

2022-08-29 12:52 UTC, closed without merging