fix(replays): Fixes replay times exceeding duration
getsentry/sentry pull request #38209
Opened 2022-08-29 18:04 UTC by danecando

### Issue
Actual replay time was exceeding the value of the replay duration causing overflow in the UI

### Changes
- Updates `getDurationMs` to be calculated based on finish and starting time 

Closes #38176 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2022-08-29 18:27 UTC, billyvg approved these changes
This is ok as a temp fix, but we should look into why our duration value from the event differs from the start/end -- I'm thinking it's related to the SDK not sending the earliest and latest timestamps.

2022-08-29 19:18 UTC, ryan953 commented
I don't think we should put in this temp fix. It's going to hide the real issue, which is that the SDK and/or backend are not returning a duration that makes sense. Who's to say that the finishedAt time is more correct?

We need to fix the root bug.

2022-08-29 19:22 UTC, danecando commented
I agree. I'm just not as familiar with the SDK and backend so I automatically reach for the solution in front of me. I'll see if I can't identify the root issue here

2022-08-30 16:45 UTC, ryan953 requested changes
Pause on this for now, we'll make the changes in the backend or sdk instead.

2022-08-30 16:45 UTC, closed without merging