fix(replays): Replay list error UI
getsentry/sentry pull request #38454
Opened 2022-09-06 12:28 UTC by danecando

When running a search query that isn't supported the error UI replaced the entire replay list view. This update keeps the view/list UI and renders the error in the table.

Closes #38367 

### Changes
- Moves replay list fetch error UI inside of the table

### Notes
The regular issues/events API just returns no results when given invalid search args and the replay API returns a 400. So a difference in behavior between the two APIs. 

Before:

![Screen Shot 2022-09-06 at 8 23 46 AM](https://user-images.githubusercontent.com/3721977/188634839-8d49688a-03bc-4e86-90aa-798d5123ce80.png)

After:

![Screen Shot 2022-09-06 at 8 23 38 AM](https://user-images.githubusercontent.com/3721977/188634861-8843fbb8-8925-419c-b38c-0b4e6d78c984.png)

Updated after with Alert:
![Screen Shot 2022-09-06 at 12 57 06 PM](https://user-images.githubusercontent.com/3721977/188695873-0bd85b6d-f8e3-4dd9-9122-9b3efa4c1ae9.png)

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2022-09-06 16:01 UTC, billyvg commented on static/app/views/replays/replayTable.tsx
> +        />
Let's use `<Alert>` - https://storybook.sentry.dev/?path=/story/components-alerts-alert--with-icons

Example on issue stream:
![image](https://user-images.githubusercontent.com/79684/188682391-80a0b7b9-7956-4f97-81bc-def6b122e6c3.png)


(although there shouldn't be a margin-bottom there)

2022-09-08 16:14 UTC, billyvg approved these changes

2022-09-08 17:03 UTC, ryan953 requested changes
I think actually this needs changes. The ticket says ".. should show no replay results instead of an error view" and it looks like that description aligns with what the Issues search shows too.

example:
![Screen Shot 2022-09-08 at 10 03 23 AM](https://user-images.githubusercontent.com/187460/189182560-f2fc926a-f44a-4749-bca4-7b3853578219.png)

2022-09-08 17:29 UTC, ryan953 approved these changes

2022-09-08 17:32 UTC, billyvg commented on static/app/views/replays/replayTable.tsx
> +          search parameters or an internal systems error.
Oops this should be wrapped in a `t()`

2022-09-09 21:09 UTC, ryan953 commented
conflicts

2022-09-12 19:56 UTC, merged