ref(js): Remove react-hotkeys-hook in favor of ours
getsentry/sentry pull request #38497
Opened 2022-09-07 00:52 UTC by evanpurkhiser

Jenn replaced most of this already

2022-09-07 01:07 UTC, scttcper requested changes
needs yarn.lock update

2022-09-07 14:09 UTC, scttcper approved these changes

2022-09-08 07:52 UTC, priscilawebdev approved these changes

2022-09-08 14:03 UTC, scttcper approved these changes

2022-09-08 17:22 UTC, evanpurkhiser commented
Needs a bit more work. Unfortunately this captures these key presses while in an input as well, which is not what we want

2022-09-13 16:35 UTC, merged