feat(spans): Add pageload span <meta> tags
getsentry/sentry pull request #39349
Opened 2022-09-27 18:30 UTC by dashed

On pageload, let the backend span (i.e. python) be the first span of the trace.

2022-09-27 18:34 UTC, sl0thentr0py approved these changes

2022-09-27 18:37 UTC, AbhiPrasad requested changes
Before we merge can we confirm that

a) if we need to update sample rates in https://github.com/getsentry/sentry/blob/master/src/sentry/utils/sdk.py

b) if this affects dynamic sampling in anyway

2022-10-27 11:44 UTC, AbhiPrasad approved these changes
@dashed can we revive and :shipit:? With the DS changes, we should be good to go.

2022-10-27 11:45 UTC, AbhiPrasad commented
Also though sanity check review from @mitsuhiko to make sure this is all fine

2022-10-27 14:55 UTC, merged