various updates/fixes to plugins to make customization easier
getsentry/sentry pull request #4197
Opened 2016-09-22 00:24 UTC by macqueen

2016-09-22 00:25 UTC, macqueen commented on src/sentry/api/serializers/models/plugin.py
> +        'required': field.get('required', True),
this matches django forms and the `GenericField` component

2016-09-22 00:26 UTC, macqueen commented on src/sentry/static/sentry/app/components/forms/form.jsx
> +          {this.props.extraButton}
this just makes something like this possible:
![screenshot 2016-09-21 17 26 03](https://cloud.githubusercontent.com/assets/5026776/18733519/86009fe2-8020-11e6-84ad-148b48abc5cd.png)

2016-09-28 16:48 UTC, dcramer commented
per convo last night, I'm ok making required the default, but we should audit existing usage (and probably just be explicit going forward)

2016-09-28 16:49 UTC, dcramer requested changes
at the very least we'll need to adjust the webhooks plugin to not make URLs required. Not sure if any other integrations have similar behaviors.

2016-09-28 18:05 UTC, dcramer approved these changes

2016-09-28 18:07 UTC, merged