feat(serializers): Fault-tolerant serialization
getsentry/sentry pull request #41987
Opened 2022-12-02 22:56 UTC by NisanthanNanthakumar

## Objective:

We should not let failing child serializers make the root serializer return an error.

Serializers should have an error boundary that returns None and let the root serializer succeed.

2022-12-02 23:34 UTC, dashed commented on src/sentry/api/serializers/base.py
> +    ) -> MutableMapping[str, JSONData]:
```suggestion
    ) -> Optional[MutableMapping[str, JSONData]]:
```

2022-12-02 23:35 UTC, dashed approved these changes

2022-12-05 14:52 UTC, untitaker requested changes
there are a bunch of unrelated changes in there that i cannot review.

2022-12-05 15:27 UTC, markstory commented on src/sentry/api/endpoints/group_integration_details.py
> +            if action == "create":
Are there other actions? Should we raise if another action category is encountered?

2022-12-07 18:55 UTC, untitaker approved these changes

2022-12-07 19:41 UTC, merged