chore(hybrid-cloud): use organization_slug in relay projectconfig api
getsentry/sentry pull request #42105
Opened 2022-12-06 22:09 UTC by cathyteng17

Adds `organization_slug` to the url for the `RelayProjectConfigsEndpoint` since it should be a region silo endpoint. Also keeps the original url.

** not sure if anything should change within the endpoint itself, which is currently grabbing Relay project configs regardless if they belong to the organization in the url **

Addresses HC-508

2022-12-07 04:29 UTC, dashed approved these changes

2022-12-07 05:39 UTC, RyanSkonnord approved these changes

2022-12-07 05:39 UTC, RyanSkonnord commented on src/sentry/api/endpoints/relay/project_configs.py
> +    def post(self, request: Request, organization_slug: str = None) -> Response:
Should be `Optional[str]` because of the default `None`.

2022-12-07 05:39 UTC, RyanSkonnord commented on tests/sentry/api/endpoints/test_relay_projectconfigs.py
> +@pytest.mark.parametrize("path", paths)
Nice. 👌

2022-12-07 10:15 UTC, jjbayer requested changes
I'm not sure if the new URL makes sense: The only client of this endpoint is Relay, which has no knowledge of organization slugs. A single request queries project configs for multiple organizations, so which slug should Relay insert into the request URL?

Could you point us to some documentation about why this change is necessary?

2022-12-07 11:02 UTC, dashed requested changes
@cathyteng17 Should this be region bounded instead of organization bounded?

2022-12-07 21:31 UTC, RyanSkonnord commented
> Could you point us to some documentation about why this change is necessary?

https://www.notion.so/sentry/Build-new-APIs-for-organization-less-resources-4c0eac5d84c54e92a0cf8d3ab55f64a0

My understanding -- possibly wrong -- was that this fit into the larger goal of allowing the control silo to proxy API requests to the correct region silo. In most cases, this can be done by taking the org slug from the address and looking up the region where that org lives. The page linked above is for the pathological cases where we don't have an org slug but still need to resolve to a region.

These Relay endpoints did indeed seem awkward in that they aren't naturally scoped to one org. When I reviewed this code earlier, I had missed the note on the Notion page about "These endpoints are not organization bound, but will need to become region focused", and assumed that it was good enough to take one arbitrary org slug and use that for region resolution. That's definitely awkward, but makes sense if we want symmetry with the other listed endpoints. If symmetry isn't the goal, then adding a region name to the path is fine.

And now that I'm discussing it, I'm doubting my understanding of the overall purpose. It wouldn't maintain backward compatibility if the user has to add a new region name or org slug to the address: if they're changing it at all, why not just point it to the region silo? I'll follow up on Slack.

2022-12-08 16:06 UTC, markstory commented
> These Relay endpoints did indeed seem awkward in that they aren't naturally scoped to one org. When I reviewed this code earlier, I had missed the note on the Notion page about "These endpoints are not organization bound, but will need to become region focused", and assumed that it was good enough to take one arbitrary org slug and use that for region resolution. That's definitely awkward, but makes sense if we want symmetry with the other listed endpoints. If symmetry isn't the goal, then adding a region name to the path is fine.
> 
> And now that I'm discussing it, I'm doubting my understanding of the overall purpose. It wouldn't maintain backward compatibility if the user has to add a new region name or org slug to the address: if they're changing it at all, why not just point it to the region silo? I'll follow up on Slack.

Yeah, I don't think there is much value in having an arbitrary organization slug unless we're going to use that scope. Relay doesn't have a way to get an organization slug for this a relay registration is per region/processing pipeline.

Without an organization slug to do routing we won't be able to route requests to these endpoints via the backwards compatibility proxy. However that isn't likely to be that important as relay will need to be configured to register with the region anyways.

2022-12-09 19:26 UTC, cathyteng17 commented
closing this since we want relay APIs to be region-scoped and not organization-scoped

2022-12-09 19:26 UTC, closed without merging