Collapse repeat frames
getsentry/sentry pull request #4224
Opened 2016-09-27 22:01 UTC by MaxBittker

https://photos-5.dropbox.com/t/2/AAD1BkC8M54pM9oBTIYgFzHGEvboVsrdR20FrTTY2U5Hlw/12/606058082/png/32x32/1/_/1/2/Screenshot%202016-09-27%2015.00.20.png/EJCurPIEGAggAigC/apFD7VO3Y9ADbOVuak8SleopUeRnfHbdArMlFb7nCSg?size=800x600&size_mode=3

2016-09-27 22:40 UTC, MaxBittker commented
![screenshot 2016-09-27 15 37 28](https://cloud.githubusercontent.com/assets/5915546/18894604/c5ca1296-84c8-11e6-85b7-a3d139453866.png)

2016-09-27 23:06 UTC, ckj commented
@MaxBittker 😍 . Colors and position both feel pretty good. 👍  from me.

2016-09-27 23:07 UTC, benvinegar commented
Pretty cool.

2016-09-28 01:06 UTC, benvinegar requested changes
This looks great – my only continued feedback is to change the style so that it matches most of the other code.

2016-09-28 01:06 UTC, benvinegar commented on src/sentry/static/sentry/app/components/events/interfaces/stacktraceContent.jsx
> +      if(!repeatedFrame){
One space after `if` and one space before the brace:

```javascript
if (!repeatedFrame) {
```

2016-09-28 01:08 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/events/interfaces/stacktraceContent.jsx
> +      if(!repeatedFrame){
i got this

2016-09-28 01:16 UTC, benvinegar approved these changes

2016-09-28 01:25 UTC, merged