ref: Replace Hierarchical Grouping with new Beta
getsentry/sentry pull request #42480
Opened 2022-12-20 09:37 UTC by Swatinem

This has the consequence that existing users of the mobile grouping strategy (aka hierarchical grouping) will be automatically migrated to the default grouping config via automatic grouping updates.

The change to `project_grouping_configs` should stop advertising the strategy as "latest".

So far this is still in DRAFT and should wait for proper communications and docs changes related to deprecation and removal of this grouping strategy.

2022-12-20 12:46 UTC, mitsuhiko requested changes
This makes sense to me but i think we should separate the retirement from the new grouping strategy. Otherwise we have to roll them out simultaneously.  I believe the date for hierarchical retirement is January?

2022-12-20 12:46 UTC, mitsuhiko commented on src/sentry/projectoptions/defaults.py
> +BETA_GROUPING_CONFIG = "beta:2022-12-20"
I would already name this `newstyle:2022-12-20` so we can just make it stable with that name when we release it.

2022-12-21 08:27 UTC, Swatinem commented
> This makes sense to me but i think we should separate the retirement from the new grouping strategy.

👍🏻 changes this PR so it only includes removal of the setting, thus triggering auto-upgrades to the latest supported version.

2023-02-15 10:19 UTC, mitsuhiko commented
Is it alive

2023-02-15 13:00 UTC, Swatinem commented
I believe the email that was sent out mentioned early march? so we still gotta wait until then?

2023-03-08 11:04 UTC, mitsuhiko approved these changes

2023-03-08 11:24 UTC, merged