Can pass redirect url for after login
getsentry/sentry pull request #4250
Opened 2016-09-30 23:23 UTC by benvinegar

/cc @getsentry/team @dcramer @lewisjellis

2016-09-30 23:28 UTC, dcramer requested changes

2016-09-30 23:28 UTC, dcramer commented on src/sentry/web/frontend/auth_login.py
> +        redirect_next = request.GET.get('next', None)
this needs validation otherwise we'll get stupid security reports about phishing

2016-09-30 23:30 UTC, benvinegar commented on src/sentry/web/frontend/auth_login.py
> +        redirect_next = request.GET.get('next', None)
Take a look at the tests.

There's already validation in `sentry.utils.auth.get_login_redirect`.

2016-09-30 23:31 UTC, dcramer approved these changes
ok fine

2016-09-30 23:35 UTC, dcramer commented
good job at tests

2016-10-03 18:27 UTC, dcramer approved these changes

2016-10-03 18:27 UTC, dcramer commented
im merging this as i need it in another PR

2016-10-03 18:28 UTC, merged