feat: Add Ruby support for auto code mappings
getsentry/sentry pull request #42668
Opened 2022-12-27 17:23 UTC by jangjodi

Fixes WOR-2467

To the best of my knowledge, Ruby is already supported for auto code mappings. This PR just adds tests to confirm this.

This [query](https://sentry.io/organizations/sentry/discover/homepage/?cursor=0%3A0%3A1&field=stacktrace_link.file&field=count%28%29&field=http.referer&field=stacktrace_link.in_app&name=All+Events&project=1&query=transaction%3A%2Fapi%2F0%2Fprojects%2F%7Borganization_slug%7D%2F%7Bproject_slug%7D%2Fstacktrace-link%2F+stacktrace_link.platform%3Aruby&sort=-stacktrace_link.file&statsPeriod=14d&yAxis=count%28%29) shows Ruby stack trace files. They all are straight paths, and can use the [_straight_path_logic function](https://github.com/getsentry/sentry/blob/49f4235cacaa5ef61de7bf05b7a2d8ee6a8aab38/src/sentry/integrations/utils/code_mapping.py#L115) to determine the auto code mapping.

2022-12-27 17:24 UTC, jangjodi commented on tests/sentry/tasks/test_derive_code_mappings.py
> +    def test_derive_code_mappings_rb(self):
Tests derive code mapping for `some/path/test.rb`

2022-12-27 17:25 UTC, jangjodi commented on tests/sentry/tasks/test_derive_code_mappings.py
> +    def test_derive_code_mappings_rake(self):
Tests derive code mapping for `lib/tasks/crontask.rake`

2023-01-03 22:55 UTC, snigdhas approved these changes

2023-01-05 17:03 UTC, armenzg requested changes
It won't start happening until it gets added here:
https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/post_process.py#L610-L612

2023-01-05 17:20 UTC, jangjodi commented
> It won't start happening until it gets added here: https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/post_process.py#L610-L612

Good catch, thank you

2023-01-06 14:41 UTC, armenzg approved these changes
Feel free to merge it.

2023-01-06 16:14 UTC, merged