[search] utilize GroupTagValue.last_seen when filtering results
getsentry/sentry pull request #4272
Opened 2016-10-05 19:34 UTC by dcramer

This improves search behavior around high frequency tags. For example, if you had a tag that was on server name, its likely every issue ever has been seen on that tag value. Because of that, you often wouldn't receive the results you're looking for in more complex filters as the first 1,000 results returned were old/or not matching those filters. This changes it to sort them by the last_seen value, which will generally ensure the results you're expecting are visible.

2016-10-05 19:54 UTC, mattrobenolt commented on src/sentry/south_migrations/0273_auto__del_index_grouptagvalue_project_key_value__add_index_grouptagval.py
> +            db.execute("CREATE INDEX CONCURRENTLY {} ON sentry_messagefiltervalue (project_id, key, value, last_seen)".format(
FYI:

```sql
CREATE INDEX CONCURRENTLY sentry_messagefiltervalue_project_id_6852dd47401b2d7d
ON sentry_messagefiltervalue (project_id, key, value, last_seen);
```

2016-10-05 19:58 UTC, mattrobenolt requested changes
I'm just blocking this so we don't merge, but I've kicked off index creation. Will merge after this is finished and the fake migration is applied in production.

2016-10-14 19:53 UTC, dcramer commented
k updated and ready to merge once we can ignore the migration

2016-10-14 20:07 UTC, mattrobenolt commented
Don't we need `0275` here? `0274` is latest on master.

2016-10-14 20:08 UTC, mattrobenolt commented
Oh, haha, `git rm` the 0273 one. :)

2016-10-14 22:18 UTC, mattrobenolt approved these changes
:fire_engine:

2016-10-19 20:42 UTC, merged