fix(commit-context): Move debounce caching to tasks and set on success only.
getsentry/sentry pull request #43588
Opened 2023-01-24 01:11 UTC by NisanthanNanthakumar

## Objective:

The original cache placement causes the process_commit_context to be only run once every 7 days for a group, regardless of whether the task was able to successfully find a Suspect Committer for that group. I have moved the debounce cache to the individual tasks and set to True only when a Suspect Committer has been found.

2023-01-24 14:26 UTC, armenzg requested changes
Could you please add tests that verify the behaviour of the cache?

2023-01-24 14:26 UTC, armenzg commented on src/sentry/tasks/groupowner.py
> +    group_cache_key = f"w-o-i:g-{group_id}-2"
Since this module and the previous one share the same key, I would have it be a shared variable or function.

2023-01-24 18:23 UTC, wedamija reviewed
I have a feeling we debounce before firing the task to avoid adding a lot of junk to celery. This might be fine, but please keep an eye on the deploy and this queue to make sure there aren't any memory issues.

So does this mean for issues where we can never find a suspect committer that we'll run this logic for every event?

2023-01-25 19:07 UTC, wedamija reviewed
This approach makes sense to me, will leave it up to your team to do a more thorough review

2023-01-25 21:19 UTC, armenzg requested changes
I like your strategy Nisanthan.

There's various comments I left.

Ideally these large functions would be smaller functions to help with comprehension and test-ability.

We can punt it to later but I would like the burden of comprehension to be reduced while this project is still fresh on your mind.

2023-01-25 21:19 UTC, armenzg commented on src/sentry/tasks/post_process.py
> -                group_cache_key = f"w-o-i:g-{event.group_id}"
What's happening in this block of changes?

I see you're moving the blocking starting with `from sentry.utils.committers import get_frame_paths` up here from the else down there.

2023-01-25 21:19 UTC, armenzg commented on tests/sentry/tasks/test_post_process.py
> +        assert cache.has_key(f"process-commit-context-{self.created_event.group_id}")
Good to see testing of the cache.

Should we have a test case for all the other places where we call set key?

If all the various blocks of the large functions were smaller functions we could also assert that a specific function is called.

2023-01-26 20:44 UTC, armenzg approved these changes
I like it! Thanks @NisanthanNanthakumar for addressing my comments!

I only have some more comments for personal understanding.

2023-01-26 20:44 UTC, armenzg commented on src/sentry/tasks/commit_context.py
> +                # We couldn't find the commit in Sentry, so we will debounce the task for 1 day.
Would we want to store the commit when missing?

2023-01-26 21:43 UTC, merged