[WIP] sourcemaps: conditionally import libsourcemap if found
getsentry/sentry pull request #4366
Opened 2016-10-14 19:00 UTC by mattrobenolt

@mitsuhiko

2016-10-14 19:01 UTC, mitsuhiko submitted a review, later dismissed

2016-10-18 07:33 UTC, mitsuhiko requested changes

2016-10-18 07:33 UTC, mitsuhiko commented on src/sentry/testutils/skips.py
> +        del libsourcemap
what's the point in that?

2016-10-18 07:35 UTC, mattrobenolt commented on src/sentry/testutils/skips.py
> +        del libsourcemap
I dunno, being overly conservative. I assume it doesn't matter. I'll remove.

2016-10-18 07:45 UTC, mitsuhiko approved these changes

2016-10-18 18:44 UTC, merged