Use yarn instead of npm
getsentry/sentry pull request #4383
Opened 2016-10-18 15:08 UTC by mitsuhiko

@benvinegar

2016-10-18 16:27 UTC, mattrobenolt commented on Makefile
> +	@hash yarn 2> /dev/null || npm install yarn
Doesn't this need `npm install -g yarn` ?

2016-11-17 22:45 UTC, benvinegar commented on Makefile
> +	@hash yarn 2> /dev/null || npm install yarn
@mitsuhiko ^

2017-01-09 04:13 UTC, benvinegar commented
https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

2017-01-09 05:21 UTC, benvinegar commented
Just the `dist` Travis task is failing now: https://travis-ci.org/getsentry/sentry/jobs/190147193

2017-01-09 05:42 UTC, benvinegar commented
Woot, Travis is green.

2017-01-09 18:46 UTC, mitsuhiko commented
Looking good but since it's my PR i can't sign this off.

2017-01-09 18:52 UTC, benvinegar approved these changes

2017-01-09 18:57 UTC, mattrobenolt requested changes

2017-01-09 18:57 UTC, mattrobenolt commented on package.json
> +    "node-zopfli": "2.0.2",
Remove this. We don't use zopfli anymore.

2017-01-09 19:01 UTC, mattrobenolt approved these changes

2017-01-09 19:36 UTC, merged