add asana to social auth
getsentry/sentry pull request #4452
Opened 2016-10-31 21:23 UTC by macqueen

also starts passing user to `get_config` because we need the user to already have an identity associated for the settings view.

still working on the sentry-plugins bit, but figured i'd get this part up

@getsentry/plugins

2016-10-31 21:25 UTC, dcramer approved these changes

2016-10-31 21:25 UTC, dcramer commented on src/sentry/conf/server.py
> +    'social_auth.backends.asana.AsanaBackend',
you dont need to add this one

2016-11-04 00:40 UTC, mattrobenolt requested changes

2016-11-04 00:40 UTC, mattrobenolt commented on src/social_auth/backends/asana.py
> +                              headers=self.auth_headers()).json()
You need to add in a `response.raise_for_status()` or it'll never error for a non-2xx.

2016-11-04 00:40 UTC, mattrobenolt commented on src/social_auth/backends/asana.py
> +                                 headers=cls.auth_headers())
You probably want a `response.raise_for_status()` here too if this call fails for some reason.

2016-11-04 00:40 UTC, mattrobenolt commented on src/social_auth/backends/asana.py
> +                                headers=headers).json()['data']
`raise_for_status()`

2016-11-09 19:35 UTC, mattrobenolt commented on src/sentry/conf/server.py
> +    'social_auth.backends.asana.AsanaBackend',
@macqueen Can you remove this plz?

2016-11-09 19:35 UTC, mattrobenolt commented on src/sentry/static/sentry/app/components/pluginConfig.jsx
> +            Associate Identity
Translation string?

2016-11-09 19:44 UTC, macqueen commented on src/sentry/conf/server.py
> +    'social_auth.backends.asana.AsanaBackend',
@mattrobenolt it is required. talked to cramer about it in slack, but asana won't work unless it's included here

2016-11-09 19:44 UTC, mattrobenolt commented on src/sentry/conf/server.py
> +    'social_auth.backends.asana.AsanaBackend',
:heart: it.

2016-11-14 19:33 UTC, macqueen commented on src/social_auth/backends/asana.py
> +                                 headers=cls.auth_headers())
done

2016-11-14 19:35 UTC, mattrobenolt approved these changes
:cookie:

2016-11-15 20:51 UTC, merged