feat(issue-owners): Ratelimit issue ownership evaluations
getsentry/sentry pull request #44613
Opened 2023-02-14 18:58 UTC by NisanthanNanthakumar

## Objective:
Customers can create new groups for the same issue and potentially overload the queue. We should set a project-wide ratelimit. The value of the ratelimit is based on the p99 of the current new issue creation per project per min across all orgs.

2023-02-15 17:54 UTC, armenzg requested changes, later dismissed
Please add tests for this. The logic seems to make sense.

2023-02-15 17:54 UTC, armenzg commented on src/sentry/tasks/post_process.py
> +                    ratelimit_key = f"issue_owner_assignment_ratelimit:{project.id}"
If you do not reuse the key in other parts of the code I would place it within `ratelimit_key` and just pass `project.id`.

2023-02-15 17:54 UTC, armenzg commented on src/sentry/tasks/post_process.py
> +):
Could you please a docstring state the purpose?

For instance something like this:
```
Make sure that we do not make more requests than ISSUE_OWNERS_PER_PROJECT_PER_MIN_RATELIMIT at the project level.
```

2023-02-15 17:54 UTC, armenzg commented on src/sentry/tasks/post_process.py
> +        timeout = max(60 - (datetime.now() - window_start).total_seconds(), 0)
If I understand correctly, we would not cache (a timeout of 0) or cache with a timeout of 1 to 59 seconds.

2023-02-15 17:54 UTC, armenzg commented on src/sentry/tasks/post_process.py
> +def should_issue_owners_ratelimit(
I think this could be a generic utility function. Do we have something already in one of our utils modules?

Do we have tests for this?

2023-02-21 21:37 UTC, jangjodi approved these changes

2023-02-21 22:03 UTC, merged