auth: add nonce to user sessions
getsentry/sentry pull request #4466
Opened 2016-11-02 06:38 UTC by mattrobenolt

This nonce is used to invalidate other logged in sessions. If an action
is taken that alters an account's security settings, we take action to
rotate the nonce and forcibly logout all other existing sessions. Right
now, this means when a user changes their password or adds a 2fa method,
we bump the session nonce causing other sessions to need to be
reauthenticated. This also opens the door for exposing a way to just
forcibly logout all sessions if you suspect suspicious activity, but
this isn't exposed through any public API.

@getsentry/security

2016-11-10 23:02 UTC, tkaemming commented on src/sentry/middleware/auth.py
> +            if user.session_nonce and request.session.get('_nonce', '') != user.session_nonce:
Curious: why `_nonce` rather than `nonce`?

2016-11-10 23:02 UTC, tkaemming commented on src/sentry/middleware/auth.py
> -        request.user_from_signed_request = False
Is this assignment actually safe to remove (and is there really a strong argument to remove it?) It looks like there are places elsewhere where it's referenced without `getattr` — but I didn't look too thoroughly.

2016-11-10 23:02 UTC, tkaemming commented on src/sentry/middleware/auth.py
> +                user = AnonymousUser()
It seems like this might be worth logging?

2016-11-10 23:02 UTC, tkaemming commented on src/sentry/web/frontend/accounts.py
>              if form.is_valid():
I didn't see anywhere that the nonce would get set (or reset) for the active session here. `login_user` is `django.contrib.auth.login` — not `sentry.utils.auth.login` — but I might be overlooking something?

2016-11-11 00:22 UTC, mattrobenolt commented on src/sentry/middleware/auth.py
> +            if user.session_nonce and request.session.get('_nonce', '') != user.session_nonce:
Django prefixes some internal keys with _ in similar vein to a "private variable". This is differentiated from a normal session variable that we wouldn't want someone tinkering with accidentally.

2016-11-11 00:22 UTC, mattrobenolt commented on src/sentry/middleware/auth.py
> +                user = AnonymousUser()
Log the attempt to login with an invalid nonce? Yeah, probably.

2016-11-11 00:22 UTC, mattrobenolt commented on src/sentry/middleware/auth.py
> -        request.user_from_signed_request = False
Oh, good eye. I think I just overlooked. I'll add back.

2016-11-11 00:32 UTC, mattrobenolt commented on src/sentry/web/frontend/accounts.py
>              if form.is_valid():
Nah, this is good catch. Worst thing is that the user would have just been redirected back to login. And probably literally never would have noticed. I've bound it to the request explicitly.

2016-11-11 00:44 UTC, tkaemming requested changes

2016-11-11 00:44 UTC, tkaemming commented on src/sentry/middleware/auth.py
> +        request.user_from_signed_request = True
This was previously `False`. Unintentional change?

2016-11-14 19:03 UTC, tkaemming approved these changes
:metal:

2016-11-15 11:00 UTC, merged