api: add the ability to suspend an organization
getsentry/sentry pull request #4554
Opened 2016-11-17 21:00 UTC by mattrobenolt

2016-11-21 00:37 UTC, dcramer requested changes

2016-11-21 00:37 UTC, dcramer commented on src/sentry/models/organization.py
> +        self.flags.suspended = True
would be better if we did an ``update()`` here

2016-11-21 00:37 UTC, dcramer commented on src/sentry/models/organization.py
> +        if 'owner_email' not in kwargs:
this is a bit odd, as if you pass owner_id but not owner_email you'll get a mismatch

I'd probably just have them pass owner, and do the rest from within this logic

2016-11-21 00:37 UTC, dcramer commented on src/sentry/models/suspension.py
> +    added = models.DateTimeField(default=timezone.now)
use ``date_added`` to keep things semi understandable based on the rest of the models

2016-11-21 00:40 UTC, mattrobenolt commented on src/sentry/models/suspension.py
> +    added = models.DateTimeField(default=timezone.now)
Will change.

2017-10-02 19:32 UTC, dcramer commented
Looks like this is not valid anymore, as at some point we added 'suspended' and 'suspension_reason' to the schema (along with basic implementations that bubble up to the user).

2017-10-02 19:32 UTC, closed without merging