ref(snuba): Add referrer_suffix
getsentry/sentry pull request #45854
Opened 2023-03-15 18:31 UTC by MeredithAnya

**context**
When debugging, one way that we can identify where requests are coming from in snuba is by using the `referrer`. This `referrer` is quite helpful when it happens to be the name of an api endpoint, but becomes less helpful when the same referrer covers a lot of different sources. For example, this is the case with the current `tsdb-model:4` referrer 

**referrer_suffix**
I didn't want to change the existing code too much, and I didn't want to change how we use tools to investigate too much. Adding a suffix means we could still search on `tsdb-model:4*` if we wanted/needed to.  

In another PR I will add the specific `referrer_suffix` to places where I think it makes the most sense

2023-03-15 19:41 UTC, untitaker approved these changes

2023-03-15 20:20 UTC, evanh requested changes

2023-03-15 20:44 UTC, rahul-kumar-saini commented on src/sentry/tsdb/snuba.py
> +                referrer += f"{referrer}:{referrer_suffix}"
Suggestion for your suggestion:
`referrer += referrer_suffix`

2023-03-15 23:56 UTC, MeredithAnya commented on src/sentry/tsdb/snuba.py
> +                referrer += f"{referrer}:{referrer_suffix}"
okay I think i want `tsdb-modelid:4.referrer-suffix` so gonna go with `referrer += f".{referrer_suffix}`

2023-03-16 16:15 UTC, evanh approved these changes

2023-03-16 18:35 UTC, merged