ref: Clarify new grouping changes
getsentry/sentry pull request #46121
Opened 2023-03-21 15:49 UTC by cleptric

Follow up of https://github.com/getsentry/sentry/pull/44761

2023-03-21 16:07 UTC, sl0thentr0py requested changes

2023-03-21 16:07 UTC, sl0thentr0py commented on src/sentry/grouping/strategies/configurations.py
> +        * We added new language/platform specific stack trace grouping enhancements rules
```suggestion
        * Added new language/platform specific stack trace grouping enhancements rules
```
to match the grammar of the other entries

2023-03-22 22:01 UTC, cleptric commented
@sl0thentr0py good to go?

2023-03-22 22:09 UTC, sl0thentr0py approved these changes

2023-03-22 22:20 UTC, merged