feat: Add base config for JS loader with performance/replay
getsentry/sentry pull request #46447
Opened 2023-03-28 14:31 UTC by mydea

This PR adjusts the loader to include default config when enabling debug/performance/replay.

## Lazy mode

Lazy mode is only available for errors-only config. Users can manually opt-out of this by adding `data-lazy="no"` to their script tag.

In lazy mode, nothing happens until an error occurs. Once an error occurs, we download the CDN bundle, and then...:

* If `onLoad` is configured, trigger it
* If `SDK.init()` has not been called, call it with defaults

## Eager mode

If either performance or replay is enabled, we are always in eager (non-lazy) mode. In this mode, we'll automatically load the CDN bundle, and then...:

* If `onLoad` is configured, trigger it
* If `SDK.init()` has not been called, call it with defaults

## Defaults

The following default config is defined:

* `dsn`: Always set
* `debug: true` is set when debug bundles are enabled
* `tracesSampleRate: 0.1` is set when performance is enabled
* `replaysSessionSampleRate: 0.1` & `replaysOnErrorSampleRate: 1` are set when replay is enabled
* `integrations`: Will add `Sentry.BrowserTracing` and/or `Sentry.Replay` if performance/replay is enabled

This config can be overwritten by the user, and is merged. So e.g. if they do:

```js
Sentry.onLoad(function() {
  Sentry.init({
    tracesSampleRate: 0.5
  });
});
```

For a full loader build with every option enabled, the actual config will be:

```js
{
  dsn: 'your-dsn',
  debug: true,
  tracesSampleRate: 0.5,
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1,
  integrations: [new Sentry.BrowserTracing(), new Sentry.Replay()]
}
```

Closes https://github.com/getsentry/sentry/issues/46368

2023-03-28 15:11 UTC, AbhiPrasad approved these changes

2023-03-30 14:43 UTC, mydea commented
So I updated this quite a bit:

* Wrote tests in https://github.com/getsentry/sentry-javascript/pull/7662 to actually test that the loader works with different combinations of lazy/products etc - this found some issues that we fixed in both repos 🎉 
* Enforce that when performance or replay is enabled, we use SDK v7. This is also enforced UI-side now:

![image](https://user-images.githubusercontent.com/2411343/228859339-ea86c786-bceb-4cc0-acd3-dda685f279a9.png)

When you switch your SDK version to <7, it automatically removes performance & tracing. This should ensure we do not get into a weird state.

* When Replay is enabled, we show a message that this will result in the ES6 bundle:

![image](https://user-images.githubusercontent.com/2411343/228860629-1a08a126-13bf-403e-8853-507400a2927e.png)

ref https://github.com/getsentry/sentry/issues/46436

2023-03-30 14:45 UTC, mydea commented on static/app/views/settings/project/projectKeys/details/keySettings.tsx
> +                              'When using Replay, the loader will load the ES6 instead of the ES5 bundle.'
Not so sure about the wording here... maybe:

> When using Replay, Sentry is not ES5 compatible.

Or 

> When using Replay, we use the ES6 bundle of Sentry.

2023-03-30 14:50 UTC, AbhiPrasad requested changes
We'll need to merge in the backend changes first - and then do the frontend.

This is still fine since everything is gated behind a feature flag.

2023-03-30 18:13 UTC, AbhiPrasad approved these changes

2023-03-31 06:23 UTC, mydea commented
So I don't _think_ the getsentry test failures are related to this PR...?

2023-03-31 07:03 UTC, HazAT approved these changes
Let's change the tracesSampleRate to `1`. The reason, it's a weird experience if you expect a transaction to show up when testing, but it doesn't.

2023-03-31 07:03 UTC, HazAT commented on src/sentry/web/frontend/js_sdk_loader.py
> +            config["tracesSampleRate"] = 0.1
```suggestion
            config["tracesSampleRate"] = 1
```
Let's change this to `1`

2023-03-31 09:44 UTC, merged