javascript: Improve gzip/deflate artifacts from ReleaseFiles
getsentry/sentry pull request #4677
Opened 2016-12-15 00:30 UTC by mattrobenolt

* Don't gzip files before caching. This is unnecessary because python-memcached will gzip for us. By doing this ourselves, we're actually adding extra work by double gzipping.
* Handle artifacts uploaded as gzip or deflate.

/cc @benvinegar

2016-12-15 00:32 UTC, mitsuhiko requested changes

2016-12-15 00:32 UTC, mitsuhiko commented on tests/sentry/lang/javascript/test_processor.py
> +                'Content-Type': 'application/json; charset=utf-8',
going to be a party pooper but 'application/json' does not accept a charset :P

2016-12-15 00:36 UTC, mitsuhiko approved these changes

2016-12-15 00:36 UTC, mitsuhiko commented
The comment should not require a change to this PR. But we should not do this mistake.

2016-12-15 01:16 UTC, benvinegar commented
‼️

2016-12-15 18:58 UTC, merged

2016-12-15 22:19 UTC, mattrobenolt commented
Had to revert because things slowed down pretty drastically and not clear what the cause is without some investigation.

2017-01-26 13:36 UTC, STRML commented
Is this line in the 8.12 changelog inaccurate, then?

> Allow gziped/deflated JavaScript artifacts to be uploaded through the API.

2017-01-26 16:23 UTC, mattrobenolt commented
Oh. Wups. Yes, this is inaccurate. The code landed, then had to be reverted. I'll fix this up. 

--
Matt Robenolt
@mattrobenolt




On Thu, Jan 26, 2017 at 5:36 AM -0800, "Samuel Reed" <notifications@github.com> wrote:












Is this line in the 8.12 changelog inaccurate, then?



Allow gziped/deflated JavaScript artifacts to be uploaded through the API.




—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-02-14 14:36 UTC, lele85 commented
Any news on that?

2017-04-06 09:46 UTC, deepflame commented
@mattrobenolt is this issue fixed and deployed?

2017-04-06 21:42 UTC, corydolphin commented
Any update? This would be a big improvement for my team, time wise. We have ~30mb of sourcemaps, which is quite slow to upload.

2017-05-24 11:01 UTC, pierreant-p commented
Same here :) (100+ mo of sourcemaps :) )