Also match on release files without query strings
getsentry/sentry pull request #4703
Opened 2016-12-21 12:19 UTC by mitsuhiko

This changes the logic for release file matching so that it will also
try to resolve files without query string.

This is necessary for react-native where all minified files add some
garbage into the query string for the minified file.

2016-12-21 12:20 UTC, mitsuhiko commented
If we want to do this I will add some tests. The alternative is to force people to preprocess all js files to not include those query strings in the references.

2017-01-03 19:39 UTC, mattrobenolt requested changes
Need a CHANGES for this even though Danger didn't say so. This is a worthy change in behavior.

And a test would be nice.

To clarify, this means we'll have now potenitally 4 idents being looked up? Given the input: `http://example.com/?foo`, we'll have the following:

* http://example.com/a.js?foo
* http://example.com/a.js
* ~/a.js?foo
* ~/a.js

2017-01-03 19:39 UTC, mattrobenolt commented on src/sentry/lang/javascript/processor.py
> +        filename_no_query = filename.split('?')[0]
Might as well do `filename.split('?', 1)[0]`

2017-01-03 19:45 UTC, mitsuhiko commented
If we want this behavior I will add tests for it. I was a little bit worried we might have too many requests at this point. One thing I also just realized is that for some clients we appear to accept non urls but filenames so we currently might look up `foo.html` and `~foo.html`. (If I interpret #4718 correctly. Is this the case?)

2017-01-03 19:45 UTC, mitsuhiko commented on src/sentry/lang/javascript/processor.py
> +        filename_no_query = filename.split('?')[0]
Indeed.

2017-01-03 19:47 UTC, mattrobenolt commented
> One thing I also just realized is that for some clients we appear to accept non urls but filenames so we currently might look up foo.html and ~foo.html. (If I interpret #4718 correctly. Is this the case?)

Unsure off hand. I'd need to read this mess of code. 😞

2017-02-10 18:08 UTC, benvinegar commented
Refs #3744

2017-02-10 18:13 UTC, benvinegar commented
Hey folks – how do we revive this PR? Another user has hit this issue [on the forums](https://forum.sentry.io/t/sourcemaps-trouble-getting-them-working-consistently/923).

2017-02-10 18:14 UTC, benvinegar commented
>  I was a little bit worried we might have too many requests at this point.

In cases where we drop the query string, I think these should be artifact lookups solely.

Or put another way: the only HTTP request we make is for the original, full URL we recovered for the frame. For artifacts lookups, we can expand the search space.

2017-02-10 18:26 UTC, mitsuhiko commented
@benvinegar I'm happy if we merge this. The reason we did not end up doing it yet is because `sentry-cli` now writes out sourcemap references with the uploaded .min.js files which also resolves that issue.

2017-02-10 18:26 UTC, mitsuhiko commented
If we end up including this we need to add tests.

2017-07-22 00:25 UTC, benvinegar commented
Boop

2017-08-09 01:08 UTC, mattrobenolt commented
@mitsuhiko I'm gonna take this over and carry it through. Swore this was merged.

2017-08-10 23:29 UTC, mattrobenolt commented
Superseded by #5860

2017-08-10 23:29 UTC, closed without merging