feat(replays): mask archived replays instead of removing them from query
getsentry/sentry pull request #47211
Opened 2023-04-11 23:57 UTC by JoshFerge

- instead of trying to fiter out archived ("deleted") replays from querying, show a masked entry. this will make pagination logic far simpler on our index page, as aggregated rows will match the subquery rows in many cases.
- We can also take this as an opportunity to describe to the user what happened to their replay (the recording is deleted, and metadata is never returned to client)

Screenshot below.
<img width="1466" alt="Screenshot 2023-04-11 at 4 41 22 PM" src="https://user-images.githubusercontent.com/1976777/231313185-9ac87486-4eec-4bb9-9f40-ab47651175fb.png">

2023-04-11 23:57 UTC, JoshFerge commented
useful for https://github.com/getsentry/sentry/pull/46356

2023-04-12 02:52 UTC, JoshFerge commented on tests/sentry/replays/test_organization_replay_index.py
> -    def test_archived_records_not_returned_with_environment_filtered(self):
these two tests don't seem to test any behavior, on master they pass even if archived is set to false

2023-04-12 13:52 UTC, cmanallen requested changes
If we display archived records we should provide a field for the client which explicitly marks them as archived.  They will likely want to add their own decoration.

e.g. `"is_archived": true`

2023-04-12 18:34 UTC, cmanallen approved these changes

2023-04-12 18:52 UTC, merged