[releases] Automatically resolve issues based on fixes notation
getsentry/sentry pull request #4811
Opened 2017-01-23 19:29 UTC by dcramer

2017-01-23 19:30 UTC, dcramer commented
I wanted to see what it'd take, and if there were any holes in schema to achieve this.

The short version is: we'll likely need to change how these notations work, and create something like GroupCommitResolution.

2017-02-05 08:13 UTC, dcramer commented
This doesnt do the auto resolution bits yet, but I think we could get it in without that. It'll be a bit tricky since we have to do some magic around "is it in a release for this environment". This will however let us start capturing the metadata and showing activity entries in the UI.

2017-02-05 08:30 UTC, dcramer commented on src/sentry/event_manager.py
> +                Q(release__date_added__gt=release.date_added) | Q(release=release) | Q(release__isnull=True),
I could back this change out, but its likely what we'll want to do when we know that theres a commit thats pending that will fix the release.

2017-02-05 08:33 UTC, mitsuhiko requested changes

2017-02-05 08:33 UTC, mitsuhiko commented on src/sentry/receivers/releases.py
> +    match = re.search(r'\bFixes ([A-Za-z0-9_-]+-[A-Z0-9]+)\b')
Should probably be set to `(?i)` to make it case insensitive. People often write "This fixes". Also maybe `\s+` instead of a space?

2017-02-05 08:40 UTC, dcramer commented on src/sentry/receivers/releases.py
> +    match = re.search(r'\bFixes ([A-Za-z0-9_-]+-[A-Z0-9]+)\b')
:+1:

2017-02-05 09:23 UTC, dcramer commented
We can improve the activity entry yet, as well as make it link to a commit details page if/when it exists. Main thing thats missing is we should probably show a bit more info than just commit key (e.g. the repo name, or a tooltip with more details).

2017-02-05 10:24 UTC, mitsuhiko approved these changes

2017-02-05 10:51 UTC, dcramer commented on bin/load-mocks
> +            if extra_events:
got tired of this being hella slow

2017-02-10 18:22 UTC, merged