disable danger on builds without token
getsentry/sentry pull request #4843
Opened 2017-01-28 02:49 UTC by graingert

2017-01-28 03:30 UTC, mattrobenolt requested changes

2017-01-28 03:30 UTC, mattrobenolt commented on Makefile
> +	[[ -z "${DANGER_GITHUB_API_TOKEN}" ]] && echo "Skipping danger on PR." || bundle exec danger
This needs to be just single brackets.

```make
travis-test-danger:
	[ -z "${DANGER_GITHUB_API_TOKEN}" ] && echo "Skipping danger on PR." || bundle exec danger
```

and in theory this is fine. The syntax you used doesn't work on Linux it seems.

2017-01-28 03:32 UTC, mattrobenolt commented
Alternatively, I'm not entirely sure how bad of an idea it'd be to just allow Danger to run on pull requests from outside contributors. Rather, unclear off hand what someone could do with the API key we are using.

2017-01-28 03:47 UTC, graingert commented
Looks like they recommend making it available: http://danger.systems/guides/getting_started.html

2017-03-21 04:43 UTC, mattrobenolt commented
I have fixed this by using a public key now. <3

2017-03-21 04:43 UTC, closed without merging