feat(sdk-crash-detection): Call code in post processing
getsentry/sentry pull request #49170
Opened 2023-05-16 08:45 UTC by philipphofmann

## If you are not @getsentry/ingest you can skip this PR.

Merging master into feature branches accidentally requested a review from almost all teams at Sentry. I'm sorry about this.

## PR Details

Call SDK crash detection code in post-processing. I had to adapt the code a bit, cause I tested it with a dictionary instead of a stored event. I adapted the tests to use the same approach as the post-processing tests. The logic of the tests didn't change. I refactored all of them to work with stored events. 

The next step is to store the SDK crash event to a specific sentry project with https://github.com/getsentry/sentry/issues/46177

I wasn't able to get parameterized tests working with test mixin approach. Does anybody know if that's possible?

Fixes GH-46175

2023-05-26 11:29 UTC, jjbayer requested changes
> I wasn't able to get parameterized tests working with test mixin approach. Does anybody know if that's possible?

`pytest.mark.parametrize` does not work in combination with `unittest.TestCase`, unfortunately: https://github.com/pytest-dev/pytest/issues/541

Why are you moving from standalone (pytest) functions to class-based tests, if I may ask?

2023-05-30 08:35 UTC, philipphofmann commented on src/sentry/utils/sdk_crashes/sdk_crash_detection.py
> +        if should_detect_sdk_crash is False:
Uh, nice. I am still getting used to Python. Thanks 👍

2023-05-30 08:37 UTC, philipphofmann commented on src/sentry/utils/sdk_crashes/sdk_crash_detection.py
> +sdk_crash_detection = SDKCrashDetection(_crash_reporter, _cocoa_sdk_crash_detector, _event_stripper)
Yes, that makes sense. Old object-oriented habits. Thanks for pointing it out. You don't need a class for everything.

2023-05-30 08:47 UTC, philipphofmann commented on src/sentry/utils/sdk_crashes/event_stripper.py
> +            new_event_data["debug_meta"]["images"] = stripped_debug_meta_images
I thought Sentry maybe needed it to display the event properly. If you say everything works fine without the dSYMs, I'm happy to drop them.

2023-05-30 08:55 UTC, philipphofmann commented on src/sentry/utils/sdk_crashes/event_stripper.py
> +        return event
I fully agree. To keep the scope of this PR small, I created another issue to fix this https://github.com/getsentry/sentry/issues/49935 in another PR. Are you okay with that, @jjbayer?

2023-05-30 09:36 UTC, philipphofmann commented
> Why are you moving from standalone (pytest) functions to class-based tests, if I may ask?

So I can apply the same approach for creating an event in `test_post_process`. I didn't manage to use the same approach with functions, @jjbayer.

2023-05-30 12:24 UTC, jjbayer commented
> > Why are you moving from standalone (pytest) functions to class-based tests, if I may ask?
> 
> So I can apply the same approach for creating an event in `test_post_process`. I didn't manage to use the same approach with functions, @jjbayer.

Yeah so AFAIK you have to chose between using either `@pytest.mark.parametrize` or class-based testing with manual parameterization, whichever you prefer.

2023-05-30 12:24 UTC, jjbayer approved these changes

2023-05-30 13:08 UTC, merged

2023-05-31 13:39 UTC, asottile-sentry commented
> > > Why are you moving from standalone (pytest) functions to class-based tests, if I may ask?
> > 
> > 
> > So I can apply the same approach for creating an event in `test_post_process`. I didn't manage to use the same approach with functions, @jjbayer.
> 
> Yeah so AFAIK you have to chose between using either `@pytest.mark.parametrize` or class-based testing with manual parameterization, whichever you prefer.

of note, `TestCase` and class based tests are soft deprecated -- please try and write function tests moving forward (pytest has already begun to remove / unsupport functionality there over time -- the compat layer is only meant as a migration helper)

2023-05-31 14:50 UTC, philipphofmann commented
Thanks for pointing that out, @asottile-sentry. I created an issue to change the tests to function tests https://github.com/getsentry/sentry/issues/50061.