Weaken release version regex
getsentry/sentry pull request #4927
Opened 2017-02-17 10:07 UTC by HazAT

For iOS we should support build numbers for Releases which look basically like this ...

`1.2.3 (1337)`

So there is a short version string `1.2.3`
And a build number `1337` 
which uniquely identify a release.

This PR softens the regex in order to allow a POST with this string.

2017-02-27 13:22 UTC, mitsuhiko commented on src/sentry/api/endpoints/project_releases.py
> -        if not set(value).isdisjoint(set(string.whitespace)):
I'm confuse. What was this line supposed to do?

2017-02-27 13:22 UTC, mitsuhiko commented
FWIW this PR looks good but i don't quite get what it did before.

2017-02-27 14:23 UTC, HazAT commented on src/sentry/api/endpoints/project_releases.py
> -        if not set(value).isdisjoint(set(string.whitespace)):
I am not sure what you mean ... But it was a strange way to detect if there is a `string.whitespace` in the `value` var.

2017-02-27 17:50 UTC, HazAT commented
So mergeable?

2017-02-27 17:56 UTC, mitsuhiko approved these changes

2017-02-27 17:57 UTC, mitsuhiko requested changes
Actually just realized: why do we need validate_version to do another regex check at all?

2017-02-27 18:09 UTC, HazAT commented
@mitsuhiko At least the test fails if `validate_version` is not there.

2017-02-27 18:11 UTC, mitsuhiko commented
I just wanted to ask the original author but it was an external contribution: https://github.com/getsentry/sentry/commit/657a444e032c5d10da5458a14fdef825889d28c3

2017-03-01 19:37 UTC, mitsuhiko approved these changes

2017-03-01 22:28 UTC, merged