fix(stats): include abuse outcomes in total dropped
getsentry/sentry pull request #49437
Opened 2023-05-18 21:13 UTC by cathteng

It has been reported many times that the numbers on the stats page don't line up. Support has done some digging and it appears that this is due to abuse outcomes not being included in the total count of dropped events. This has been fixed here.

2023-05-18 23:10 UTC, leedongwei approved these changes

2023-05-19 16:28 UTC, nhsiehgit requested changes
going to block on this until we have a clear outcome from product 😬

2023-06-05 17:55 UTC, Dhrumil-Sentry commented
Let's discuss this a bit more before we merge any changes here

2023-09-11 18:25 UTC, JoshFerge commented
what did we end up deciding here?

2023-09-13 17:41 UTC, cathteng commented
@JoshFerge i can follow up

2023-09-13 17:46 UTC, cathteng commented
parking this for now

2023-09-13 17:46 UTC, closed without merging