riccardo/fix/fix deduplication
getsentry/sentry pull request #49677
Opened 2023-05-24 12:06 UTC by iambriccardo

- fix(sourcemaps): Deduplicate bundles by considering release and dist
- Update deduplication logic

2023-05-24 13:58 UTC, mitsuhiko requested changes

2023-05-24 13:58 UTC, mitsuhiko commented on src/sentry/tasks/assemble.py
> +            artifact_bundle = ArtifactBundle.objects.create(
This code path can create duplicates. We still need to have a logic in place to actually get rid of the unintended duplicates.

2023-05-31 10:18 UTC, Swatinem commented on src/sentry/tasks/assemble.py
> +        existing_file.delete()
I believe files should also be deduped by their checksum, no? Maybe we should check that edge-case here to make sure that `existing_artifact_bundle.file != archive_file`?

2023-05-31 10:18 UTC, Swatinem commented on src/sentry/api/endpoints/artifact_bundles.py
> +                            # If there are more than one project, we will just delete ProjectArtifactBundle entry
```suggestion
                            # If there is more than one project, we will just delete the ProjectArtifactBundle entry
```

2023-05-31 13:09 UTC, Swatinem approved these changes

2023-05-31 13:31 UTC, mitsuhiko approved these changes

2023-06-12 12:03 UTC, merged