Adding 'discover' command to 'config'
getsentry/sentry pull request #4974
Opened 2017-02-23 15:06 UTC by joedborg

…to see where config files have been placed.  Added .idea/ directory to .gitignore to allow development under IDEA based IDEs.

Following from https://github.com/getsentry/sentry/pull/4965

2017-02-23 15:06 UTC, joedborg commented
@mattrobenolt

2017-02-24 16:35 UTC, mattrobenolt requested changes
After those minor things, will merge. <3

2017-02-24 16:35 UTC, mattrobenolt commented on src/sentry/runner/commands/config.py
> +    print(py)
Need to use `click.echo` here instead or linter will yell.

2017-02-24 16:35 UTC, mattrobenolt commented on src/sentry/runner/commands/config.py
> +    directory, py, yaml = discover_configs()
And this will lead to an unused variable. So just:

```python
_, py, yaml = discover_configs()
```

would be sufficient

2017-02-24 16:35 UTC, mattrobenolt commented on src/sentry/runner/commands/config.py
> +@configuration
This isn't needed for this command, so it can just be removed.

2017-02-24 16:43 UTC, joedborg commented on src/sentry/runner/commands/config.py
> +@configuration
I guess you mean the `@configuration` decorator?  Removing this is fine, but removing `@config.command()` means the runner doesn't pick it up.

2017-02-24 16:45 UTC, joedborg commented
Done, unless you'd prefer the commits squashed?

2017-02-24 16:46 UTC, mattrobenolt commented on src/sentry/runner/commands/config.py
> +@configuration
That's exactly what I meant. :)

2017-02-24 16:46 UTC, mattrobenolt approved these changes

2017-02-24 16:47 UTC, merged