changing support logo to question mark
getsentry/sentry pull request #4984
Opened 2017-02-23 22:34 UTC by ehfeng

![image](https://cloud.githubusercontent.com/assets/279398/23282252/3873a420-f9d5-11e6-9c86-e8b4367d2b46.png)

2017-02-23 23:36 UTC, ckj requested changes
I'm plus one for making this change, but I want to approach it differently. Our icon font generation process will overwrite this part of fonts.less (my bad for not noting that anywhere in the file.) Also, ideally the question mark itself would be part of the icon font set. I'll set aside some time today or tomorrow to document how we generate these, as well as add this icon to the set. 

Sorry for making this harder than it should be :(

2017-02-23 23:43 UTC, ehfeng commented
No problem @ckj. I'm at fault for jumping the gun on this. I appreciate the "doing it right" approach.

2017-02-24 22:51 UTC, ckj approved these changes

2017-02-24 22:51 UTC, ckj commented
I updated the icon set with the new icon -- should be good to go now.

2017-03-02 18:00 UTC, merged