[quotas] support soft-quotas (unenforced)
getsentry/sentry pull request #5081
Opened 2017-03-15 19:44 UTC by dcramer

This adds a flag to RedisQuota (``enforce``) which can be used to track soft quotas, which are not always enforced but are always counted.

2017-03-15 19:45 UTC, dcramer commented
I'm open to another name for this, but this will allow us to easily have a daily quota as a soft limit (e.g. with on-demand spend).

2017-03-15 22:03 UTC, tkaemming requested changes

2017-03-15 22:03 UTC, tkaemming commented on src/sentry/quotas/redis.py
> +                if not quota.enforce:
If both Quota A and Quota B are rejected but only Quota B is *not* enforced, doesn't this mean that the rate limit check will return *not* rate limited even though Quota A *should* be enforced? Is this intentional?

2017-03-15 22:14 UTC, dcramer commented on src/sentry/quotas/redis.py
> +                if not quota.enforce:
good point -- ill invert the logic

2017-03-15 23:15 UTC, tkaemming requested changes

2017-03-15 23:15 UTC, tkaemming commented on src/sentry/quotas/redis.py
> +                    continue
I don't think this `continue` statement is necessary, since it prevents the `worst_case` values from being set when the quota is actually enforced.

2017-03-15 23:36 UTC, dcramer commented on src/sentry/quotas/redis.py
> +                    continue
derp yeah -- i wrote some tests but they were failing

2017-03-16 00:02 UTC, tkaemming requested changes

2017-03-16 00:02 UTC, tkaemming commented on src/sentry/quotas/redis.py
>                  delay = get_next_period_start(quota.window) - timestamp
In my opinion it'd make more sense to just move [L113-115](https://github.com/getsentry/sentry/blob/908150b9dde8f20412168482a5699c5e588be79f/src/sentry/quotas/redis.py#L113-L115) into the `if` block to obviate the need for the `continue` statement. (Up to you if you'd like to make this change or not — I'm not going to block on it.)

2017-03-16 00:02 UTC, tkaemming commented on tests/sentry/quotas/redis/tests.py
> +        assert self.quota.is_rate_limited(self.project).is_limited
What? One of these is definitely going to fail unless something really weird is going on here.

2017-03-16 17:24 UTC, dcramer commented
ok for real i think this is good now

2017-03-16 18:34 UTC, tkaemming approved these changes
:3rd_place_medal:

2017-03-16 18:38 UTC, merged