ref(email): Add unsubscribe link to metric alert emails
getsentry/sentry pull request #51417
Opened 2023-06-21 22:54 UTC by ceorourke

Adds an unsubscribe button to metric alert emails in the same way we have them for issue alerts and digests.

2023-06-21 22:55 UTC, ceorourke commented
I'm not sure if there was a reason we didn't have this already.

2023-06-21 23:16 UTC, scttcper approved these changes
10/10

2023-06-21 23:23 UTC, scttcper requested changes
can't unsubscribe from metric alerts

2023-06-22 00:03 UTC, ceorourke commented
oops use https://github.com/getsentry/sentry/pull/51425 instead

2023-06-22 00:03 UTC, closed without merging