List files by repository
getsentry/sentry pull request #5143
Opened 2017-03-24 00:41 UTC by kjlundsgaard

Separates the files in Files Changed list for the Release Overview tab by their respective repositories

Now looks more like:
![screen shot 2017-03-23 at 5 33 23 pm](https://cloud.githubusercontent.com/assets/9269824/24275766/24322b00-0fef-11e7-93df-158b3e9a7691.png)

Design suggestions welcome/appreciated.
@ckj @jess @MaxBittker @benvinegar 

#nochanges

2017-03-24 00:49 UTC, mattrobenolt commented on src/sentry/api/serializers/models/filechange.py
> +        repositories = Repository.objects.filter(id__in=[commit.repository_id for commit in commits])
This can be shorted to just:

```python
repo_names_by_id = dict(Repository.objects.filter(id__in=[..]).values_list('id', 'name'))
```

2017-03-24 00:49 UTC, mattrobenolt commented on src/sentry/api/serializers/models/filechange.py
> +                'repository_name': repo_names_by_id[commit.repository_id]
I'd probably guard against a missing key here.

```python
repo_names_by_id.get(commit.repository_id)
```

I'm not entirely sure if this case will be hit, but there's no reason it couldn't happen. There isn't a foreign key link here, so it's possible they can become decoupled.

2017-03-24 01:22 UTC, ckj commented
😍

2017-03-24 20:25 UTC, macqueen requested changes

2017-03-24 20:25 UTC, macqueen commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      let {id, authors, types} = fileChangeSummary[filename];
i'd indent this block to make it more obvious it's the function being passed to map

2017-03-24 20:25 UTC, macqueen commented on src/sentry/api/serializers/models/filechange.py
> +        repo_names_by_id = dict(Repository.objects.filter(id__in=[commit.repository_id for commit in commits]).values_list('id', 'name'))
not necessary to change, but for long lines like this, i think we try to do something like:
```python
repo_names_by_id = dict(Repository.objects.filter(
    id__in=[commit.repository_id for commit in commits],
).values_list('id', 'name'))
```
to make it more readable

2017-03-24 20:25 UTC, macqueen commented on src/sentry/api/serializers/models/filechange.py
>          commits = Commit.objects.filter(id__in=[f.commit_id for f in item_list]).select_related('author')
so i think based on the [django docs](https://docs.djangoproject.com/en/1.7/ref/models/querysets/):
> Iteration. A QuerySet is iterable, and it executes its database query the first time you iterate over it.

your use of commits twice shouldn't execute two queries. But from talking to matt, it seems like it's probably just better to be explicit and coerce to a list so it's more obvious it's only one query. do you mind changing this to `commits = list(...`?

2017-03-24 20:25 UTC, macqueen commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      <h6>{fileCount} {fileCount !== 1 ? t('files ') : t('file ')} {t('changed in ')} {repository}</h6>
let's bug armin and see if this should use `tn` or not

2017-03-27 19:15 UTC, kjlundsgaard commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      <a onClick={props.onClick}>Show {props.count} collapsed files</a>
fixed

2017-03-27 19:15 UTC, kjlundsgaard commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      <h6>{fileCount} {fileCount !== 1 ? t('files ') : t('file ')} {t('changed in ')} {repository}</h6>
changed

2017-03-27 19:15 UTC, kjlundsgaard commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      let {id, authors, types} = fileChangeSummary[filename];
changed

2017-03-27 19:15 UTC, kjlundsgaard commented on src/sentry/api/serializers/models/filechange.py
>          commits = Commit.objects.filter(id__in=[f.commit_id for f in item_list]).select_related('author')
updated

2017-03-27 19:16 UTC, kjlundsgaard commented on src/sentry/api/serializers/models/filechange.py
> +        repo_names_by_id = dict(Repository.objects.filter(id__in=[commit.repository_id for commit in commits]).values_list('id', 'name'))
changed

2017-03-27 23:44 UTC, macqueen approved these changes
left a couple little comments, but otherwise 👍

2017-03-27 23:44 UTC, macqueen commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +        {fileCount} {tn((' file changed in ' + repository), (' files changed in ' + repository), fileCount)}
same here, i think this can just be
`{tn(('%d file changed in ' + repository), ('%d files changed in ' + repository), fileCount)}`

2017-03-27 23:44 UTC, macqueen commented on src/sentry/static/sentry/app/components/repositoryFileSummary.jsx
> +      <a onClick={props.onClick}>{tn(('Show ' + props.count + ' collapsed file'), ('Show ' + props.count + ' collapsed files'), props.count)}</a>
i think you can just do:
`<a onClick={props.onClick}>{tn(('Show %d collapsed file'), ('Show %d collapsed files'), props.count)}</a>`
can't you?

2017-03-28 01:59 UTC, merged