Use gray and italicized text for system frames
getsentry/sentry pull request #51758
Opened 2023-06-27 22:47 UTC by 17hogeju

Closes https://github.com/getsentry/sentry/issues/50691 and https://github.com/getsentry/sentry/issues/50693

Distinguishes "In App" and "System" frames using gray/italicized text with no pill for "System".

Before and After Gray/Italicization
<img width="799" alt="Screenshot 2023-06-27 at 3 40 52 PM" src="https://github.com/getsentry/sentry/assets/22582037/21743168-3f1c-4099-9199-2bf47118a0af">
<img width="799" alt="Screenshot 2023-06-27 at 3 41 20 PM" src="https://github.com/getsentry/sentry/assets/22582037/34b90ba5-1988-4dc0-9a3d-1889e1300385">

2023-06-29 18:43 UTC, scttcper approved these changes

2023-06-29 19:45 UTC, malwilley commented on static/app/components/events/interfaces/nativeFrame.tsx
> +  color: ${p => (p.isSystemLabel ? p.theme.subText : 'default')};
Is `default` a valid color/font-style? I think you want to only apply these styles conditionally, like:

```ts
${p => p.isSystemLabel
 ?  css`
      color: ${p.theme.subText};
	  font-style: 'italic';
     ` 
  : ''
```

2023-06-29 23:25 UTC, 17hogeju commented
One thing I noticed is that when italics are used for Native Stacktrace, the location text gets cut off a little
![Screenshot 2023-06-29 at 4 24 22 PM](https://github.com/getsentry/sentry/assets/22582037/53861fb1-e2da-407b-a58a-be1beca72b14)

2023-06-30 16:52 UTC, malwilley commented
> One thing I noticed is that when italics are used for Native Stacktrace, the location text gets cut off a little
 
@17hogeju ah good catch. We do want to fix that before merging. This is happending because the containing element has `overflow: hidden` (which we use to prevent overflow and apply the ellipsis for long lib names) and it a bit too small. You'll want to find a solution where the containing element takes up the full space, or maybe even some padding might help. LMK if you need help finding the right solution.

2023-07-13 17:46 UTC, malwilley requested changes
Need to put this behind a feature flag, requesting changes so we don't accidentally merge

2023-07-18 18:59 UTC, malwilley approved these changes
Great work!

2023-07-18 19:01 UTC, merged