feat(doc): Update health-check inbound filter API documentation
getsentry/sentry pull request #52008
Opened 2023-06-30 15:45 UTC by RaduW

Update API documentation for inbound filters to contain the health-check filter

2023-06-30 17:44 UTC, sentaur-athena approved these changes

2023-06-30 19:29 UTC, schew2381 requested changes

2023-06-30 19:29 UTC, schew2381 commented on src/sentry/apidocs/parameters.py
> +- `filtered-transaction`: Filter out transactions for healthcheck and ping endpoints.
How is filtered-transactions toggled? If it's done using the `active` query param, you must add it to the [active strin explanation](https://github.com/getsentry/sentry/blob/master/src/sentry/apidocs/parameters.py#L248). Also this filter appears to be set behind a feature flag so is it available to all users by default?

<img width="551" alt="Screenshot 2023-06-30 at 12 25 06 PM" src="https://github.com/getsentry/sentry/assets/67301797/7abf8a69-037d-497a-9cfe-42d090925c68">

2023-07-05 17:13 UTC, schew2381 approved these changes

2023-07-06 07:18 UTC, merged