chore: Prevent committing to master
getsentry/sentry pull request #52089
Opened 2023-07-03 09:45 UTC by philipphofmann

Prevent committing to master via pre-commit hook.

There is no proper reason to commit to master, as we don't allow pushing to master. Sometimes you may commit to master by accident. Then you, anyways, have to create a new branch and then reset master again.

2023-07-03 11:24 UTC, evanpurkhiser commented
Fwiw (and I am probably largely in the minority here) but I **only** commit to master, my workflow is to just commit straight to master, and I use a tool to automatically rebase commits to the tip of `origin/master` and then push those to an autogenerated branch name on the remote. I don't use branches locally.

That said I have pre-commit disabled, so this is fine for me lol

2023-07-03 13:07 UTC, philipphofmann commented
@evanpurkhiser, that's an interesting workflow. I'm also OK with closing this PR again. Which tool do you use?

2023-07-06 08:28 UTC, philipphofmann commented
@asottile-sentry, it's not about pushing to master but committing locally to master.

2023-07-06 12:51 UTC, asottile-sentry requested changes
(mostly to prevent auto-merge)

committing to the branch isn't what's dangerous -- it's pushing over the master branch.  accidentally committing to `master` is fine -- you can always `git branch -m my-feature-branch` and go on with your day

2023-07-06 13:02 UTC, closed without merging