fix(dynamic-sampling): Add query timeout logging for more functions
getsentry/sentry pull request #52268
Opened 2023-07-05 14:50 UTC by iambriccardo

This PR adds more timeouts loggers and increases the time for execution of org recalibration.

2023-07-05 15:06 UTC, RaduW requested changes
Need to move the:
```
else: 
    log_query_timeout(...)
```

blocks to their proper place

2023-07-05 15:06 UTC, RaduW commented on src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
> +        log_query_timeout(query="get_orgs_with_project_counts", offset=offset)
Wrong place of the log ( it should be one block higher)

2023-07-05 15:06 UTC, RaduW commented on src/sentry/dynamic_sampling/tasks/common.py
> +        log_query_timeout(query="get_active_orgs_with_projects_counts", offset=offset)
also wrong place :-) ( one block up)

2023-07-06 06:28 UTC, iambriccardo commented on src/sentry/dynamic_sampling/tasks/common.py
> +        log_query_timeout(query="get_active_orgs_with_projects_counts", offset=offset)
Talking about why brackets are better than tabs 🤣

2023-07-06 07:21 UTC, RaduW approved these changes
Good to go

2023-07-06 07:22 UTC, merged