fix(django_admin): Disable django_admin on prod
getsentry/sentry pull request #52329
Opened 2023-07-06 04:54 UTC by klboke

Disable django_admin on prod ，fix #23742 , https://github.com/getsentry/self-hosted/issues/1039

cc @BYK 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2023-07-06 04:58 UTC, klboke commented
fix https://github.com/getsentry/self-hosted/issues/1922  cc @hubertdeng123

2023-07-06 10:02 UTC, BYK requested changes
Lol, was that it? 😅 

Can we have a smoke test somewhere so we know for sure it is fixed and will stay that way?

2023-07-06 18:58 UTC, hubertdeng123 commented
/gcbrun

2023-07-06 22:49 UTC, hubertdeng123 commented
> Lol, was that it? 😅

Seems to work, just tested this locally. Thanks @klboke

2023-07-07 20:50 UTC, hubertdeng123 approved these changes
> Can we have a smoke test somewhere so we know for sure it is fixed and will stay that way?

I think this is a nice thing to have but don't think we should block on this.

2023-07-07 21:01 UTC, chadwhitacre commented
Let's get a review from the backend team as well.

2023-07-10 14:40 UTC, markstory approved these changes

2023-07-10 14:47 UTC, dashed approved these changes

2023-07-10 16:38 UTC, merged