add external_id column to CommitAuthor
getsentry/sentry pull request #5257
Opened 2017-04-18 22:56 UTC by macqueen

2017-04-19 00:56 UTC, macqueen commented on CHANGES
> +Version 8.15
nooo fu rebasing

2017-04-19 01:10 UTC, mattrobenolt requested changes

2017-04-19 01:10 UTC, mattrobenolt commented on src/sentry/models/commitauthor.py
> +    external_id = models.CharField(max_length=164, null=True, db_index=True)
We don't need `db_index` here. This will create an extra index that we don't need. The `UNIQUE` is enough.

2017-04-20 20:22 UTC, mattrobenolt approved these changes
🥇

2017-04-20 20:25 UTC, merged