feat(github-growth): replace delete repo with hide repo on config page
getsentry/sentry pull request #53024
Opened 2023-07-17 23:42 UTC by cathteng

Instead of deleting a repo, clicking the trash icon will now set the repo status to `HIDDEN`.

Requires #53018 in order to maintain the behavior of cascading deletions now that we are hiding the repo instead of fully deleting it.

2023-07-20 16:44 UTC, scefali requested changes
@cathteng I believe this will cause some bad states because we have uniqueness constraints on the repo that cause bugs that occasionally have to be fixed by deleting a repo for another integration: https://github.com/getsentry/sentry/blob/master/src/sentry/models/repository.py#L41

I think if we changed the uniqueness constraints then we can hide repos but we have to fix that first

2023-07-20 18:17 UTC, scttcper commented on static/app/actionCreators/integrations.tsx
> + * @param {String} repositoryId Repository ID
```suggestion
 * @param client ApiClient
 * @param orgId Organization Slug
 * @param repositoryId Repository ID
```
types conflict with the typescript types

2023-07-24 18:40 UTC, cathteng commented
@scefali two follow up PRs were merged -- #53286 and #53307

2023-07-24 18:40 UTC, scefali approved these changes

2023-07-24 19:02 UTC, merged