unset neutral settings and change camelcase
getsentry/sentry pull request #5332
Opened 2017-05-03 00:06 UTC by MaxBittker

committed_deploys_only is the default setting, and so instead of ever saving it, it's better to unset. this means I had to change unset_value to be kwargs to also accept organization.  Also, while i was here, i fixed the broadcast capitalization

2017-05-03 00:13 UTC, mattrobenolt requested changes

2017-05-03 00:13 UTC, mattrobenolt commented on src/sentry/models/useroption.py
> +    def unset_value(self, user, key, **kwargs):
Definitely need a test for this behavior.

2017-05-03 15:27 UTC, mattrobenolt requested changes
plz run your code before committing next time

2017-05-04 04:16 UTC, mattrobenolt commented on tests/sentry/models/test_useroption.py
> +        )
You should add an assert here to make sure that the `set_value` worked correctly.

2017-05-05 06:27 UTC, MaxBittker commented
might remove the code logic changes and just commit some form of this test

2017-10-18 20:39 UTC, closed without merging