fix unicode release versions in pagination fixes SENTRY-39H
getsentry/sentry pull request #5338
Opened 2017-05-03 22:39 UTC by macqueen

2017-05-03 23:01 UTC, dcramer commented
I'm going to defer to matt or armin on this one

2017-05-03 23:36 UTC, mattrobenolt requested changes
Since this is touching all API endpoints, would it be super hard to construct a test for the `Link` header to exercise this issue?

2017-05-03 23:36 UTC, mattrobenolt commented on tests/sentry/api/endpoints/test_release_deploys.py
> +            version='1–0',
fwiw, instead of using the `# -*- coding` thing, you could use the escaped format here: `u'1\u20130'`.

2017-05-08 20:02 UTC, mattrobenolt approved these changes

2017-05-08 20:29 UTC, merged