Localhost filter includes url
getsentry/sentry pull request #5339
Opened 2017-05-03 23:57 UTC by MeredithAnya

Basically copypasta from #4762 
Fixes #4800 

@mattrobenolt

2017-05-04 00:12 UTC, mattrobenolt requested changes
We need to also have tests that cover the 127.0.0.1 case, as well as tests that cover the missing key path.

I also want to re-iterate that this will never solve the actual problem and this is still quite hacky solution. Granted, there isn't much better we can do. But we should communicate this in the product so set expectations.

2017-05-04 00:12 UTC, mattrobenolt commented on src/sentry/filters/localhost.py
> +        matchObj = DOMAIN_FROM_URL.match(self.get_url(data))
I'd rather we not use a regular expression here, and instead use `urlparse`

2017-05-04 00:12 UTC, mattrobenolt commented on src/sentry/filters/localhost.py
> +            http = data['sentry.interfaces.Http']
I'd simplify this to just `return data['sentry.interfaces.Http']['url']`

2017-05-04 00:12 UTC, mattrobenolt commented on tests/sentry/filters/test_localhost.py
> +        data = self.get_mock_data(url='http://localhost?domain_in_args=example.com')
This test is bad since it's not a valid url.

2017-05-23 22:10 UTC, MeredithAnya commented
this probs needs more tests but wanted to address the other changes since its been some time

2017-05-31 23:52 UTC, mattrobenolt approved these changes

2017-06-01 18:14 UTC, merged