delete repos without commits immediately, reduce delay to an hour for others
getsentry/sentry pull request #5352
Opened 2017-05-05 20:51 UTC by macqueen

cc @MeredithAnya

2017-05-05 20:53 UTC, macqueen commented on src/sentry/api/endpoints/organization_repository_details.py
> +            repo.get_provider().delete_repository(
should this still be async? we need to make a request to github api, so it might be better to keep this async...

2017-05-05 20:56 UTC, mattrobenolt requested changes

2017-05-05 20:56 UTC, mattrobenolt commented on src/sentry/api/endpoints/organization_repository_details.py
> +            repo.get_provider().delete_repository(
I should have clarified. I wouldn't change this behavior. I'd just fire the celery task with no delay instead of the 86400 countdown.

2017-05-05 21:03 UTC, macqueen commented on src/sentry/api/endpoints/organization_repository_details.py
> +            repo.get_provider().delete_repository(
k .. yeah kind of though about that as i was putting pr up lol :) easy to fix though

2017-05-06 00:44 UTC, mattrobenolt approved these changes

2017-05-08 19:57 UTC, merged