Fixing "notification integration" onboarding task
getsentry/sentry pull request #5397
Opened 2017-05-15 23:40 UTC by ehfeng

Fixing notification on-boarding task to adjust for jess' migration to sentry-plugins for Slack, and other notification integrations

2017-05-15 23:57 UTC, macqueen requested changes
This shouldn't be necessary because of https://github.com/getsentry/sentry/blob/master/src/sentry/plugins/__init__.py. What are you trying to fix?

2017-05-17 01:18 UTC, macqueen reviewed
i assume this relates to the `This will play into on-boarding later.`, but is there a reason you're not adding the onboarding task right now? i guess i'm just wondering why the signal is useful without anything listening to it

2017-05-18 16:00 UTC, ehfeng commented on src/sentry/models/rule.py
> +        alert_rule_created.send(project=self.project, rule=self, sender=Rule)
Good point. I'll move it there.

2017-05-18 16:04 UTC, ehfeng commented on src/sentry/receivers/rules.py
> +DEFAULT_RULE_LABEL = 'Send a notification for new events'
I'm using this in getsentry to ignore the first signal created by the default rule.

2017-05-18 20:32 UTC, ehfeng commented
I'll have receivers within the `getsentry` codebase to track as organizations use a feature for the first time. The pattern is very similar to the OrganizationOnboardingTask model.

2017-05-26 22:48 UTC, macqueen approved these changes
✨

2017-05-26 22:50 UTC, merged