feat(perf): Set default values for perf detection to 1.0
getsentry/sentry pull request #53985
Opened 2023-08-01 21:36 UTC by udameli

Set defaults to `1.0` so all detectors and general perf-issue detection options are enabled by default. That way detection will work for s4s and self-hosted.

2023-08-01 21:37 UTC, narsaynorath approved these changes

2023-08-01 21:39 UTC, narsaynorath requested changes

2023-08-01 21:39 UTC, narsaynorath commented on src/sentry/options/defaults.py
> +    default=1.0,
Actually, I don't think one has been released yet!

2023-08-01 21:50 UTC, udameli commented on src/sentry/options/defaults.py
> +    default=1.0,
oh oops!

2023-08-01 21:50 UTC, udameli commented on src/sentry/options/defaults.py
> +    default=1.0,
fixed! good catch

2023-08-02 15:10 UTC, wedamija approved these changes

2023-08-02 16:21 UTC, narsaynorath approved these changes

2023-08-02 17:27 UTC, merged