remove remaining release project indices
getsentry/sentry pull request #5439
Opened 2017-05-23 21:31 UTC by macqueen

2017-05-23 21:33 UTC, macqueen commented on src/sentry/south_migrations/0324_auto__del_index_releaseenvironment_project_id__del_unique_releaseenvir.py
> +        db.delete_unique('sentry_environmentrelease', ['project_id', 'release_id', 'environment_id'])
this evaluated to `ALTER TABLE "sentry_environmentrelease" DROP CONSTRAINT "sentry_environmentrelease_project_id_1762e5bd8b7a0675_uniq"` so i didn't think there was a way to improve that, but lmk if there is

2017-05-23 21:35 UTC, mattrobenolt commented on src/sentry/south_migrations/0324_auto__del_index_releaseenvironment_project_id__del_unique_releaseenvir.py
> +        db.delete_unique('sentry_environmentrelease', ['project_id', 'release_id', 'environment_id'])
Hmm, I'm going to have to research a tad, since this is different from what I normally do.

2017-05-30 18:20 UTC, mattrobenolt requested changes
Tests are definitely broken.

2017-06-14 18:03 UTC, mattrobenolt approved these changes

2017-06-14 21:58 UTC, merged