ref(inbound-filters): Move desc and label to frontend + add link to health check doc
getsentry/sentry pull request #54846
Opened 2023-08-16 15:32 UTC by priscilawebdev

closes: https://github.com/getsentry/sentry/issues/54539

Requires: https://github.com/getsentry/sentry-docs/pull/7649

**Preview:**

![image](https://github.com/getsentry/sentry/assets/29228205/4d132ff9-79a6-43e3-87f3-bd6a39c5bb66)

2023-08-16 15:37 UTC, matejminar approved these changes

2023-08-17 09:18 UTC, RaduW requested changes
Are we missing some of the filters (maybe the custom filters) ?
On server side we emit up to 12 filters.

Here's a list:
```
    IP_ADDRESS = "ip-address"
    RELEASE_VERSION = "release-version"
    ERROR_MESSAGE = "error-message"
    BROWSER_EXTENSION = "browser-extensions"
    LEGACY_BROWSER = "legacy-browsers"
    LOCALHOST = "localhost"
    WEB_CRAWLER = "web-crawlers"
    INVALID_CSP = "invalid-csp"
    CORS = "cors"
    DISCARDED_HASH = "discarded-hash"  # Not replicated in Relay
    CRASH_REPORT_LIMIT = "crash-report-limit"  # Not replicated in Relay
    HEALTH_CHECK = "filtered-transaction"  # Ignore health-check transactions

```

Could we please confirm that we handle all inbound filter properly (common filters or custom filters) ?

2023-08-17 09:18 UTC, RaduW submitted a review, later dismissed
Are we missing some of the filters (maybe the custom filters) ?
On server side we emit up to 12 filters.

Here's a list:
```
    IP_ADDRESS = "ip-address"
    RELEASE_VERSION = "release-version"
    ERROR_MESSAGE = "error-message"
    BROWSER_EXTENSION = "browser-extensions"
    LEGACY_BROWSER = "legacy-browsers"
    LOCALHOST = "localhost"
    WEB_CRAWLER = "web-crawlers"
    INVALID_CSP = "invalid-csp"
    CORS = "cors"
    DISCARDED_HASH = "discarded-hash"  # Not replicated in Relay
    CRASH_REPORT_LIMIT = "crash-report-limit"  # Not replicated in Relay
    HEALTH_CHECK = "filtered-transaction"  # Ignore health-check transactions

```

Could we please confirm that we handle all inbound filter properly (common filters or custom filters) ?

2023-08-17 09:46 UTC, priscilawebdev commented
@RaduW the other filters come from the project settings and not from the `/filters/` endpoint. Example:

> "options": {
>         "sentry:token": "59e1c2e83ac611eeb4ed7213a7859fc7",
>         "quotas:spike-protection-disabled": false,
>         "sentry:option-epoch": 11,
>         "sentry:csp_ignored_sources_defaults": true,
>         "sentry:csp_ignored_sources": "",
>         "sentry:reprocessing_active": false,
>         "filters:blacklisted_ips": "",
>         "filters:react-hydration-errors": true,
>         "filters:releases": "",
>         "filters:error_messages": "",
>         "feedback:branding": true
>     },


perhaps we should unify them one day but until then 🤷‍♀️

2023-08-17 09:47 UTC, merged