feat(slug): Prevent creating/updating to numeric monitor slugs
getsentry/sentry pull request #55125
Opened 2023-08-19 04:18 UTC by schew2381

2023-08-19 04:19 UTC, dashed approved these changes

2023-08-21 17:58 UTC, sentaur-athena requested changes
Looks good but "requesting changes" to add feature flag as discussed.

2023-08-21 18:55 UTC, sentaur-athena commented on src/sentry/monitors/validators.py
> +        DEFAULT_SLUG_PATTERN,
Same as previous PRs this will be addressed and won't need flag if you do this: https://github.com/getsentry/sentry/pull/55122#discussion_r1300521992

2023-08-22 20:44 UTC, sentaur-athena approved these changes

2023-08-28 22:00 UTC, merged