[WIP] Distinguish zero bar from others in event histogram
getsentry/sentry pull request #5519
Opened 2017-06-06 00:34 UTC by denamwangi

<img width="859" alt="histogram_zero buckets" src="https://cloud.githubusercontent.com/assets/16228317/26808812/7363904c-4a14-11e7-8417-506f6a68ab6a.png">

Working on your second suggestion Chris with having a standing bottom bar/shadow. So far my shadow is not looking so hot and not as clean as this version. I'll play with the settings.

2017-06-12 18:05 UTC, MaxBittker commented
addresses https://github.com/getsentry/sentry/issues/5241

2017-06-12 18:14 UTC, MaxBittker requested changes
looks good! only blocking this is dropping the ternary because i think this reads more cleanly.

2017-06-12 18:14 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/stackedBarChart.jsx
> +    return pct === 0 ? classNames(colClass, 'zero-bar') : colClass;
I think you should use the classNames predicate syntax here, like 
```
return classNames(colClass, {'zero-bar':  pct === 0})
```

2017-06-12 18:14 UTC, MaxBittker commented on src/sentry/static/sentry/less/stream.less
> +    .barchart {
is this to draw the line underneath it? why this and not `border-bottom: 1px solid @gray-lightest`?

2017-06-12 18:16 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/stackedBarChart.jsx
> +    const colClass = this.props.barClasses[idx];
could you help me understand what this barClasses array is?

2017-09-07 20:07 UTC, benvinegar commented
Hey folks, we re-visiting this?

2017-09-07 21:29 UTC, denamwangi commented
I definitely want to-i'll plan to loop back around to it next week

2018-01-03 17:40 UTC, closed without merging