chore(hybrid-cloud): Adds outbox type for subscription post-save events
getsentry/sentry pull request #55299
Opened 2023-08-28 21:39 UTC by GabeVillalobos

Adds new outbox types for subscription post-save operations that query different databases. Not an ideal solution so I'm open to other ways to handle this situation instead.

2023-08-28 21:41 UTC, corps commented
Hmm... flushing the cache doesn't seem like it requires a separate outbox, right?  If the original outbox itself is idempotent, it can simply run the cache flush at the end, and if that step fails the outbox retries until it completes.

2023-08-28 21:47 UTC, corps requested changes
What about just a `SUBSCRIPTION_UPDATE`?  That is, in this case, the outbox category is representing the event and not the goal.

2023-08-29 03:50 UTC, corps approved these changes

2023-08-29 18:26 UTC, markstory approved these changes

2023-08-29 20:14 UTC, merged