Add `GroupHash.state` and locking during unmerge task.
getsentry/sentry pull request #5560
Opened 2017-06-13 00:04 UTC by tkaemming

2017-06-13 00:07 UTC, dcramer approved these changes

2017-06-13 00:07 UTC, dcramer commented on src/sentry/tasks/unmerge.py
> +        eligible_hashes = list(
any reason to simply not do all of this in the same request? is it to avoid when any hash is flipped form active to inactive during it?

2017-06-13 00:07 UTC, tkaemming commented
This prevents someone from unmerging the same `GroupHash` twice, and allows us to reflect the lock status in the UI. This doesn't have an effect on other actions that lead to mutations to `GroupHash` like merges.

2017-06-13 00:08 UTC, tkaemming commented on src/sentry/tasks/unmerge.py
> +        eligible_hashes = list(
This needs to accurately return the fingerprints that were actually locked and you can't reliably do that without a `RETURNING` clause or a higher isolation level without using `SELECT OR UPDATE`.

2017-06-13 00:12 UTC, tkaemming commented
>  new columns need to be nullable (unless table is new)

Gonna fix this. 🙄

2017-06-13 00:37 UTC, tkaemming commented on src/sentry/tasks/unmerge.py
> +        eligible_hashes = list(
(Specifically, this is to avoid trying to start another migration on a hash that is already being migrated by another process.)

2017-06-13 18:50 UTC, tkaemming commented on src/sentry/south_migrations/0330_auto__add_field_grouphash_state.py
> +                      self.gf('sentry.db.models.fields.bounded.BoundedPositiveIntegerField')(default=0, null=True),
```LOG:  duration: 0.106 ms  statement: BEGIN
LOG:  duration: 56.158 ms  statement: ALTER TABLE "sentry_grouphash" ADD COLUMN "state" integer CHECK ("state" >= 0) NULL DEFAULT 0;
LOG:  duration: 2.041 ms  statement: ALTER TABLE "sentry_grouphash" ALTER COLUMN "state" TYPE integer, ADD CONSTRAINT CK_state_PSTV_556c62431651a0b1 CHECK ("state" >= 0), ALTER COLUMN "state" DROP NOT NULL, ALTER COLUMN "state" DROP DEFAULT;
LOG:  duration: 0.316 ms  statement: SELECT "south_migrationhistory"."id", "south_migrationhistory"."app_name", "south_migrationhistory"."migration", "south_migrationhistory"."applied" FROM "south_migrationhistory" WHERE ("south_migrationhistory"."app_name" = 'sentry'  AND "south_migrationhistory"."migration" = '0330_auto__add_field_grouphash_state' )
LOG:  duration: 1.127 ms  statement: INSERT INTO "south_migrationhistory" ("app_name", "migration", "applied") VALUES ('sentry', '0330_auto__add_field_grouphash_state', '2017-06-13 18:47:50.521119+00:00') RETURNING "south_migrationhistory"."id"
LOG:  duration: 13.018 ms  statement: COMMIT
```

2017-06-13 23:26 UTC, mattrobenolt requested changes
Just gonna reiterate this here for posterity. As-is, this migration will lock the table. We need to drop the database level default value.

2017-06-14 00:42 UTC, tkaemming commented
As of 999b087ebad1eaa470d2b34f1c4ebc4414f24d69:

```
LOG:  duration: 0.102 ms  statement: BEGIN
LOG:  duration: 2.931 ms  statement: ALTER TABLE "sentry_grouphash" ADD COLUMN "state" integer CHECK ("state" >= 0) NULL;
LOG:  duration: 3.482 ms  statement: ALTER TABLE "sentry_grouphash" ALTER COLUMN "state" TYPE integer, ADD CONSTRAINT CK_state_PSTV_556c62431651a0b1 CHECK ("state" >= 0), ALTER COLUMN "state" DROP NOT NULL, ALTER COLUMN "state" DROP DEFAULT;
LOG:  duration: 0.188 ms  statement: SELECT "south_migrationhistory"."id", "south_migrationhistory"."app_name", "south_migrationhistory"."migration", "south_migrationhistory"."applied" FROM "south_migrationhistory" WHERE ("south_migrationhistory"."app_name" = 'sentry'  AND "south_migrationhistory"."migration" = '0330_auto__add_field_grouphash_state' )
LOG:  duration: 0.203 ms  statement: INSERT INTO "south_migrationhistory" ("app_name", "migration", "applied") VALUES ('sentry', '0330_auto__add_field_grouphash_state', '2017-06-14 00:41:27.267006+00:00') RETURNING "south_migrationhistory"."id"
LOG:  duration: 0.386 ms  statement: COMMIT
```

2017-06-14 19:52 UTC, mattrobenolt approved these changes

2017-06-14 19:55 UTC, merged