Wizard only onboarding
getsentry/sentry pull request #55844
Opened 2023-09-07 13:18 UTC by smeubank

Remix, SvelteKit, and Nextjs

Someone can validate if these changes, by someone I mean a real developer :D

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2023-09-07 13:52 UTC, ArthurKnaus reviewed
Code itself looks good 👍

2023-09-07 13:52 UTC, ArthurKnaus commented on static/app/gettingStartedDocs/javascript/remix.spec.tsx
> +import {GettingStartedWithSvelteKit, steps} from './sveltekit';
Copy-🍝
```suggestion
import {GettingStartedWithRemix, steps} from './remix';
```

2023-09-08 09:35 UTC, Lms24 requested changes
Only requesting changes so we don't merge this until https://github.com/getsentry/sentry-wizard/issues/433 is resolved. Let's only publish this once the wizard is fully ready.

2023-09-08 10:36 UTC, smeubank commented
> Only requesting changes so we don't merge this until [getsentry/sentry-wizard#433](https://github.com/getsentry/sentry-wizard/issues/433) is resolved. Let's only publish this once the wizard is fully ready.

@Lms24 good to go?

cc @ArthurKnaus

2023-09-08 10:42 UTC, Lms24 approved these changes
LGTM, good call on proceeding here  w/o remix

2023-09-08 13:06 UTC, Lms24 commented
@smeubank fixed the linter errors, should be good now 🤞

2023-09-08 13:31 UTC, merged