Add ability to override the sample_rate on an individual basis.
getsentry/sentry pull request #5602
Opened 2017-06-22 17:16 UTC by JTCunning

Up in the air about doing this, or just changing sentry.io's sample rate, but sparse metrics get pretty nerfed because of sentry.io's `0.1` rate.

2017-08-11 20:43 UTC, mattrobenolt requested changes

2017-08-11 20:43 UTC, mattrobenolt commented on src/sentry/utils/metrics.py
> +def _sampled_value(value, sample_rate):
This isn't going to work right here. This variable immediately gets clobbered.

2018-08-30 20:30 UTC, markstory commented
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

2018-08-30 20:31 UTC, JTCunning commented
Wasn't that important.

2019-05-24 00:25 UTC, benvinegar commented
Can we revisit? It seems there are some metrics where sampling is hurting us (e.g. logins).

2019-05-24 00:27 UTC, JTCunning commented
aaaaaaaand we're back. going to rebase this since it's been a minute

2019-05-28 20:28 UTC, JTCunning commented
Closed in favor of https://github.com/getsentry/sentry/pull/5602.

2019-05-28 20:28 UTC, closed without merging