chore(hybrid-cloud): Introduce SENTRY_USE_MONOLITH_DBS
getsentry/sentry pull request #56056
Opened 2023-09-11 22:42 UTC by dashed

We have some backup tests that we'd like to ensure that it passes. But they can only run in non-split database mode. 

This pull request introduces `SENTRY_USE_MONOLITH_DBS` env variable to not skip these tests when `SENTRY_USE_MONOLITH_DBS=1`.

2023-09-11 23:19 UTC, azaslavsky reviewed
Just to be clear (since I see the main change is in the makefile):

- If I want to run any tests (not just backup) with `MONOLITH_DBS` mode turned on locally, I set the `SENTRY_USE_MONOLITH_DBS` env variable. If I don't set it, my local test run with execute with siloed dbs.
- All backup tests get run twice: once in silo mode like all other suites in `tests/`, and a second `SENTRY_USE_MONOLITH_DBS=1` mode run for the backup tests only.

Is the summary above correct? If so, that seems like a good solution to my immediate problem, though I do still wonder how this effects test coverage for self-hosted (or for that matter single-tenant) as a whole? For a release of `sentry` to be valid for self-hosted, the entirety of the test suite would need to be tested with `MONOLITH_DBS` on, right?

2023-09-11 23:19 UTC, azaslavsky commented on Makefile
> +	SENTRY_USE_MONOLITH_DBS=1 pytest tests/sentry/backup \
Also: tests/sentry/runner/commands/test_backup.py

2023-09-12 13:14 UTC, asottile-sentry requested changes, later dismissed

2023-09-12 13:14 UTC, asottile-sentry commented on Makefile
> +		--cov . --cov-report="xml:.artifacts/python-backup-tests.coverage.xml"
we've been working hard to *reduce* the number of special ways to run our testsuite.  I would strongly prefer this be done inside the test and not in the Makefile

it's been a constant source of feedback in dev-infra surveys that running ci tests locally is difficult and this just increases the barrier to entry further

2023-09-13 19:23 UTC, azaslavsky approved these changes

2023-09-13 19:38 UTC, merged