feat(ui): Add `story-ui` command to run internal storybook
getsentry/sentry pull request #56511
Opened 2023-09-19 21:35 UTC by evanpurkhiser

2023-09-19 21:44 UTC, ryan953 approved these changes

2023-09-19 21:44 UTC, ryan953 commented on static/app/views/stories/storyList.tsx
seems unrelated to the build stuff but w/e

2023-09-19 21:46 UTC, evanpurkhiser commented on static/app/views/stories/storyList.tsx
It is related, it's no longer at `/stories/` now

2023-09-19 21:47 UTC, ryan953 commented on static/app/views/stories/storyList.tsx
oh, derp, nice!

2023-09-20 14:57 UTC, ryan953 commented
Whatever the strategy is, we should make it work for getsentry too. I'm worried that splitting this off onto vercel has low value and cut off all those components from participating. We should describe the value of this PR instead of briefly restarting what the code states

2023-09-20 15:03 UTC, ryan953 requested changes
Whatever the strategy is, we should make it work for `getsentry` too. I'm worried that splitting this off onto vercel has low value on it's own, and will prevent off all those components from participating which I think is more interesting.
We should describe the value of this PR instead of briefly restarting what the code states in the description.

2023-09-25 21:32 UTC, closed without merging