Fix #5703: Improve error message when events fail to load
getsentry/sentry pull request #5707
Opened 2017-07-11 21:44 UTC by billyvg

In `<GroupEventDetails>`, swapped out `<LoadingError>` with a new `<DetailedError>`.

![image](https://user-images.githubusercontent.com/79684/28092223-7665859e-6647-11e7-9223-22862c56533a.png)

2017-07-11 21:47 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-07-12 22:15 UTC, macqueen reviewed
looks awesome! one question: why is the pagination/header showing in the screenshot? it seems like that shouldn't be available

2017-07-12 22:15 UTC, macqueen commented on src/sentry/static/sentry/app/components/errors/groupEventDetailsLoadingError.jsx
> +      heading="Sorry, the events for this issue could not be found."
this should be translated too

2017-07-12 22:15 UTC, macqueen commented on src/sentry/static/sentry/app/components/errors/groupEventDetailsLoadingError.jsx
> +          <p>This could be due to a handful of reasons:</p>
and this

2017-07-12 22:25 UTC, billyvg commented on src/sentry/static/sentry/app/components/errors/groupEventDetailsLoadingError.jsx
> +          <p>This could be due to a handful of reasons:</p>
Oops, thanks!

2017-07-12 22:28 UTC, billyvg commented
Ah the reason the toolbar is showing is because I was only setting the `error` state in `<GroupEventDetails>` and the toolbar is displayed as long as the `event` data is in state.

2017-07-12 22:37 UTC, ckj requested changes

2017-07-12 22:37 UTC, ckj commented on src/sentry/static/sentry/less/errors.less
> +  padding: 18px;
After playing around with this locally, I think this needs bumped up to something like 40px. It's a bit tight for my taste as it is.

2017-07-12 22:38 UTC, ckj commented on src/sentry/static/sentry/less/errors.less
> +  padding: 18px;
NM! Looks like you covered it elsewhere in your last commit.

2017-07-12 22:38 UTC, ckj approved these changes
🤘

2017-07-13 17:48 UTC, merged