ref(arroyo): arroyo_producer learns to produce to specific partition
getsentry/sentry pull request #57860
Opened 2023-10-10 21:09 UTC by evanpurkhiser

This just mirrors the underlying interface

2023-10-10 21:10 UTC, untitaker approved these changes

2023-10-10 21:13 UTC, lynnagara requested changes
Producing to a specific partition makes it hard for us to change the partitions later and it makes the application need to be aware of the topology of the Kafka cluster which we want to avoid. Can you set the message key instead?

2023-10-11 17:47 UTC, evanpurkhiser commented
Okay @lynnagara I've discussed with @fpacifici. We're going to move forward with this approach, we are OKAY in this scenario producing to a specific partition.

See https://github.com/getsentry/sentry/issues/55821#issuecomment-1758150543

I can also create a separate function that is discouraged from use and keep the interface on this one explicit as it is now?

2023-10-11 20:44 UTC, lynnagara approved these changes

2023-10-11 20:47 UTC, merged