Onboarding project polish
getsentry/sentry pull request #5795
Opened 2017-08-01 00:13 UTC by MaxBittker

the setPlatform logic is complicated enough it should probably have better testing

2017-08-01 00:15 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-08-01 01:37 UTC, ehfeng requested changes

2017-08-01 01:37 UTC, ehfeng commented on src/sentry/static/sentry/app/views/onboarding/index.jsx
> +          parseLastToken(this.state.platform) === this.state.projectName
Let's use name, like "Node.js", instead of shortening the platform id, "like nodejs".

2017-08-03 18:41 UTC, denamwangi approved these changes
This lgtm. I wonder if the red box is too subtle for indicating the field is required? nbd and we can always revisit if support gets questions related to it.

2017-08-03 19:39 UTC, ehfeng approved these changes

2017-08-03 20:37 UTC, merged