tooling(storybook): add more storybook stories for existing components
getsentry/sentry pull request #5811
Opened 2017-08-03 23:14 UTC by billyvg

Adds storybook stories for some of our existing components

Do not merge before #5807 

#nochanges

2017-08-03 23:19 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-08-04 05:39 UTC, benvinegar requested changes
Please see my `publicPath` comment, otherwise lgtm.

2017-08-04 05:39 UTC, benvinegar commented on webpack.config.js
> +    publicPath: '/_static/sentry/dist/',
Are we using code splitting or anything here? I learned later this doesn't work and fixed it [in this PR](https://github.com/getsentry/sentry/pull/5623/commits/50b5ee383371741f64b835682c8e8faa63996b3d).

2017-08-04 16:01 UTC, billyvg commented on webpack.config.js
> +    publicPath: '/_static/sentry/dist/',
Nope, I think this was added in the old styleguide when we wanted to codesplit, so seems good to remove.

2017-08-04 20:28 UTC, benvinegar approved these changes

2017-08-07 21:45 UTC, merged