backfilling project platform
getsentry/sentry pull request #5836
Opened 2017-08-07 22:51 UTC by ehfeng

Now that `Project` has a `platform` column, it'd be great to be able to backfill these with data from `ProjectPlatform`

1. If there are no platforms, do nothing
2. If there is one platform, populate `Project.platform`
3. If there are two platforms, use the most recent `last_seen`

I could alternatively do a `RangeQuerySetWrapperWithProgressBar` over Project, if that's preferred. That would double the amount of work (half of the `Project`s don't have a corresponding `ProjectPlatform` row), but if it's preferred, we can do taht.

2017-08-07 22:53 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR includes migrations</td>
    </tr>
  </tbody>
</table>

## Migration Checklist

- [ ] new columns need to be nullable (unless table is new)
- [ ] migration with any new index needs to be done concurrently
- [ ] data migrations should not be done inside a transaction
- [ ] before merging, check to make sure there aren't conflicting migration ids


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-08-07 23:36 UTC, mattrobenolt requested changes
Overall, this seems like you're doing the work backwards. I might be wrong, but why not iterate over all Projects that are missing a platform, and calculate those instead?

It seems starting with just:

```python
Project.objects.filter(platform__isnull=True)
```

would simplify this a bit.

2017-08-07 23:36 UTC, mattrobenolt commented on src/sentry/south_migrations/0342_projectplatform.py
> +            project = Project.objects.get(pk=row['project_id'])
Can just do:

```python
Project.objects.filter(pk=row['project_id'], platform__isnull=True).update(platform=projectplatform.platform)
```

This also removes the race condition that you have there now.

2017-08-07 23:36 UTC, mattrobenolt commented on src/sentry/south_migrations/0342_projectplatform.py
> +                projectplatform = ProjectPlatform.objects.filter(project_id=row['project_id']
Are there any cases where this would be an index error? Is it not possible for `row['platforms'] == 0` ?

2017-08-08 01:32 UTC, mattrobenolt commented on src/sentry/south_migrations/0342_projectplatform.py
> +                project.platform = projectplatform.platform
Do:

```python
Project.objects.filter(id=project.id).update(platform=projectplatform.platform)
```

To avoid a race condition.

2017-08-08 19:23 UTC, ehfeng commented on src/sentry/south_migrations/0342_projectplatform.py
> +                project.platform = projectplatform.platform
Fixed

2017-08-08 19:27 UTC, mattrobenolt requested changes

2017-08-08 19:27 UTC, mattrobenolt commented on src/sentry/south_migrations/0342_projectplatform.py
> +                project.save()
Now remove this line.

2017-08-08 19:40 UTC, ehfeng commented on src/sentry/south_migrations/0342_projectplatform.py
> +                project.save()
oh, right. that was stupid of me.

2017-08-08 21:24 UTC, mattrobenolt commented
This migration now conflicts with https://github.com/getsentry/sentry/pull/5843 for 0342, so whoever loses will have to change.

2017-08-09 17:31 UTC, mattrobenolt approved these changes

2017-08-09 17:50 UTC, merged