Parse full BitBucket repo urls
getsentry/sentry pull request #5879
Opened 2017-08-14 23:09 UTC by kjlundsgaard

Fixes #5874

2017-08-14 23:11 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-08-14 23:22 UTC, MaxBittker requested changes
would it be possible to just have parseRepo, which matches one or the other? would make the code simpler.

also, is there any weird input that could mess with this? like if someone had bitbucket.com as their repo or user name? i guess that's probably not possible. 

I know that this was meant to be a quick fix so feel free to skip some of the style changes if you think it's better not to mess with it right now.

2017-08-14 23:22 UTC, MaxBittker commented on src/sentry/static/sentry/app/utils.jsx
> +    match ? (parsedRepo = match[1]) : (parsedRepo = repo);
ik you were just matching the other form, but this should rly be
` let parsedRepo =  match ? match[1] : repo;`
imo

2017-08-14 23:22 UTC, MaxBittker commented on src/sentry/static/sentry/app/utils.jsx
> +  } else {
also i think it reads easier if the function starts with a guard statement like `if( not repo) return repo`

2017-08-14 23:22 UTC, MaxBittker commented on src/sentry/static/sentry/app/utils.jsx
> +  } else {
instead of the big if else that's slightly harder to read

2017-08-15 18:23 UTC, MaxBittker approved these changes
sweeeet :bucket:

2017-08-15 20:22 UTC, merged