feat(github-growth): client side pagination for invite modal
getsentry/sentry pull request #59495
Opened 2023-11-07 00:06 UTC by cathteng

Members can be selected across pages, and each page has up to 6 rows. Changed the behavior  for the checkbox in the header to select all rows on the page and to have no rows selected by default.

<img width="1484" alt="Screenshot 2023-11-06 at 16 01 42" src="https://github.com/getsentry/sentry/assets/70817427/42b5f652-7fce-44ea-b4d9-2adc8bb3caed">

https://github.com/getsentry/sentry/assets/70817427/9219ef7a-14d9-4a6b-91e0-749d668cd02e

For ER-1918

2023-11-07 17:09 UTC, cathteng commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +  const pageCount = Math.floor(initialMemberInvites.length / ROWS_PER_PAGE);
this does zero-indexing

2023-11-07 17:09 UTC, cathteng commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +  const setRole = (role: string, email: string) => {
these use email instead of index now because the full list of missing members is sliced. also, email is still a unique identifier

2023-11-07 17:10 UTC, cathteng commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +      if (i >= currentPage * ROWS_PER_PAGE && i < (currentPage + 1) * ROWS_PER_PAGE) {
selects the members whose indices are currently being shown

2023-11-07 17:56 UTC, scttcper commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +          const checked = membersOnPage[i].selected;
```suggestion
          const checked = member.selected;
```

2023-11-08 18:15 UTC, sentaur-athena approved these changes
Looks good. Just a product feedback

2023-11-08 18:17 UTC, cathteng commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +const ROWS_PER_PAGE = 6;
this is how many rows fit on the modal in full screen mode on a computer. the table doesn't fit when you are on a small screen...

also, you can select all on the page

2023-11-08 20:01 UTC, nhsiehgit requested changes

2023-11-08 20:01 UTC, nhsiehgit commented on static/app/components/modals/inviteMissingMembersModal/index.tsx
> +const ROWS_PER_PAGE = 6;
Oh.

this is purely a client side pagination??

Lets def just make this infinite scroll then

2023-11-13 17:39 UTC, cathteng commented
no need for this since we can have dropdowns rendered correctly inside a modal with a scrolling parent component https://github.com/getsentry/sentry/pull/59764

2023-11-13 17:39 UTC, closed without merging