feat(api): Add download function for debug symbols
getsentry/sentry pull request #6067
Opened 2017-09-08 10:09 UTC by HazAT

This adds a download button for debug symbols.
<img width="939" alt="screenshot 2017-09-08 12 09 12" src="https://user-images.githubusercontent.com/363802/30207072-92c73208-948e-11e7-95ba-97074ef211aa.png">

2017-09-08 10:10 UTC, mitsuhiko commented
lgtm but we should verify with @getsentry/ops if downloading dsyms is okay from the web workers.

2017-09-08 10:12 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-09-12 16:33 UTC, JTCunning requested changes
Please add a rate limiter to this so that we do not expose any future exploitations of downloading. 

A good example is here: https://github.com/getsentry/sentry/blob/master/src/sentry/plugins/base/notifier.py#L33-L37

I'll defer to @mattrobenolt for any of the kwarg specifics.

2017-09-12 16:54 UTC, dcramer requested changes
We also need a test to prove permissions are correct here.

2017-09-19 06:55 UTC, HazAT commented
@JTCunning rate limiting applied
@dcramer tests are in place

2017-09-19 16:45 UTC, dcramer approved these changes

2017-09-20 07:36 UTC, merged