Onboarding widget
getsentry/sentry pull request #6069
Opened 2017-09-08 16:44 UTC by denamwangi

Add detailed descriptions on hover, shorten list of tasks, and refactor existing components.

2017-09-08 18:43 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-09-08 22:41 UTC, MaxBittker requested changes
on the macro sense, looks great, just tagged a handful of small syntax nits! I realize that a lot of this code was rearranged from it's old form, so in any case that you don't want to mess with it, it's your discretion to leave it as-is. just wanted to bring these things to light

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/confirmation.jsx
> +      <div className="ob-confirmation" onClick={this.dismiss}>
you can just put this.props.dismiss in here directly and remove line 17-19

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +  learnMoreUrlCreator: function(org) {
you can just do `let org = this.getOrganization();` inside this function instead of passing it through from render

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +  toggleDescription(e) {
nit, but `e` isn't used

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +    task: PropTypes.object,
should task be required here?

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +      return <p>{this.props.task.description}. {this.props.task.detailedDescription}</p>;
nit, but maybe combine these into `return <p>{this.props.task.description} {this.state.isExpanded && ('. ' +this.props.task.detailedDescription)}</p>;`

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +        '/organizations/' +
I think it's nicer to use es6 format strings to build these, aka 
```
`/organizations/${org.slug}/projects/choose/?onboarding=1&task=${this.props.task.task}`
```

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +        '/organizations/' +
(nit)

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +      learnMoreUrl = this.props.task.location;
is there any other case? could you add an else clause here to make sure this gets defined to something, or maybe even a raven.captureMessage("this should never happen") kind of thing?

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +    this.props.onSkip(task);
you _could_ bind skip when you pass it down like `()=>this.skip(task)`, let me know if you want me to elaborate on this

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +    this.props.onSkip(task);
instead of letting the child supply the task

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/toDoItem.jsx
> +      classNames += ' blur';
the classnames library would make this logic simpler, lmk if you want an example

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/todos.jsx
> +    // Map server task state (who finished what) to TodoList.TASK objects
can this all go in getInitialState?

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/todos.jsx
> +    // e.preventDefault();
remove commented code. why is this needed btw?

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/todos.jsx
> +    }, this);
not sure this `this` is needed

2017-09-08 22:41 UTC, MaxBittker commented on src/sentry/static/sentry/app/components/onboardingWizard/todos.jsx
> +    let todo_list = nextTasks.map(task => {
tiny nit, but probably camelcase this

2017-09-11 22:51 UTC, MaxBittker approved these changes
this is good to go when you're happy with the nits

2017-09-12 16:48 UTC, merged