feat(ai): Issue severity short circuit to 1 + add severity reason to metadata
getsentry/sentry pull request #61779
Opened 2023-12-14 19:17 UTC by jennmueng

Key changes:
- Adds a `severity.reason` field to the group metadata
- severity score function always returns a defined score
- Bad titles (\<unknown\>, Error, etc) are auto-assigned a 0.0 severity score.
- When there is a error with getting the severity score from the seer microservice we short circuit to severity `1.0` and the reasoning provided.

Possible values for reason:
- `log_level_fatal`
- `log_level_info`
- `bad_title`
- `ml`
- `microservice_max_retry`
- `microservice_error`

2023-12-14 20:02 UTC, isabellaenriquez approved these changes

2023-12-14 20:28 UTC, armenzg requested changes

2023-12-14 20:28 UTC, armenzg commented on src/sentry/event_manager.py
>      if features.has("projects:first-event-severity-calculation", event.project):
This is a very risky code path. Put this logic into its own function and wrap it with a try/except block.

2023-12-14 20:39 UTC, vartec commented on src/sentry/event_manager.py
> +        group_data["metadata"]["severity.reason"] = reason
I'd go with `severity_reason`,or doing away with backwards compatibility and changing it to ```group_data["metadata"]["severity"] = {"value": severity, "reason": reason}```

2023-12-15 20:49 UTC, vartec approved these changes

2023-12-18 17:01 UTC, armenzg approved these changes
👍🏻

2023-12-18 19:29 UTC, merged