fix(tests): Fix pytest warnings from upgrade
getsentry/sentry pull request #6235
Opened 2017-10-02 20:12 UTC by mattrobenolt

There are others, but they seem to be from outside our codebase.

2017-10-02 20:13 UTC, mattrobenolt commented on src/sentry/utils/pytest/selenium.py
> +@pytest.hookimpl(hookwrapper=True)
tbh waiting on Travis for this one to confirm it actually worked. I hobbled this together from random PRs that fixed this warning themselves by doing something similar.

2017-10-02 20:14 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-10-04 21:26 UTC, tkaemming requested changes
Requesting changes since you mentioned making some additional fixes and this way we don't get emailed about it. 🙂  This change itself looks fine and probably does something.

2018-09-21 02:26 UTC, markstory commented
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

2018-09-25 14:37 UTC, closed without merging