feat(grouping): Add BuiltInFingerprintVariant
getsentry/sentry pull request #63165
Opened 2024-01-13 00:56 UTC by vartec

Add BuiltInFingerprintVariant  to allow UI to differentiate between built-in and user-defined custom fingerprint rules

2024-01-13 01:05 UTC, scefali commented on src/sentry/grouping/variants.py
> +        return "built-in fingerprint"
@vartec I think we wanted to say `Sentry Defined Fingerprint`

2024-01-16 18:35 UTC, armenzg requested changes
The PR looks good. We need to separate it into two different PRs before we can merge them.

2024-01-19 02:50 UTC, vartec commented on src/sentry/grouping/fingerprinting/__init__.py
> +        return fingerprinting_rules
fully covered now.
![Screenshot 2024-01-18 at 6 49 34 PM](https://github.com/getsentry/sentry/assets/2284726/c4302850-d51c-4c57-a7fc-efbb331735f3)

2024-01-19 18:17 UTC, armenzg approved these changes
Great job @vartec !

2024-01-19 19:43 UTC, jangjodi approved these changes

2024-01-19 20:29 UTC, merged