initial stab at schema [wip]
getsentry/sentry pull request #6438
Opened 2017-10-26 04:40 UTC by MaxBittker

2017-10-26 04:43 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-10-31 22:50 UTC, macqueen requested changes

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +sentry.models.groupseen
should be grouplink

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +    Link a group with an extenal resource like a commit, issue, or pull request
`extenal` --> `external`

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +        links = 2
what about calling this `references` or something? don't really care either way, just seems like a way to not overuse the word `link`

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +    unique_together = (('group_id', 'linked_type', 'linked_id'), )
this needs to be defined in the meta class, and you'll need to regenerate the migration to actually create the unique constraint

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +    datetime = models.DateTimeField(default=timezone.now, db_index=True)
definitely a nit, but i think it's easier to tell what the model fields are when they're grouped together without a blank line between them

2017-10-31 22:50 UTC, macqueen commented on src/sentry/models/grouplink.py
> +        choices=((LinkedType.commit, _('Commit')),
i'm pretty sure `choices` are only used for django forms, which we'll probably never have for this, so not sure if this is necessary

2017-11-01 17:48 UTC, dcramer commented on src/sentry/models/grouplink.py
> +    group_id = BoundedBigIntegerField()
could we also add a project_id column, as it will make some things easier in the future when we do tenants

2017-11-01 21:18 UTC, macqueen approved these changes
there is already a migration in master with id 0362, so you're going to need to regenerate the migration before merging. other than that, looks good!

2017-11-01 21:38 UTC, merged