feat(ci): Adding migrations approval check to CI
getsentry/sentry pull request #64433
Opened 2024-02-01 23:38 UTC by IanWoodard

As part of a push to prevent problematic migrations from being merged, this PR adds an additional check that ensures migrations are approved by a member of `owners-migrations`. One thing to note is that in order for this to work properly, we will have to make this a required action once this is merged. It is worth noting that if a change does not touch a migration, this workflow is skipped meaning it won't block merging (even if required).

2024-02-02 08:25 UTC, asottile-sentry commented
what are we trying to solve here.  this feels like extra gatekeeping.  we should trust developers to do the right thing and if they don't that's a people management problem

2024-02-06 21:28 UTC, snigdhas approved these changes
Thanks for adding this!

2024-02-06 21:31 UTC, snigdhas commented
@asottile-sentry I agree this is extra process, but it's coming from an [incident](https://www.notion.so/sentry/INC-611-Save-workers-backlogging-9cd511d97e2049dd8e600e14c1f11cf7) that took down Sentry because of a bad migration that wasn't thoroughly reviewed by the right folks, so the tradeoff feels worth it

2024-02-06 21:33 UTC, asottile-sentry requested changes, later dismissed
I'm going to put a blocking review for now.  we should not be unnecessarily adding process / sign off by a small group of people at sentry.

if the system is implicitly unsafe more eyeballs is not going to solve the problem and a small group sign off is not going to scale with the organization.

we need to put the correct safety guards in place automatically or they will not be effective

2024-02-06 22:48 UTC, snigdhas commented
That makes sense, I've got a [spec](https://www.notion.so/sentry/Run-migration-checks-on-all-SQL-migrations-861c814559db4355aa695df24adb129d) started for a system-based improvement. We'd need to start running the migration checks on all SQL migrations and not just those generated by Django. 

I'm still working through specifics, and I plan to open a Github Issue for the [library](https://github.com/tbicr/django-pg-zero-downtime-migrations), but it looks like that library is just being maintained for new versions and not adding new features so it would have to be something we fork and build ourselves.

2024-02-07 01:59 UTC, asottile-sentry commented
my 2c is we should just ban custom sql

2024-02-09 22:33 UTC, snigdhas commented
I don't think that's the right solution here. Perhaps we need is a larger set of people to be part of migrations-owners to distribute review load. Migrations likely don't need a <24h review turnaround given they're often risky. I'll add this as a discussion topic for the next TSC to run it by other folks.

2024-02-15 01:49 UTC, anonrig commented on .github/workflows/scripts/team-approval-check.js
> +    if (reviews.length === 0) {
Array.isArray check is missing. The next github call actually has it.

2024-02-15 01:49 UTC, anonrig commented on .github/workflows/scripts/team-approval-check.js
> +    const memberIds = members.map(member => member.id);
If you convert this to a set, it will be a lot easier and faster to check with .has()

2024-02-15 01:49 UTC, anonrig commented on .github/workflows/scripts/team-approval-check.js
> +  check: async ({github, context, core, team_slug}) => {
Can we add a JSDoc to here to not lose the context and have proper intellisense?

2024-03-21 07:01 UTC, closed without merging