feat(tags): Add environment_id to tagstore create APIs
getsentry/sentry pull request #6478
Opened 2017-10-30 21:49 UTC by bretthoerner

This is *just* dealing with the create APIs. Note that the legacy
backend ignores the environment that is passed in, but I've made sure to
pass in a valid environment_id everywhere these methods are called.

2017-10-31 05:06 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-11-13 22:25 UTC, tkaemming requested changes
This generally looks good but your build is broken (see inline comment.)

Are you planning on filling the legacy backend, or does that depend on what we decide the future plan is?

2017-11-13 22:25 UTC, tkaemming commented on src/sentry/tasks/unmerge.py
> +        environment = get_environment(event)
This was renamed as part of GH-6492.

2017-11-13 22:37 UTC, bretthoerner commented
When you say filling do you mean "making use of `environment_id`"? If so, no, `legacy` will always ignore it. The new backend will have the columns and be able to support it.

2017-11-13 22:39 UTC, tkaemming commented
That answers my question. I accidentally a word in my comment above (I meant to write "are you planning on filling out" which I guess wasn't super clear to begin with.)

2017-11-13 23:03 UTC, bretthoerner commented
@tkaemming Fixed the tests.

2017-11-13 23:04 UTC, tkaemming approved these changes
🌄

2017-11-13 23:05 UTC, merged