Changing killswitch flags
getsentry/sentry pull request #64930
Opened 2024-02-09 02:51 UTC by kneeyo1

This removes the automator_modifiable flag from the killswitch options we have.

2024-02-10 05:09 UTC, fpacifici requested changes

2024-02-10 05:09 UTC, fpacifici commented on src/sentry/options/defaults.py
> +register("store.load-shed-process-event-projects-gradual", type=Dict, default={})
This is not a killswitch.

2024-02-10 05:43 UTC, kneeyo1 commented on src/sentry/options/defaults.py
> +register("store.load-shed-process-event-projects-gradual", type=Dict, default={})
oh right, this is a rollout flag

2024-02-10 05:43 UTC, kneeyo1 commented on src/sentry/options/defaults.py
> +register("store.load-shed-process-event-projects-gradual", type=Dict, default={})
my b

2024-03-27 23:05 UTC, kneeyo1 commented
We will be supporting killswitches in the future, closing this PR

2024-03-27 23:05 UTC, closed without merging