chore(issues): Remove usage of issue-alert-fallback-targeting flag from the frontend
getsentry/sentry pull request #64965
Opened 2024-02-09 20:00 UTC by leeandher

It's GA'd so I'll delete it from the frontend and try to get rid of any unused components as well.

2024-02-09 21:10 UTC, vartec approved these changes

2024-02-09 23:15 UTC, scttcper commented on static/app/views/alerts/rules/issue/ruleNode.tsx
> -      !organization.features.includes('issue-alert-fallback-targeting')
i think this block should be deleted?

2024-02-09 23:17 UTC, scttcper commented on static/app/views/projectInstall/issueAlertOptions.tsx
> +          ...{fallthroughType: 'ActiveMembers'},
i think in this case we can change ISSUE_ALERT_DEFAULT_ACTION to have `fallthroughType: 'ActiveMembers'` all the time

2024-02-09 23:19 UTC, scttcper commented on static/app/views/alerts/rules/issue/ruleNode.tsx
> -      !organization.features.includes('issue-alert-fallback-targeting')
yeah we do not want to display the below MarginlessAlert

2024-02-09 23:19 UTC, scttcper requested changes
just blocking to make sure we don't auto merge or whatever

2024-02-12 17:21 UTC, scttcper approved these changes
nice, one less api call this is great

2024-02-12 17:23 UTC, merged

2024-02-12 17:26 UTC, scttcper commented on static/app/views/settings/project/projectOwnership/index.spec.tsx
> +    it('should hide issue owners', () => {
just realizing this test is probably useless