Drop eventtag index migration
getsentry/sentry pull request #6545
Opened 2017-11-14 15:32 UTC by bretthoerner

2017-11-14 15:54 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR includes migrations</td>
    </tr>
  </tbody>
</table>

## Migration Checklist

- [ ] new columns need to be nullable (unless table is new)
- [ ] migration with any new index needs to be done concurrently
- [ ] data migrations should not be done inside a transaction
- [ ] before merging, check to make sure there aren't conflicting migration ids


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-11-14 17:47 UTC, mattrobenolt requested changes

2017-11-14 17:47 UTC, mattrobenolt commented on src/sentry/south_migrations/0365_auto__del_index_eventtag_project_id_key_id_value_id.py
> +    is_dangerous = False
We need to set this to True. I will be running this by hand.

2017-11-15 17:22 UTC, mattrobenolt approved these changes

2017-11-17 19:33 UTC, mattrobenolt commented
This migration id also conflicts with #6571. So one of you will need to fix depending on which is merged first.

2017-11-17 19:33 UTC, bretthoerner commented
Mashing merge the second travis finishes. 🔥

2017-11-17 19:43 UTC, mattrobenolt commented
gl @adhiraj, you lost the race this time.

2017-11-17 19:51 UTC, merged