perf: enable dogstatsd buffering
getsentry/sentry pull request #66039
Opened 2024-02-29 01:13 UTC by anonrig

Alternative to https://github.com/getsentry/sentry/pull/66032

@wedamija thank you for finding it!

2024-02-29 01:17 UTC, wedamija reviewed
This lgtm. The only concern I have is from https://docs.datadoghq.com/developers/dogstatsd/high_throughput/

> By default, Python DogStatsD client instances (including the statsd global instance) cannot be shared across processes but are thread-safe. Because of this, the parent process and each child process must create their own instances of the client or the buffering must be explicitly disabled by setting disable_buffering to True. See the documentation on [datadog.dogstatsd](https://datadogpy.readthedocs.io/en/latest/#datadog-dogstatsd) for more details.

We use multiproc in some consumers. As far as I know, we fork before we import anything, and so we should be safe. But would just like to confirm that's true with @untitaker @lynnagara 

Single tenant uses this backend too, so if this causes problems we should see them there before we get to the US region

2024-02-29 14:43 UTC, asottile-sentry approved these changes
![](https://i.fluffy.cc/Xr1jnB3r6dWrfwqPwNdrpnF9zW1lVp0F.gif)

2024-02-29 20:43 UTC, untitaker commented
> We use multiproc in some consumers. As far as I know, we fork before we import anything, and so we should be safe. But would just like to confirm that's true with @untitaker @lynnagara

We do however import before fork in celery (that's where our recent memory savings come from!), so anything that is not inherently fork-safe may break/segfault in celery.

so, i still think you need to find a way to initialize the datadog client per-process. maybe it means checking your own PID all the time, and re-creating the client if it is different, or maybe there is a celery hook that can be used to run some code after forking is done.

2024-02-29 20:45 UTC, untitaker reviewed
if you want to move forward with this i suggest either making our metrics backend totally fork-safe (as per above suggestions), or opting into this new behavior for specific pods only.

you can also let this change bake in s4s for quite a while by making it a setting

2024-02-29 21:37 UTC, mitsuhiko requested changes
We need to reinitialize the client on new process and it's good to ship.

2024-03-04 16:46 UTC, mitsuhiko approved these changes
Looks like the library already supports fork detection.

2024-03-04 17:07 UTC, merged

2024-03-04 17:31 UTC, mitsuhiko commented on src/sentry/metrics/dogstatsd.py
> +        if features.has("datadog:enable-buffering"):
Sorry I missed this. This should be the other way around.

2024-03-04 17:32 UTC, mitsuhiko commented on src/sentry/metrics/dogstatsd.py
> +        if features.has("datadog:enable-buffering"):
Nevermind i'm wrong.