[WIP] tags: Beginning of v2 backend (setup, create, basic get)
getsentry/sentry pull request #6637
Opened 2017-11-28 16:18 UTC by bretthoerner

2017-11-28 16:20 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-11-28 17:57 UTC, mattrobenolt commented on src/sentry/tagstore/deletions.py
> +def tagkeydeletiontask_factory(tagvalue_model, grouptagkey_model, grouptagvalue_model):
🙄

2017-11-28 18:00 UTC, bretthoerner commented on src/sentry/tagstore/deletions.py
> +def tagkeydeletiontask_factory(tagvalue_model, grouptagkey_model, grouptagvalue_model):
get out, matt

2017-12-08 00:01 UTC, mattrobenolt requested changes
Just my minor nits, but other than that, this looks like hell. Let's ship it.

2017-12-08 00:01 UTC, mattrobenolt commented on src/sentry/tagstore/migrations/0001_initial.py
> +# -*- coding: utf-8 -*-
I don't know how or why, but migrations for nodestore at in `south_migrations` folder. Can we make that happen here too?

2017-12-08 00:01 UTC, mattrobenolt commented on src/sentry/tagstore/migrations/0001_initial.py
> +    is_dangerous = False
I would argue that we should just set this to True for ourselves even though it's not technically dangerous, just applying this to our existing cluster doesn't need to happen. We'll apply manually to shards.

2017-12-08 11:34 UTC, bretthoerner commented
@mattrobenolt fixed your issues

2017-12-08 17:59 UTC, mattrobenolt approved these changes
Punch it. 🍕

2017-12-08 18:03 UTC, merged