Convert project tags page to React
getsentry/sentry pull request #6645
Opened 2017-11-29 01:19 UTC by lynnagara

2017-11-29 01:23 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-11-29 22:57 UTC, billyvg requested changes
Needs some small fixes, but otherwise looks great!

2017-11-29 22:57 UTC, billyvg commented on src/sentry/templates/sentry/projects/manage.html
> +        <a href="{% absolute_uri '/{}/{}/settings/tags' project.organization.slug project.slug %}">{% trans "Tags" %}</a>
I haven't tested this but I suspect URL is wrong here, missing trailing slash

2017-11-29 22:57 UTC, billyvg commented on src/sentry/static/sentry/app/views/projectTags.jsx
> +                        onClick={() => this.onDelete(key, idx)}
Looks like one thing we're missing here is the confirm modal before deleting. I believe we have a `<Confirm>` component for this.

2017-11-30 23:00 UTC, billyvg approved these changes
Woo only 3 more views to go

2017-11-30 23:02 UTC, billyvg commented
Not sure why org stats view is failing on percy, should be unrelated to this PR

2017-12-01 21:24 UTC, merged