feat(replays): Skip billing for replay-video types
getsentry/sentry pull request #66909
Opened 2024-03-13 20:11 UTC by cmanallen

While relay-video is in alpha let's not bill people.

2024-03-13 20:16 UTC, michellewzhang approved these changes

2024-03-13 20:48 UTC, JoshFerge requested changes
we'd still probably want to send the "first replay received" signal, though no?

2024-03-15 19:56 UTC, JoshFerge approved these changes

2024-03-20 16:55 UTC, JoshFerge approved these changes

2024-03-28 14:57 UTC, merged