feat(metrics): Track discarded events
getsentry/sentry pull request #6706
Opened 2017-12-07 00:35 UTC by macqueen

2017-12-07 00:56 UTC, mattrobenolt commented on src/sentry/event_manager.py
> +                tags={'organization_id': project.organization_id},
@JTCunning Any preference on this tag name? Pretty sure this is what we use elsewhere. Or should we use `instance` instead? I still don't know when we should use which.

2017-12-07 00:59 UTC, macqueen commented
talked to ted and i'm going to update this to have an additional tag that'll allow us to count the number that needed to be processed vs not

2017-12-07 01:02 UTC, JTCunning commented
@mattrobenolt: We've traditionally only done "project_id" so if we think
the organization is a better object to track, that's the way to do it.

On Wed, Dec 6, 2017 at 4:57 PM Matt Robenolt <notifications@github.com>
wrote:

> *@mattrobenolt* commented on this pull request.
> ------------------------------
>
> In src/sentry/event_manager.py
> <https://github.com/getsentry/sentry/pull/6706#discussion_r155405271>:
>
> > @@ -671,6 +671,12 @@ def save(self, project, raw=False):
>                  project=project,
>                  sender=EventManager,
>              )
> +
> +            metrics.incr(
> +                'event.discarded',
> +                skip_internal=True,
> +                tags={'organization_id': project.organization_id},
>
> @JTCunning <https://github.com/jtcunning> Any preference on this tag
> name? Pretty sure this is what we use elsewhere. Or should we use instance
> instead? I still don't know when we should use which.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getsentry/sentry/pull/6706#pullrequestreview-81719249>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABImRnkmuf2kpaINBLUJc6gWy8z_jTQCks5s9zfsgaJpZM4Q4z3w>
> .
>

2017-12-07 01:04 UTC, mattrobenolt commented
Yeah, I'm explicitly referring to using the tag name `organization_id` vs using the `instance` kwarg.

I decided that we should track this per org instead of per project. Since the volume would be so low per project, and org more relates to usage and quotas. It'd make more sense for us to see "which orgs are using this the most".

2017-12-11 19:00 UTC, tkaemming requested changes
> talked to ted and i'm going to update this to have an additional tag that'll allow us to count the number that needed to be processed vs not

Recording here for posterity that I was wrong and you can just use the platform instead.

2017-12-13 19:44 UTC, tkaemming approved these changes
🍰

2017-12-13 21:31 UTC, merged