ci: Refactor frontend.yml CI workflow for clarity and maximum file coverage
getsentry/sentry pull request #67067
Opened 2024-03-15 19:09 UTC by ryan953

This updates the linting tool & file-selection rules to be consistent in dev and in CI. 

Specifically, the main thing I did here is to update `file-filters.yml` so that each tool (eslint, prettier, stylelint) has a specific list of file types to check. If those files, or their configs change, then that trigggers checks at both PR time, and after merge to master. I think the logic is easier to follow now, and it turns out that before it was really easy to skip stylelint for example.

I also updated vscode/settings.json to bring in some stuff from getsentry, so we have linting setup for json which was missing before.

All the files here should basically match their getsentry siblings. We could do better to share things and make sure things stay consistent, so this is a first step. Hopefully we just reduce churn and bugs here altogether.

The getsentry sibling is https://github.com/getsentry/getsentry/pull/13325

2024-03-15 19:09 UTC, ryan953 commented on .eslintignore
> -/scripts/*.js
There are two js files in here, lets just lint them

2024-03-15 19:11 UTC, ryan953 commented on .vscode/settings.json
> +  "[javascript][typescript][javascriptreact][typescriptreact]": {
weird syntax, but it'll keep things in sync forever which is good.

2024-03-15 19:11 UTC, ryan953 commented on .vscode/settings.json
> +  "[json][yaml]": {
yaml!

2024-03-15 19:12 UTC, ryan953 commented on package.json
> +    "lint:prettier": "prettier \"**/*.md\" \"**/*.yaml\" \"**/*.[jt]s(x)?\" --check",
need to treat js/ts/jsx/tsx files the same in all the places.

2024-03-15 19:13 UTC, ryan953 commented on .github/workflows/frontend.yml
> +      - name: lint
This one runs all the lint rules/tools on all the files. 

The tools are currently: biome, prettier, eslint, stylelint.

2024-03-18 20:58 UTC, ryan953 commented on .eslintrc.js
> +      files: ['static/**/*.spec.{ts,js}', 'tests/js/**/*.{ts,js}'],
Lots of tests are inside the static folder now

2024-03-18 20:58 UTC, ryan953 commented on .github/file-filters.yml
> +  - added|deleted|modified: 'fixtures/js-stubs/**/*'
Everything else in the PR is the same for sentry&getsentry, except this stuff (and where it's referenced down below)

2024-03-18 20:58 UTC, ryan953 commented on .github/file-filters.yml
> +  - *lintable_css_in_js_modified
You'll notice that usually there's a pair of file-lists... one to list all the files that we should run the tool against, and another that includes config files which we should watch

2024-03-18 20:58 UTC, ryan953 commented on .github/workflows/frontend.yml
> +          yarn lint:css
List this out to be explicit that we're doing the same 4 checks here as below

This is the 'run everything / on master' step
Below are the 'run against changed files' steps

2024-03-18 20:58 UTC, ryan953 commented on .github/workflows/frontend.yml
> -        if: ${{ always() && needs.files-changed.outputs.frontend_all == 'true' }}
The comment above suggests we should do this all the time, and the `frontend_src == 'true'` check is moved up in the tree, not needed here anymore.

2024-03-18 20:58 UTC, ryan953 commented on .vscode/extensions.json
> -    "tyriar.sort-lines"
sorted, and added `mkhl.direnv`

This is more important for getsentry. In getsentry we use direnv to find the sentry folder and do some stuff. Added here to for consistency.

2024-03-18 20:58 UTC, ryan953 commented on biome.json
> +    "enabled": false,
no need to battle with eslint/prettier

2024-03-19 13:14 UTC, asottile-sentry requested changes
this changes far too much in one patch to be reviewable

could you split this into multiple, reviewable patches -- in particular please avoid the changes which simply reorder conditions because it's distracting

2024-03-19 15:07 UTC, ryan953 commented
> this changes far too much in one patch to be reviewable

@asottile-sentry ack, yeah i'll split things up

2024-03-20 22:26 UTC, closed without merging