chore: Upgrade React to 15.6.2
getsentry/sentry pull request #6735
Opened 2017-12-11 23:07 UTC by lynnagara

2017-12-12 03:47 UTC, billyvg commented
Nice, tests are passing!

We should do a grep for `React.PropTypes` because I think I've seen a few places where its called. Should also check getsentry + make a tracking PR on getsentry to see if things break there.

2017-12-12 13:23 UTC, MaxBittker requested changes
sweeeeeeet 💯 

+1 on a getsentry tracking PR! also, i noticed two snapshots that got a lot shorter, possibly due to some async render condition?

2017-12-12 13:23 UTC, MaxBittker commented on tests/js/spec/views/__snapshots__/groupSimilarView.spec.jsx.snap
> +    <LoadingIndicator>
what happened here?

2017-12-12 13:23 UTC, MaxBittker commented on tests/js/spec/views/__snapshots__/groupMergedView.spec.jsx.snap
> +    <LoadingIndicator>
was this intentional?

2017-12-12 21:56 UTC, lynnagara commented on tests/js/spec/views/__snapshots__/groupSimilarView.spec.jsx.snap
> +    <LoadingIndicator>
Good pick up, thanks!

2017-12-15 08:53 UTC, MaxBittker approved these changes
💥 👍  love it

2017-12-18 19:09 UTC, merged