Remove Redis references from Sentry
getsentry/sentry pull request #67814
Opened 2024-03-27 19:23 UTC by xurui-c

As part of [deprecating unused rate limiters from the indexer](https://github.com/getsentry/getsentry/issues/13425), we want to remove references to the Redis VMS that were previously used by the indexer's cardinality rate limiting

Requires https://github.com/getsentry/getsentry/pull/13450

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2024-03-29 22:48 UTC, ayirr7 commented
I think it makes sense to remove the code that _uses_ the particular Sentry configurations first, i.e. let's maybe remove stuff like https://github.com/getsentry/sentry/blob/master/src/sentry/sentry_metrics/configuration.py#L87-L88 before we remove the actual configs like `SENTRY_METRICS_INDEXER_CARDINALITY_LIMITER_OPTIONS` from any repo. 

We've removed the code logic for the cardinality rate limiter already, next we can remove the parts of `MetricsIngestConfiguration` that used configs to initialize cardinality rate limiter clusters/other stuff, and then finally, we can remove the configs themselves. Tagging @john-z-yang as well - what do you think about this?

2024-04-01 10:38 UTC, aznclouds requested changes
Need informed

2024-04-02 21:18 UTC, john-z-yang approved these changes
This looks okay to me, just make sure you are still able to bring up the consumers locally before you merge please, just in case we missed anything

2024-04-02 22:04 UTC, xurui-c commented
> This looks okay to me, just make sure you are still able to bring up the consumers locally before you merge please, just in case we missed anything

confirmed. @ayirr7 is there anything else you'd like to double check before merging?

2024-04-02 23:27 UTC, ayirr7 approved these changes

2024-04-02 23:27 UTC, ayirr7 commented
@xurui-c, looks good to me. As long as we can run the pipeline locally and ingest data into Clickhouse, we're good.

2024-04-02 23:28 UTC, merged