Update logic showing the "Reprocess Event" action
getsentry/sentry pull request #68412
Opened 2024-04-08 09:42 UTC by Swatinem

The logic was updated so that all kinds of events that have debug files are eligible for reprocessing.

2024-04-18 16:15 UTC, armenzg requested changes
The BE changes look good.
Could you please split up this PR for BE and FE changes?

2024-04-18 16:25 UTC, Swatinem commented
> Could you please split up this PR for BE and FE changes?

Done, BE changes split into https://github.com/getsentry/sentry/pull/69204

2024-04-19 15:01 UTC, armenzg commented
> > Could you please split up this PR for BE and FE changes?
> 
> Done, BE changes split into #69204

Could you please remove the BE changes from this PR? You won't be able to merge this PR as long as both FE and BE changes are in the same PR.

2024-04-19 15:02 UTC, armenzg approved these changes
Could you please add the screenshot before and after to the description of the PR? It will help future people to look back at what changed.

2024-05-21 14:12 UTC, Swatinem commented
> Could you please add the screenshot before and after to the description of the PR?

There is no visual changes with this PR. It would just display this action more frequently: https://docs.sentry.io/product/issues/reprocessing/

2024-05-22 07:12 UTC, merged