feat(api): Change User Details endpoint to require sudo access
getsentry/sentry pull request #7046
Opened 2018-01-24 02:10 UTC by billyvg

Attempting to change your password/email/username will require sudo access.
 It will then update the rest of the payload.

2018-01-24 07:38 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes require @getsentry/security sign-off</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

### Security concerns found

- src/sentry/api/endpoints/sudo.py


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2018-01-24 22:20 UTC, macqueen approved these changes

2018-01-24 22:20 UTC, macqueen commented on src/sentry/api/endpoints/user_details.py
> +            # TODO(billy): Why is `user.has_usable_password()` false here
usually that's if a user has never had a password set. are these sso users or something?

2018-01-24 22:20 UTC, macqueen commented on src/sentry/api/endpoints/user_details.py
> +    def update_unprivileged_details(self, request, user):
i think this is fine

2018-01-24 22:20 UTC, macqueen commented on src/sentry/api/endpoints/user_details.py
> +        if request.DATA.get('passwordVerify') or \
not really sure if this is any cleaner, but you could do something like: 

`if any(k in request.DATA for k in ['passwordVerify', 'password', 'email', 'username']):`

2018-01-25 19:46 UTC, billyvg commented
@mattrobenolt can review since there's potential security concerns here?

2018-01-26 00:23 UTC, mattrobenolt requested changes
@billyvg when you get some time, mind running me through this IRL just so I'm clear? I'm missing the other bits of how this is implemented to give a better review.

2018-01-31 23:00 UTC, billyvg commented
@mattrobenolt This is ready for a review, I've merged the `user_appearance` endpoint into `user_details` and removed `password` and `emails` as fields that can be updated by this endpoint. There is a separate endpoint for adding emails and there will be a follow up PR to:
* change password (will be a new endpoint but I think should be merged into the `users/security` endpoint introduced in #7113)
* remove `user_appearance` endpoint and update JSX accordingly

2018-02-01 21:05 UTC, mattrobenolt approved these changes
wcgw

2018-02-02 18:32 UTC, merged