ref(replay): bump rrweb version to 2.18.0
getsentry/sentry pull request #72050
Opened 2024-06-04 20:16 UTC by michellewzhang

redo of https://github.com/getsentry/sentry/pull/71875

2024-06-04 20:42 UTC, c298lee approved these changes

2024-06-05 16:44 UTC, scttcper approved these changes

2024-06-05 17:10 UTC, billyvg requested changes
Blocking this so it doesn't accidentally get merged. Currently using this to test our mobile replay multi touch, but there's a bug in rrweb lib that breaks playback on certain replays with large CSS.

2024-06-07 20:06 UTC, billyvg approved these changes

2024-06-10 13:21 UTC, merged