feat(ui): Finish fine tuning UI
getsentry/sentry pull request #7239
Opened 2018-02-13 06:17 UTC by billyvg

+ change account notifications to be saveOnBlur

2018-02-13 06:20 UTC, getsentry-danger commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2018-02-15 23:08 UTC, lynnagara requested changes

2018-02-15 23:08 UTC, lynnagara commented on src/sentry/static/sentry/app/data/forms/accountNotificationSettings.jsx
> +      path: 'alerts/',
this is definitely nicer!

2018-02-16 22:07 UTC, billyvg commented
@lynnagara this is ready for a re-review, added email routing + an empty panel for it (i.e. it only has fine tuning link) because the old UI doesn't have a setting for "default", so can make incremental changes with that.

2018-02-20 19:26 UTC, lynnagara commented on src/sentry/static/sentry/app/data/forms/accountNotificationSettings.jsx
> +        help: tct('Alerts are defined in [locationPath]', {
It's returning a React element, field from config complains because it wants a string or function

2018-02-20 19:29 UTC, lynnagara commented
Played around a bit - email routing and weekly reports aren't working for me... is that expected?

2018-02-20 20:09 UTC, billyvg commented
What was not working with it? It should all be working (unless it was not rebased with latest API branch)

2018-02-20 22:18 UTC, lynnagara commented
@billyvg I don't see any results... do I need confirmed alternative emails, or?

<img width="835" alt="screen shot 2018-02-20 at 2 12 48 pm" src="https://user-images.githubusercontent.com/1779792/36452313-db4a6f7c-1648-11e8-8223-5ade0864919c.png">

2018-02-20 22:28 UTC, billyvg commented
@lynnagara do you have *any* verified emails?

2018-02-22 19:30 UTC, billyvg commented
@lynnagara can you re-review?

2018-02-22 21:19 UTC, lynnagara approved these changes

2018-02-22 23:01 UTC, merged