fix(feedback): catch snuba errors in update_user_reports task
getsentry/sentry pull request #76697
Opened 2024-08-28 20:35 UTC by aliu39

Related to, but doesn't fix [SENTRY-163P](https://sentry.sentry.io/issues/4502227101/)

2024-08-28 20:45 UTC, cmanallen requested changes

2024-08-28 20:45 UTC, cmanallen commented on src/sentry/tasks/update_user_reports.py
> +                sentry_sdk.set_tag("update_user_reports.eventstore_query_failed", True)
Move this above logger.exception.

2024-08-28 20:55 UTC, cmanallen commented
Let's add a limit that is some multiple of the ingest rate over a 15 minute period.

2024-08-29 04:47 UTC, aliu39 commented
> Let's add a limit that is some multiple of the ingest rate over a 15 minute period.

I don't think we should limit this query. Aside from the backlog from this issue, we usually don't expect many reports with missing events to make it past post process. The query is already limited by time range (last 24hr).

For clearing the backlog: https://sentry.slack.com/archives/CUHS29QJ0/p1724881027856289
Issue platform is totally fine to handle a burst of ~20k, which is worst case. It's possible tomorrow morning this backlog will be smaller too.
The problem is the rate limit of 1k/hour, per project. We can temporarily raise that by a generous amount. Under normal conditions, I think it's ok for this task to get rate limited.

2024-08-29 16:59 UTC, cmanallen approved these changes

2024-08-29 17:00 UTC, aliu39 commented
This actually isn't a backlog.. https://cloudlogging.app.goo.gl/CepGv7zXk2jKpCieA is from before the error and we always process roughly this amount (16k) of reports. My bad for the mis-diagnosis

2024-08-29 17:00 UTC, merged