feat(assistant): Add click tracking events for assistant
getsentry/sentry pull request #7764
Opened 2018-03-23 00:42 UTC by denamwangi

Is this the right approach? i.e. using a single `event_type` and tagging it with an action field?

2018-03-26 23:32 UTC, ehfeng requested changes

2018-03-26 23:32 UTC, ehfeng commented on src/sentry/static/sentry/app/components/assistant/helper.jsx
> +      cb('assistant.guide', {
We should discuss what this should be (whether action should be a part of this, so  `event_name` might be `assistant.opened`)

2018-03-27 18:37 UTC, denamwangi commented
Updated to capture actions in the `event_name`

2018-03-27 21:56 UTC, ehfeng approved these changes
I'd move the HookStore calls to AFTER the core logic is complete (in case there's an error, it doesn't break the UI). Approving, since it's non-blocking.

2018-03-28 01:04 UTC, denamwangi commented
Fair point- moved!

2018-03-28 19:55 UTC, merged