ref(toolbar): check allowed origins and update response templates
getsentry/sentry pull request #77756
Opened 2024-09-18 23:32 UTC by aliu39

This is a pretty cool branch name

Closes https://github.com/getsentry/sentry/issues/77214
Ref https://github.com/getsentry/sentry/issues/77577 (might close it too)

2024-09-19 23:12 UTC, aliu39 commented
Ready, but needs test coverage:
- unit tests for `url_matches`
- e2e tests making requests to `iframe_view`
  - project doesn't exist
  - missing REFERER
  - same cases as `url_matches`

2024-09-20 18:12 UTC, cmanallen requested changes
Finish the todos.  Add test coverage.

2024-09-20 18:12 UTC, cmanallen commented on src/sentry/toolbar/views/iframe_view.py
> +            response[header] = val
Let's just assign these statically.  I.e. without the class variable.  `response["X-Frame-Options"] = "ALLOWALL"`

2024-09-20 18:28 UTC, aliu39 commented on src/sentry/toolbar/utils/url.py
> +            return False
are you saying "." will always be in a hostname?

2024-09-20 20:00 UTC, aliu39 commented on src/sentry/toolbar/utils/url.py
> +            return False
Nvm, I totally messed up the logic here. We allow wildcards in target, not the referrer.

2024-09-21 01:42 UTC, aliu39 commented
Do we have any need for this response header? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

2024-09-23 17:54 UTC, ryan953 commented
> Do we have any need for this response header? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Maybe! But that'll be a separate PR i think. If we were to use that we would still want to run the check in python first to verify which type of response to return. If the domain is valid we might want to add that header with only the valid domain listed... I would not want to return a list of valid domains because that could be a leak of customer info.

ticketed: https://github.com/getsentry/sentry-toolbar/issues/29

2024-09-23 18:03 UTC, ryan953 approved these changes
looks good to me. I can't think of missing test cases right now

2024-09-24 20:20 UTC, cmanallen approved these changes

2024-09-24 21:27 UTC, merged