chore(grouping): Stop calling `_save_aggregate`
getsentry/sentry pull request #77838
Opened 2024-09-20 05:33 UTC by lobsterkatie

As of https://github.com/getsentry/sentry/pull/77027, all projects are using the new grouping config transition flow, because `project_uses_optimized_grouping` now always returns `True`. We can therefore start removing the old code path. 

This takes the first step in that direction by removing the call to the old version of the `_save_aggregate` function. Though this isn't strictly necessary before removing the function (since now no one should be going through the branch which calls it), this makes it extra obvious that nothing can go wrong when that happens.

2024-09-20 11:32 UTC, armenzg requested changes
Can you please make all changes in one shot? It does not seem to be too many changes and the PR should not be too overwhelming to review.

2024-09-20 11:32 UTC, armenzg commented on src/sentry/event_manager.py
> +    group_info = _save_aggregate_new(
Can we renamed it as part of this?

2024-09-20 17:00 UTC, lobsterkatie commented
> Can you please make all changes in one shot? It does not seem to be too many changes and the PR should not be too overwhelming to review.

Okay - I was going to do it in stages and PR as I went, but lemme actually do all the steps and see how big it ends up being. I'll leave this open for now but won't merge it.

2024-09-27 19:13 UTC, lobsterkatie commented
UPDATE:

I did the whole thing out, and it was pretty big, so I ended up splitting it in 4:

https://github.com/getsentry/sentry/pull/78260
https://github.com/getsentry/sentry/pull/78261
https://github.com/getsentry/sentry/pull/78262
https://github.com/getsentry/sentry/pull/78268

Closing this in favor of those.

2024-09-27 19:13 UTC, closed without merging