[feat] Add API functionality to call Seer's test generation endpoint
getsentry/sentry pull request #78518
Opened 2024-10-02 20:33 UTC by rohitvinnakota-codecov

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2024-10-02 20:50 UTC, jennmueng approved these changes
lgtm

2024-10-03 21:20 UTC, JoshFerge commented on src/sentry/api/endpoints/ai_unit_test_generation.py
> +        *args,
don't need to use kwargs for the variables you want to access -- can just add them as keywords

2024-10-03 21:24 UTC, JoshFerge requested changes
small nits around how APIs are usually done -- should just raise the error, don't need to write your own custom error response function. can poke around a few other sentry endpoints to see how we usually do those things. should also use a validator instead of putting validation logic in the endpoint body.

the primary concern i have is about security -- how do we check authorization and prevent someone passing in repo names / github orgs that their team doesnt own.

are there any endpoints that do similar things in sentry?

2024-10-03 21:24 UTC, JoshFerge commented on src/sentry/api/endpoints/ai_unit_test_generation.py
> +            return self._respond_with_error("Invalid pull request number.", 400)
please use a `Validator`. I would recommend not using `_respond_with_error`. Can see how errors are handled on other endpoints.

2024-10-03 21:26 UTC, JoshFerge commented on src/sentry/api/endpoints/ai_unit_test_generation.py
> +TIMEOUT_SECONDS = 60 * 30  # 30 minutes
`timedelta(minutes=30)`.

2024-10-03 21:28 UTC, JoshFerge commented on src/sentry/api/endpoints/ai_unit_test_generation.py
> +            )
you shouldn't need to manually do any of this. errors are already handled and 500s logged at the middleware level https://github.com/getsentry/sentry/blob/07396b7608ee6a7857a35641626b70027f6bc95d/src/sentry/api/base.py#L324

2024-10-03 21:36 UTC, JoshFerge reviewed
seems like sentry has linked Repositories as a concept. may want to see how these are used and if checking that a linked repository exists could be a good idea https://github.com/getsentry/sentry/blob/07396b7608ee6a7857a35641626b70027f6bc95d/src/sentry/models/repository.py#L28

2024-10-04 16:41 UTC, JoshFerge commented
> Thanks for the review @JoshFerge
> 
> The consumer of this API will be [this](https://github.com/getsentry/getsentry/pull/15270) class
> 
> Regarding security: The class above^ will do validation on the incoming request(which is fired by github). It verifies the signature of the request, as well as whether the user has write access to the repo they are specifying. This is the only route through which this API will be called.
> 
> Regarding custom errors: This API is called via an LLM interface, and the user expects some form of human readable response. The LLM basically takes the response from this API and converts it into a "chat message" format so I prefer to add some context here.
> 
> Regarding Repository object: Seer has a model defined for the Repo object as well and the params passed are validated by that model.
> 
> I switched to using keywords and a validator.
> 
> Please let me know if you have any questions, these changes are time sensitive so I'm always open to creating follow ups to clean things up.

do we have a spec for this anywhere? I'm confused on the flow of this endpoint being called

2024-10-08 17:45 UTC, closed without merging