chore: Add session-replay-rage-click-issue-creation flagpole guard
getsentry/sentry pull request #78620
Opened 2024-10-04 17:02 UTC by ryan953

2024-10-04 17:09 UTC, michellewzhang approved these changes

2024-10-04 17:10 UTC, aliu39 approved these changes

2024-10-07 16:34 UTC, aliu39 requested changes
Use an option similar to `feedback.organizations.slug-denylist`

2024-11-20 14:53 UTC, JoshFerge commented on src/sentry/features/temporary.py
> +    manager.add("organizations:session-replay-hydration-error-issue-creation", OrganizationFeature, FeatureHandlerStrategy.FLAGPOLE, api_expose=True)
does this need to be exposed in the api?

2024-11-20 14:54 UTC, JoshFerge commented on src/sentry/replays/usecases/ingest/dom_index.py
> +    has_feature = features.has(
why do we need a feature and a killswitch? (on top of the ingest flag created by the issue platform for this issue type)

2024-11-20 15:10 UTC, closed without merging