fix(unmerge): Allow members to unmerge
getsentry/sentry pull request #79125
Opened 2024-10-15 18:21 UTC by jangjodi

Change unmerge FE call to use new PUT endpoint
This will allow the endpoint to use [PUT permissions](https://github.com/getsentry/sentry/blob/423fedeb968c757f1455ee915b67840f48a275ba/src/sentry/api/bases/group.py#L26-L32) instead of DELETE permissions, and allow the members to unmerge

2024-10-15 20:22 UTC, armenzg approved these changes

2024-10-18 16:35 UTC, JoshFerge requested changes
we can't roll out frontend and backend in the same PR. can we release the backend PR first in a backwards compatible way, then switch over the frontend?

2024-10-18 16:44 UTC, jangjodi commented
> we can't roll out frontend and backend in the same PR. can we release the backend PR first in a backwards compatible way, then switch over the frontend?

yeah, I just merged in the backend change that was a base branch for this one. I rebased and it should just be the FE changes now!

2024-10-18 17:02 UTC, JoshFerge approved these changes
ah that makes sense! thank you!

2024-10-21 15:28 UTC, merged