chore(tests): Add types to `insta_snapshot`
getsentry/sentry pull request #79180
Opened 2024-10-16 14:40 UTC by lobsterkatie

This adds typing to the `insta_snapshot` fixture. The function which is returned is typed using a protocol rather a callable in order to account for the optional parameters/default values, and to allow passing things via keyword.

2024-10-16 20:37 UTC, armenzg requested changes

2024-10-16 20:37 UTC, armenzg commented on src/sentry/testutils/pytest/fixtures.py
Could you investigate the purpose of this in the pyproject.toml?
<img width="406" alt="image" src="https://github.com/user-attachments/assets/18297368-077f-41db-971e-4d55fa279591">

I want to make sure these changes get tested by mypy.

Could you also please add it to the `# begin: stronger typing` section?

2024-10-16 20:43 UTC, asottile-sentry commented on src/sentry/testutils/pytest/fixtures.py
that section is for pytest doing assertion rewriting -- but agree this should end up in the better typing section (I think it's actually in the ignored section right now so removing it from there should be a blocker to this work either way!)

2024-10-16 20:58 UTC, lobsterkatie commented on src/sentry/testutils/pytest/fixtures.py
I can vouch for the fact that mypy tests this, because it took a number of tries for me to get it to stop yelling at me!

But yeah, I'll make sure it gets put into the appropriate pyproject section.

2024-10-17 16:40 UTC, lobsterkatie commented on src/sentry/testutils/pytest/fixtures.py
UPDATE: Okay, so it's not ready for the stronger typing section - there are a few dozen untyped functions in there which would need typing for that to work - but as I say, mypy is definitely checking this, because if you type `insta_snapshot` slightly differently, it notices and won't have it.

Can you lift your hold, please?

2024-10-17 17:14 UTC, armenzg approved these changes

2024-10-17 20:55 UTC, merged