feat: split processing store for post_process_forwarder
getsentry/sentry pull request #79633
Opened 2024-10-23 19:55 UTC by bmckerry

This PR adds an `eventstream_type` param to the post-process-forwarder.

2024-10-24 19:03 UTC, lynnagara approved these changes

2024-10-24 22:07 UTC, kneeyo1 approved these changes

2024-10-24 22:21 UTC, kneeyo1 requested changes

2024-10-24 22:21 UTC, kneeyo1 commented on src/sentry/post_process_forwarder/post_process_forwarder.py
> +        eventstream_type: str | None = None,
I think this needs to be passed in actually as static args for the post process forwarders: 

shoud be here https://github.com/getsentry/sentry/blob/master/src/sentry/consumers/__init__.py#L370-L389

and they can be passed in as static args.

2024-10-25 16:43 UTC, kneeyo1 approved these changes

2024-10-28 14:45 UTC, merged