feat(minidump): Store minidumps in a temp directory for debugging
getsentry/sentry pull request #8036
Opened 2018-04-12 23:14 UTC by jan-auer

This PR stores minidumps in a temporary location on our webservers for debugging purposes. They should be deleted within 24-48 hours.

2018-04-12 23:16 UTC, jan-auer commented
@JTCunning I wasn't sure if there's a setting to determine the `/tmp` location, so I hard coded it for now. Maybe it would be better to turn that off during tests and development and only activate it in production - is there something similar we can do or a configuration option that I can reuse for this?

2018-04-13 07:18 UTC, mitsuhiko commented on src/sentry/web/api.py
> +MINIDUMP_TMP_PATH = '/tmp/minidump'
can we put this behind a sentry settings key?

2018-04-13 07:19 UTC, mitsuhiko approved these changes

2018-04-13 07:19 UTC, mitsuhiko requested changes
approved by accident

2018-04-13 08:32 UTC, mitsuhiko approved these changes

2018-04-16 15:49 UTC, jan-auer commented
@JTCunning note that this will require two new configs to be set in prod: 

```py
# Toggles whether minidumps should be cached
SENTRY_MINIDUMP_CACHE = False
# The location for cached minidumps
SENTRY_MINIDUMP_PATH = '/tmp/minidump'
```

2018-04-16 17:41 UTC, JTCunning approved these changes
🍪

2018-04-17 06:35 UTC, merged