fix(assistant): Move record assistant cues to guidestore to decrease dups
getsentry/sentry pull request #8153
Opened 2018-04-23 22:55 UTC by denamwangi

Currently we rely on reacts' `componentDidMount` to record when a fresh guide is presented to a user but this is problematic for cases like the `issue tour` assistant guide where cycling through older events will refresh the page. This moves essentially the same behaviour to `guidestore` which hangs on to which guide was served up previously and only records the event if the new guide is different than the last one.

2018-04-23 23:03 UTC, MaxBittker requested changes
this looks like an elegant improvement - but maybe it's complicated enough logic to warrant a test? (not sure if this is covered by existing test cases)

also, this version seems easier to test than the old code!

2018-04-23 23:03 UTC, MaxBittker commented on src/sentry/static/sentry/app/stores/guideStore.jsx
> +    if (!this.state.prevGuide) {
can these cases be simplified? this code looks redundant somehow

2018-04-23 23:03 UTC, MaxBittker commented on src/sentry/static/sentry/app/stores/guideStore.jsx
> +    bestGuide ? this.updatePrevGuide(bestGuide) : null;
two things - i would favor if statements over ternaries for side effects, and I think it's better to put this logic into the update method and have the "don't do this if X" check live there.

2018-04-24 01:03 UTC, ehfeng submitted a review, later dismissed
testing github flow thing

2018-04-24 17:31 UTC, MaxBittker approved these changes
the code looks good to me, just had a nit and a question about the testcase

2018-04-24 17:31 UTC, MaxBittker commented on src/sentry/static/sentry/app/stores/guideStore.jsx
> +      (this.state.prevGuide && this.state.prevGuide.id !== bestGuide.id)
i think you can actually safely drop `this.state.prevGuide && ` because it will never evaluate the second expression if the first is falsey

2018-04-24 17:31 UTC, MaxBittker commented on tests/js/spec/stores/guideStore.spec.jsx
> +    expect(mockRecordCue).toHaveBeenCalledTimes(1);
this test seems to cover the branches according to codecov but I'm not sure how it does (but could just be missing something). Could you explain with a comment or write another case like `it('should not update on duplicates')`?

I was looking to see (in pseudocode) something like:

triggerguide(A)
expect(mockRecordCue).toHaveBeenCalledTimes(1);
triggerguide(A)
expect(mockRecordCue).toHaveBeenCalledTimes(1);
triggerguide(B)
expect(mockRecordCue).toHaveBeenCalledTimes(2);

2018-04-24 21:59 UTC, merged