db: Migrate File name to text
getsentry/sentry pull request #8244
Opened 2018-04-30 07:45 UTC by jan-auer

This migrates `sentry_file.name` to type `TEXT` to match all other name columns. 

Fixes SENTRY-6DA
Fixes SENTRY-6HA

2018-04-30 08:12 UTC, mattrobenolt requested changes

2018-04-30 08:12 UTC, mattrobenolt commented on src/sentry/south_migrations/0410_auto__chg_field_file_name.py
> +    is_dangerous = False
Make this True please.

2018-04-30 10:21 UTC, mitsuhiko requested changes
see above

2018-04-30 10:47 UTC, jan-auer commented
@mitsuhiko @mattrobenolt updated, although I am raising concerns for leaving this `varchar`. In virtually all models referencing this (such as release files, etc) the names are `TEXT`.

2018-04-30 10:48 UTC, jan-auer commented on src/sentry/south_migrations/0410_auto__chg_field_file_name.py
> +    is_dangerous = False
Still necessary with varchar(255)?

2018-05-02 10:03 UTC, mitsuhiko commented
@mattrobenolt can we clarify what policy we want? Because last time we went to extend a limit (releases) I remember that conversation was that bumping varchar lengths is free on postgres anyways so no concern.

(Apparently for free changes from `VARCHAR` to `TEXT` one needs to use `ALTER TABLE ... SET DATA TYPE`)

2018-05-02 17:39 UTC, mattrobenolt commented
I'm pretty confident doing an ALTER from varchat to text is free. I can just apply this migration by hand in production first to make sure it's fine. Would still warrant `is_dangerous = True` flag since it'll then conflict. But I plan on just running the SQL by hand. I like going to text because then this is never an issue again, and length can just be enforced (if we cared) by a constraint instead, or make sure the application enforces it at data input time. This way we just never have to alter the column again.

2018-05-02 17:43 UTC, mattrobenolt commented
Yeah, so I just applied this:

```
getsentry=# alter table sentry_file alter column name type text;
ALTER TABLE
```

And it was instantaneous. So we can move forward with just making this TextField instead, we just now need `is_dangerous = True` or the migration will fail since it's already text.

I'd much rather this be the pattern moving forward so we don't have to think about it.

The only reason _not_ to keep this as text, is when you have an index on the column. And this is just a problem with MySQL iirc. It can't index a full text field, but you typically wouldn't want to do that anyways, and you should have another md5 hash or something that's indexed on instead.

But anyways, we're good to go here with making this TextField, and the change has already been applied in production.

2018-05-02 19:41 UTC, jan-auer commented
Rebased onto `master` and updated the migration.

2018-05-02 19:42 UTC, mattrobenolt approved these changes

2018-05-07 09:18 UTC, mitsuhiko approved these changes

2018-05-07 09:18 UTC, merged