feat: Add assertMaxWriteQueries to test max queries against a table
getsentry/sentry pull request #8446
Opened 2018-05-15 13:11 UTC by HazAT

2018-05-15 14:29 UTC, mitsuhiko requested changes

2018-05-15 14:29 UTC, mitsuhiko commented on src/sentry/testutils/cases.py
> +            match = re.search(r"u'([^']*)'", query['sql'])
Instead of this use `ast.literal_eval`:

```
>>> import ast
>>> ast.literal_eval('u"Hello World!"')
u'Hello World!'
```

2018-05-15 15:18 UTC, mattrobenolt commented
What’s wrong with just the builtin assertNumQueries? I get that this provides a bit more behavior, but seems a little overkill imo. I don’t think we typically care which tables, and read vs write usually. It’s just as easy to introduce a bunch of extra read queries that cause a similar incident.

2018-05-15 18:07 UTC, mattrobenolt commented
How does this work with JOINs and subqueries, etc? Which table are they counted against? All of them? One for each?

2018-05-15 20:14 UTC, mattrobenolt commented
The only other comment I have with this is why explicitly only testing for write queries? What about read queries? I think these are all valid since it's more likely that we introduce unintended read queries.

2018-05-16 08:27 UTC, HazAT commented
@mattrobenolt The library we use for parsing the query doesn't really work reliable for subqueries/joins to count the "reads".
https://github.com/andialbrecht/sqlparse

So we could invest more time to make it work by parsing the queries manually to correctly get the "read" count but not sure if we should really do this now.

2018-05-23 08:02 UTC, mitsuhiko approved these changes

2018-05-23 08:16 UTC, merged