ref: Truncate float fingerprints
getsentry/sentry pull request #8726
Opened 2018-06-13 13:39 UTC by jan-auer

2018-06-13 17:52 UTC, jan-auer commented
Before merging, we need to sample how many customers will be affected by this and potentially coordinate a broadcast to warn them about changed grouping behavior.

2018-06-13 18:30 UTC, mitsuhiko requested changes

2018-06-13 18:30 UTC, mitsuhiko commented on src/sentry/event_manager.py
> +                return text(int(f)) if f < (1 << 53) else None
This needs an `abs()` as it does not handle negative numbers.

2018-06-22 08:40 UTC, mitsuhiko commented
@jan-auer we should merge this now. There is a low chance of this producing new groups based on the measurements we did.

2018-06-22 09:01 UTC, mitsuhiko approved these changes

2018-06-22 09:20 UTC, mitsuhiko approved these changes

2018-06-22 10:48 UTC, merged