fix(relay): Update last_seen on every heartbeat
getsentry/sentry pull request #8742
Opened 2018-06-14 15:25 UTC by jan-auer

2018-06-14 15:45 UTC, mitsuhiko requested changes

2018-06-14 15:45 UTC, mitsuhiko commented on src/sentry/api/endpoints/relay_heartbeat.py
> +        request.relay.last_seen = timezone.now()
We need to debounce this. Ideally we only push this once a minute max.

2018-06-15 09:32 UTC, jan-auer commented
@mitsuhiko updated.

2018-06-15 10:44 UTC, mitsuhiko approved these changes

2018-06-15 10:55 UTC, merged