Fix path of sentry-email-avatar.png
getsentry/sentry pull request #8916
Opened 2018-07-03 10:22 UTC by albertvaka

It was using a local path, from an email, so the image was broken.

2018-07-03 12:18 UTC, mattrobenolt requested changes
I don’t know the answer off the top of my head, but rejecting this because this will break if STATIC_URL is already an absolute url. Which is the case for sentry.io.

2018-07-03 12:18 UTC, albertvaka commented
@getsentry/ui

2018-07-03 12:28 UTC, albertvaka commented
Don't think so. If that was the case, the [template tag `absolute_asset_url`](https://github.com/getsentry/sentry/blob/master/src/sentry/templatetags/sentry_assets.py#L16) which is implemented in exactly the same way and used in [every image](https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/emails/base.html#L23) in [every email](https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/emails/reports/body.html#L338) would be broken.

2018-07-04 00:27 UTC, mattrobenolt approved these changes

2018-07-04 00:28 UTC, mattrobenolt commented
Thanks for hanging in there @albertvaka. I forgot that our `absolute_uri` function wouldn't clobber an already absolute url, so this is fine. 🍕

2018-07-04 00:28 UTC, merged

2018-07-04 07:51 UTC, albertvaka commented
Glad to help :)