WIP: feat(integrations): Support inbound status sync core
getsentry/sentry pull request #9016
Opened 2018-07-11 23:45 UTC by macqueen

- needs to be updated to use the new model
- needs tests (but i didn't want to add them until this is using the new model)

@lauryndbrown does this seem like it'll be useable for vsts?

2018-07-12 01:45 UTC, lauryndbrown requested changes

2018-07-12 01:45 UTC, lauryndbrown commented on src/sentry/integrations/issues.py
> +            updated_resolve = Group.objects.filter(
The two sections with `groups_to_resolve` vs `groups_to_unresolve` should probably be the same function it's pretty similar code.  Something like:
``` 
def change_status(self, groups, status, activity_type):
     updated_groups = Group.objects.filter(
                id__in=[g.id for g in groups],
      ).exclude(
                status=status,
     ).update(
                status=status,
     )
    if updated_groups:
       for group in groups:
              Activity.objects.create(
                  project=group.project,
                  group=group,
                   type=activity_type,
               )
```
so when you call it all you'll have to do is:
```
if groups_to_resolve:
   self.change_status(groups_to_resolve, GroupStatus.RESOLVED, Activity.SET_RESOLVED
``` 
And similarly with unresolved.

2018-07-12 01:45 UTC, lauryndbrown commented on src/sentry/integrations/issues.py
> +    def should_resolve(self, configuration, data):
The `should_resolve` and `should_unresolve` methods have me a bit confused. Could you give me an example of how these would be used? Is there a reason they are separate methods? If so, what would be the differences between the two?

2018-07-13 01:40 UTC, macqueen commented
disclaimer, haven't run the latest update at all and need to add tests, so maybe don't look at this yet 🙂

2018-07-13 23:29 UTC, macqueen commented
ok, @lauryndbrown added a couple tests and implemented your suggestions if you wanna take another look!

2018-07-16 18:11 UTC, lauryndbrown approved these changes
Looks good to me! Just have to get tests running.

2018-07-16 19:46 UTC, merged