feat(minidump): Support gzipped crashpad requests
getsentry/sentry pull request #9238
Opened 2018-07-30 09:02 UTC by jan-auer

Updated implementation of https://github.com/getsentry/sentry/pull/9208.

The issue was that [DjangoRestFrameworkCompatMiddleware](https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/middleware/__init__.py#L140) cached the request body and the decoded stream was never read. This was not caught by our tests, because Raven is not set up there (although middlewares were run).

2018-08-01 18:57 UTC, mattrobenolt requested changes
Ok, so reading this more and fully understanding what went wrong, we should be explicit on where raven injects it's middleware. Meaning, we should explicitly put it after our `proxy.*` middlewares. Then raven won't inject itself in the front.

Looking at this now, your ChunkedMiddleware is also broken becuase of the DRF middleware behavior because it too, replaces `request._stream`, after it's already read.

So I'd vote we back out the extra changes you've added to detect `request._body`, and we just manually put `raven.contrib.django.middleware.DjangoRestFrameworkCompatMiddleware` into our middleware stack after these.

2018-08-03 07:07 UTC, jan-auer commented
@mattrobenolt updated.

2018-08-13 11:08 UTC, mitsuhiko approved these changes

2018-08-13 20:23 UTC, mattrobenolt approved these changes
:+1: This is much better. Thanks for making the changes.

2018-08-13 20:24 UTC, merged