feat(integrations): Bitbucket issue search
getsentry/sentry pull request #9476
Opened 2018-08-22 23:10 UTC by MeredithAnya

autocomplete search for issues for bitbucket

2018-08-23 20:09 UTC, EvanPurkhiser commented on src/sentry/integrations/bitbucket/issues.py
>          repo_choices, default_repo, issues = self.get_repo_choices(**kwargs)
I'm changing this in a separate PR, we don't need `get_repo_choices` also returning issues (which we're now not even using anymore)

2018-08-29 18:41 UTC, mnoble requested changes
Looks good overall – should add some tests. At the least for the endpoint.

2018-08-30 17:31 UTC, MeredithAnya commented on src/sentry/integrations/bitbucket/issues.py
> +                'url': autocomplete_url,
> Does it pass `name` as a query param somehow? 

Yeah - in the search endpoint it's the field so we know whether we are searching 'repo' vs. 'externalIssue' vs. etc

2018-08-30 17:32 UTC, mnoble approved these changes
👍

2018-09-04 16:51 UTC, merged